package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
)

// SetMyShortname is the resolver for the setMyShortname field.
func (r *mutationResolver) SetMyShortname(ctx context.Context, shortname string) (*model.MyAccount, error) {
	if err := r.plexams.SetMyShortname(ctx, shortname); err != nil {
		return nil, err
	}
	return r.plexams.MyAccount(ctx)
}

// SetMyJiraToken is the resolver for the setMyJiraToken field.
func (r *mutationResolver) SetMyJiraToken(ctx context.Context, token string) (*model.MyAccount, error) {
	if err := r.plexams.SetMyJiraToken(ctx, token); err != nil {
		return nil, err
	}
	return r.plexams.MyAccount(ctx)
}

// RemoveMyJiraToken is the resolver for the removeMyJiraToken field.
func (r *mutationResolver) RemoveMyJiraToken(ctx context.Context) (*model.MyAccount, error) {
	if err := r.plexams.RemoveMyJiraToken(ctx); err != nil {
		return nil, err
	}
	return r.plexams.MyAccount(ctx)
}

// MyAccount is the resolver for the myAccount field.
func (r *queryResolver) MyAccount(ctx context.Context) (*model.MyAccount, error) {
	return r.plexams.MyAccount(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
