package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
)

// UpsertAdditionalExam is the resolver for the upsertAdditionalExam field.
func (r *mutationResolver) UpsertAdditionalExam(ctx context.Context, input model.AdditionalExamInput) (*model.AdditionalExam, error) {
	rooms := make([]*model.AdditionalExamRoom, 0, len(input.Rooms))
	for _, room := range input.Rooms {
		rooms = append(rooms, &model.AdditionalExamRoom{
			RoomName:      room.RoomName,
			InvigilatorID: room.InvigilatorID,
			Duration:      room.Duration,
			IsReserve:     room.IsReserve,
			StudentCount:  room.StudentCount,
			IsHandicap:    room.IsHandicap,
		})
	}
	return r.plexams.UpsertAdditionalExam(ctx, &model.AdditionalExam{
		Ancode: input.Ancode,
		Date:   input.Date,
		Time:   input.Time,
		Rooms:  rooms,
	})
}

// DeleteAdditionalExam is the resolver for the deleteAdditionalExam field.
func (r *mutationResolver) DeleteAdditionalExam(ctx context.Context, ancode int) (bool, error) {
	return r.plexams.DeleteAdditionalExam(ctx, ancode)
}

// AdditionalExams is the resolver for the additionalExams field.
func (r *queryResolver) AdditionalExams(ctx context.Context) ([]*model.AdditionalExam, error) {
	return r.plexams.AdditionalExams(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
