package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/rs/zerolog/log"
)

// AdminOverview is the resolver for the adminOverview field. Gated on role ADMIN in the
// backend: a plain query is not covered by the VIEWER write-gate in AroundOperations, so
// the resolver itself must enforce it.
func (r *queryResolver) AdminOverview(ctx context.Context) (*model.AdminOverview, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	return r.plexams.AdminOverview(ctx)
}

// SchedulerStatus is the resolver for the schedulerStatus field. Gated on role ADMIN.
func (r *queryResolver) SchedulerStatus(ctx context.Context) (*model.SchedulerStatus, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	return r.plexams.SchedulerStatus(ctx)
}

// SendAdminDigestNow is the resolver for the sendAdminDigestNow field. It sends the admin
// digest on demand and streams the progress; dryRun sends the preview to the test address
// instead of the admins. Gated on role ADMIN. The send runs on a detached context so it
// finishes even if the client leaves the page.
func (r *subscriptionResolver) SendAdminDigestNow(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	ch := make(chan *model.LogLine, 256)
	reporter := newStreamReporter(ctx, ch)
	opCtx := context.WithoutCancel(ctx)
	go func() {
		defer close(ch)
		if err := r.plexams.SendAdminDigest(opCtx, !dryRun, reporter); err != nil {
			log.Error().Err(err).Msg("triggered admin digest failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		reporter.emit(model.LogLevelDone, "done")
	}()
	return ch, nil
}
