package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AnnyBookings is the resolver for the annyBookings field.
func (r *queryResolver) AnnyBookings(ctx context.Context, room *string) ([]*model.AnnyBooking, error) {
	return r.plexams.AnnyBookings(ctx, room)
}

// AllAnnyBookings is the resolver for the allAnnyBookings field.
func (r *queryResolver) AllAnnyBookings(ctx context.Context) ([]*model.AnnyBooking, error) {
	return r.plexams.AllAnnyBookings(ctx)
}
