package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetAnnyPersonalizationNames is the resolver for the setAnnyPersonalizationNames field.
func (r *mutationResolver) SetAnnyPersonalizationNames(ctx context.Context, names []string) (*model.AnnyConfig, error) {
	return r.plexams.SetAnnyPersonalizationNames(ctx, names)
}

// AllAnnyBookings is the resolver for the allAnnyBookings field.
func (r *queryResolver) AllAnnyBookings(ctx context.Context) ([]*model.AnnyBooking, error) {
	return r.plexams.AllAnnyBookings(ctx)
}
