package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// GenerateAssembledExams is the resolver for the generateAssembledExams field.
func (r *mutationResolver) GenerateAssembledExams(ctx context.Context) (*model.GenerateAssembledExamsResult, error) {
	return r.plexams.GenerateAssembledExams(ctx)
}

// ResetAssembledExams is the resolver for the resetAssembledExams field.
func (r *mutationResolver) ResetAssembledExams(ctx context.Context) (int, error) {
	return r.plexams.ResetAssembledExams(ctx)
}

// AssembledExamsState is the resolver for the assembledExamsState field.
func (r *queryResolver) AssembledExamsState(ctx context.Context) (*model.AssembledExamsState, error) {
	return r.plexams.AssembledExamsState(ctx)
}
