package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/obcode/plexams.go/graph/model"
)

// SetUser is the resolver for the setUser field.
func (r *mutationResolver) SetUser(ctx context.Context, email string, name string, role model.Role) (*model.User, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	return r.plexams.SetUser(ctx, email, name, role)
}

// RemoveUser is the resolver for the removeUser field.
func (r *mutationResolver) RemoveUser(ctx context.Context, email string) (bool, error) {
	if err := requireAdmin(ctx); err != nil {
		return false, err
	}
	return r.plexams.RemoveUser(ctx, email)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	if user := UserFromContext(ctx); user != nil {
		return user, nil
	}
	return nil, fmt.Errorf("no authenticated user in context")
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.plexams.GetUsers(ctx)
}
