package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// BackupStatus is the resolver for the backupStatus field.
func (r *queryResolver) BackupStatus(ctx context.Context) (*model.BackupStatus, error) {
	return r.plexams.BackupStatus(ctx)
}
