package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/obcode/plexams.go/plexams"
)

// ClearEmailAttachments is the resolver for the clearEmailAttachments field.
func (r *mutationResolver) ClearEmailAttachments(ctx context.Context, kind string) (int, error) {
	return r.plexams.ClearEmailAttachments(ctx, kind)
}

// EmailAttachments is the resolver for the emailAttachments field.
func (r *queryResolver) EmailAttachments(ctx context.Context, kind string) ([]*model.EmailAttachmentInfo, error) {
	return r.plexams.EmailAttachmentInfos(ctx, kind)
}

// SendEmailExaHm is the resolver for the sendEmailExaHM field.
func (r *subscriptionResolver) SendEmailExaHm(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailExaHM(ctx, run, reporter)
	}), nil
}

// SendEmailConstraints is the resolver for the sendEmailConstraints field.
func (r *subscriptionResolver) SendEmailConstraints(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailConstraints(ctx, run, reporter)
	}), nil
}

// SendEmailPrepared is the resolver for the sendEmailPrepared field.
func (r *subscriptionResolver) SendEmailPrepared(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailPrepared(ctx, run, reporter)
	}), nil
}

// SendEmailDraft is the resolver for the sendEmailDraft field.
func (r *subscriptionResolver) SendEmailDraft(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailDraft(run, reporter)
	}), nil
}

// SendEmailPublishedExams is the resolver for the sendEmailPublishedExams field.
func (r *subscriptionResolver) SendEmailPublishedExams(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailPublishedExams(ctx, run, reporter)
	}), nil
}

// SendEmailPublishedRooms is the resolver for the sendEmailPublishedRooms field.
func (r *subscriptionResolver) SendEmailPublishedRooms(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailPublishedRooms(ctx, run, reporter)
	}), nil
}

// SendEmailInvigilations is the resolver for the sendEmailInvigilations field.
func (r *subscriptionResolver) SendEmailInvigilations(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailInvigilations(ctx, run, reporter)
	}), nil
}

// SendEmailInvigilationsMissing is the resolver for the sendEmailInvigilationsMissing field.
func (r *subscriptionResolver) SendEmailInvigilationsMissing(ctx context.Context, run bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		return r.plexams.SendEmailInvigilationReqMissing(ctx, run, reporter)
	}), nil
}
