package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetEmailTemplate is the resolver for the setEmailTemplate field.
func (r *mutationResolver) SetEmailTemplate(ctx context.Context, name string, markdown string) (*model.EmailTemplate, error) {
	return r.plexams.SetEmailTemplate(ctx, name, markdown)
}

// ResetEmailTemplate is the resolver for the resetEmailTemplate field.
func (r *mutationResolver) ResetEmailTemplate(ctx context.Context, name string) (bool, error) {
	return r.plexams.ResetEmailTemplate(ctx, name)
}

// EmailTemplates is the resolver for the emailTemplates field.
func (r *queryResolver) EmailTemplates(ctx context.Context) ([]*model.EmailTemplate, error) {
	return r.plexams.EmailTemplates(ctx)
}

// EmailTemplateFunctions is the resolver for the emailTemplateFunctions field.
func (r *queryResolver) EmailTemplateFunctions(ctx context.Context) ([]*model.EmailTemplateFunction, error) {
	return r.plexams.EmailTemplateFunctions(ctx)
}

// RenderEmailTemplatePreview is the resolver for the renderEmailTemplatePreview field.
func (r *queryResolver) RenderEmailTemplatePreview(ctx context.Context, name string, markdown string) (*model.EmailTemplatePreview, error) {
	return r.plexams.RenderEmailTemplatePreview(ctx, name, markdown)
}
