package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetStudentConflictDecision is the resolver for the setStudentConflictDecision field.
func (r *mutationResolver) SetStudentConflictDecision(ctx context.Context, ancode1 int, ancode2 int, mtknr string, decision model.ConflictDecision) (bool, error) {
	return r.plexams.SetStudentConflictDecision(ctx, ancode1, ancode2, mtknr, decision)
}

// RemoveStudentConflictDecision is the resolver for the removeStudentConflictDecision field.
func (r *mutationResolver) RemoveStudentConflictDecision(ctx context.Context, ancode1 int, ancode2 int, mtknr string) (bool, error) {
	return r.plexams.RemoveStudentConflictDecision(ctx, ancode1, ancode2, mtknr)
}

// SetExamsCanShareSlot is the resolver for the setExamsCanShareSlot field.
func (r *mutationResolver) SetExamsCanShareSlot(ctx context.Context, ancode1 int, ancode2 int) (bool, error) {
	return r.plexams.SetExamsCanShareSlot(ctx, ancode1, ancode2)
}

// RemoveExamsCanShareSlot is the resolver for the removeExamsCanShareSlot field.
func (r *mutationResolver) RemoveExamsCanShareSlot(ctx context.Context, ancode1 int, ancode2 int) (bool, error) {
	return r.plexams.RemoveExamsCanShareSlot(ctx, ancode1, ancode2)
}
