package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetExamDuration is the resolver for the setExamDuration field.
func (r *mutationResolver) SetExamDuration(ctx context.Context, ancode int, duration int) (*model.ExamDurationOverride, error) {
	return r.plexams.SetExamDuration(ctx, ancode, duration)
}

// RemoveExamDuration is the resolver for the removeExamDuration field.
func (r *mutationResolver) RemoveExamDuration(ctx context.Context, ancode int) (bool, error) {
	return r.plexams.RemoveExamDuration(ctx, ancode)
}
