package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/obcode/plexams.go/graph/model"
)

// Exams is the resolver for the exams field.
func (r *queryResolver) Exams(ctx context.Context) ([]*model.Exam, error) {
	panic(fmt.Errorf("not implemented: Exams - exams"))
}

// Exam is the resolver for the exam field.
func (r *queryResolver) Exam(ctx context.Context, ancode int) (*model.Exam, error) {
	panic(fmt.Errorf("not implemented: Exam - exam"))
}
