package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/rs/zerolog/log"
)

// FixExamRoomsPhase is the resolver for the fixExamRoomsPhase field.
func (r *mutationResolver) FixExamRoomsPhase(ctx context.Context) (int, error) {
	return r.plexams.FixExamRoomsPhase(ctx)
}

// UnfixExamRoomsPhase is the resolver for the unfixExamRoomsPhase field.
func (r *mutationResolver) UnfixExamRoomsPhase(ctx context.Context) (bool, error) {
	if err := r.plexams.UnfixExamRoomsPhase(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// ResetExamSchedule is the resolver for the resetExamSchedule field.
func (r *mutationResolver) ResetExamSchedule(ctx context.Context) (int, error) {
	return r.plexams.ResetExamSchedule(ctx)
}

// ExamScheduleConstraints is the resolver for the examScheduleConstraints field.
func (r *queryResolver) ExamScheduleConstraints(ctx context.Context) ([]*model.OptimizerConstraint, error) {
	infos := r.plexams.ExamScheduleConstraints()
	out := make([]*model.OptimizerConstraint, 0, len(infos))
	for _, i := range infos {
		out = append(out, &model.OptimizerConstraint{
			Name: i.Name, Title: i.Title, Description: i.Description,
			Kind: i.Kind.String(), Weight: i.Weight, Tier: i.Tier,
		})
	}
	return out, nil
}

// GenerateExamSchedule is the resolver for the generateExamSchedule field. It runs the
// automatic exam-schedule generation and streams its terminal-style output line by
// line. The operation runs on a background context so a started (non-dry-run) run
// finishes and writes even if the client disconnects; the subscription context only
// governs the streaming.
func (r *subscriptionResolver) GenerateExamSchedule(ctx context.Context, dryRun bool, seed *int, iterations *int, ignoreRatings *bool) (<-chan *model.LogLine, error) {
	ch := make(chan *model.LogLine, 256)

	var seedVal int64
	if seed != nil {
		seedVal = int64(*seed)
	}
	var iterVal int
	if iterations != nil {
		iterVal = *iterations
	}
	ignore := ignoreRatings != nil && *ignoreRatings
	reporter := newStreamReporter(ctx, ch)

	go func() {
		defer close(ch)
		result, err := r.plexams.GenerateExamSchedule(context.Background(), dryRun, seedVal, iterVal, ignore, reporter)
		if err != nil {
			log.Error().Err(err).Msg("generate exam schedule failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		if result != nil {
			reporter.send(&model.LogLine{Level: model.LogLevelResult, Text: "report", ExamReport: examScheduleReport(result)})
		}
		reporter.emit(model.LogLevelDone, "done")
	}()

	return ch, nil
}

// GenerateExamRoomsPhase is the resolver for the generateExamRoomsPhase field. It runs
// phase A (EXaHM/SEB into the booked T-building slots) and streams its output line by
// line. Like GenerateExamSchedule it runs on a background context so a started non-dry
// run finishes even if the client disconnects.
func (r *subscriptionResolver) GenerateExamRoomsPhase(ctx context.Context, dryRun bool, seed *int, iterations *int) (<-chan *model.LogLine, error) {
	ch := make(chan *model.LogLine, 256)

	var seedVal int64
	if seed != nil {
		seedVal = int64(*seed)
	}
	var iterVal int
	if iterations != nil {
		iterVal = *iterations
	}
	reporter := newStreamReporter(ctx, ch)

	go func() {
		defer close(ch)
		result, err := r.plexams.GenerateExamRoomsPhase(context.Background(), dryRun, seedVal, iterVal, reporter)
		if err != nil {
			log.Error().Err(err).Msg("generate exam rooms phase failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		if result != nil {
			reporter.send(&model.LogLine{Level: model.LogLevelResult, Text: "report", ExamReport: examScheduleReport(result)})
		}
		reporter.emit(model.LogLevelDone, "done")
	}()

	return ch, nil
}
