package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AcceptStudentConflict is the resolver for the acceptStudentConflict field.
func (r *mutationResolver) AcceptStudentConflict(ctx context.Context, ancode1 int, ancode2 int, mtknr string) (bool, error) {
	return r.plexams.AcceptStudentConflict(ctx, ancode1, ancode2, mtknr)
}

// RemoveStudentConflictAcceptance is the resolver for the removeStudentConflictAcceptance field.
func (r *mutationResolver) RemoveStudentConflictAcceptance(ctx context.Context, ancode1 int, ancode2 int, mtknr string) (bool, error) {
	return r.plexams.RemoveStudentConflictAcceptance(ctx, ancode1, ancode2, mtknr)
}

// SetExamsCanShareSlot is the resolver for the setExamsCanShareSlot field.
func (r *mutationResolver) SetExamsCanShareSlot(ctx context.Context, ancode1 int, ancode2 int) (bool, error) {
	return r.plexams.SetExamsCanShareSlot(ctx, ancode1, ancode2)
}

// RemoveExamsCanShareSlot is the resolver for the removeExamsCanShareSlot field.
func (r *mutationResolver) RemoveExamsCanShareSlot(ctx context.Context, ancode1 int, ancode2 int) (bool, error) {
	return r.plexams.RemoveExamsCanShareSlot(ctx, ancode1, ancode2)
}

// ExamScheduleConflicts is the resolver for the examScheduleConflicts field.
func (r *queryResolver) ExamScheduleConflicts(ctx context.Context) ([]*model.ExamScheduleConflict, error) {
	return r.plexams.ExamScheduleConflicts(ctx)
}

// StudentConflictAcceptances is the resolver for the studentConflictAcceptances field.
func (r *queryResolver) StudentConflictAcceptances(ctx context.Context) ([]*model.StudentConflictAcceptance, error) {
	return r.plexams.StudentConflictAcceptances(ctx)
}

// ExamsCanShareSlot is the resolver for the examsCanShareSlot field.
func (r *queryResolver) ExamsCanShareSlot(ctx context.Context) ([]*model.ExamPair, error) {
	return r.plexams.ExamsCanShareSlot(ctx)
}

// CanShareSlotSuggestions is the resolver for the canShareSlotSuggestions field.
func (r *queryResolver) CanShareSlotSuggestions(ctx context.Context) ([]*model.ExamPair, error) {
	return r.plexams.CanShareSlotSuggestions(ctx)
}
