package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// InvigilatorTodos is the resolver for the invigilatorTodos field.
func (r *queryResolver) InvigilatorTodos(ctx context.Context) (*model.InvigilationTodos, error) {
	return r.plexams.GetInvigilationTodos(ctx)
}

// InvigilatorsWithReq is the resolver for the invigilatorsWithReq field.
func (r *queryResolver) InvigilatorsWithReq(ctx context.Context) ([]*model.Invigilator, error) {
	return r.plexams.InvigilatorsWithReq(ctx)
}

// RoomsWithInvigilationsForSlot is the resolver for the roomsWithInvigilationsForSlot field.
func (r *queryResolver) RoomsWithInvigilationsForSlot(ctx context.Context, day int, time int) (*model.InvigilationSlot, error) {
	return r.plexams.RoomsWithInvigilationsForSlot(ctx, day, time)
}

// InvigilatorsForDay is the resolver for the invigilatorsForDay field.
func (r *queryResolver) InvigilatorsForDay(ctx context.Context, day int) (*model.InvigilatorsForDay, error) {
	return r.plexams.InvigilatorsForDay(ctx, day)
}

// Invigilator is the resolver for the invigilator field.
func (r *queryResolver) Invigilator(ctx context.Context, room string, day int, time int) (*model.Teacher, error) {
	return r.plexams.Invigilator(ctx, room, day, time)
}
