package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// PrePlanInvigilation is the resolver for the prePlanInvigilation field.
func (r *mutationResolver) PrePlanInvigilation(ctx context.Context, invigilatorID int, day int, slot int, roomName *string) (bool, error) {
	return r.plexams.PreAddInvigilation(ctx, invigilatorID, day, slot, roomName)
}

// PrePlanInvigilationInSlot is the resolver for the prePlanInvigilationInSlot field.
func (r *mutationResolver) PrePlanInvigilationInSlot(ctx context.Context, day int, slot int, roomName *string) (bool, error) {
	return r.plexams.PrePlanInvigilationInSlot(ctx, day, slot, roomName)
}

// InvigilatorTodos is the resolver for the invigilatorTodos field.
func (r *queryResolver) InvigilatorTodos(ctx context.Context) (*model.InvigilationTodos, error) {
	return r.plexams.GetInvigilationTodos(ctx)
}

// InvigilatorsWithReq is the resolver for the invigilatorsWithReq field.
func (r *queryResolver) InvigilatorsWithReq(ctx context.Context) ([]*model.Invigilator, error) {
	return r.plexams.InvigilatorsWithReq(ctx)
}

// InvigilatorsExcludedByConfig is the resolver for the invigilatorsExcludedByConfig field.
func (r *queryResolver) InvigilatorsExcludedByConfig(ctx context.Context) ([]*model.Invigilator, error) {
	return r.plexams.InvigilatorsExcludedByConfig(ctx)
}

// RoomsWithInvigilationsForSlot is the resolver for the roomsWithInvigilationsForSlot field.
func (r *queryResolver) RoomsWithInvigilationsForSlot(ctx context.Context, day int, time int) (*model.InvigilationSlot, error) {
	return r.plexams.RoomsWithInvigilationsForSlot(ctx, day, time)
}

// InvigilatorsForDay is the resolver for the invigilatorsForDay field.
func (r *queryResolver) InvigilatorsForDay(ctx context.Context, day int) (*model.InvigilatorsForDay, error) {
	return r.plexams.InvigilatorsForDay(ctx, day)
}

// Invigilator is the resolver for the invigilator field.
func (r *queryResolver) Invigilator(ctx context.Context, room string, day int, time int) (*model.Teacher, error) {
	return r.plexams.Invigilator(ctx, room, day, time)
}

// PrePlannedInvigilations is the resolver for the prePlannedInvigilations field.
func (r *queryResolver) PrePlannedInvigilations(ctx context.Context) ([]*model.PrePlannedInvigilation, error) {
	return r.plexams.PrePlannedInvigilations(ctx)
}
