package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// CreateJiraIssue is the resolver for the createJiraIssue field.
func (r *mutationResolver) CreateJiraIssue(ctx context.Context, project *string, issueType *string, summary string, description *string) (*model.JiraIssue, error) {
	return r.plexams.CreateJiraIssue(ctx, project, issueType, summary, description)
}

// AddJiraComment is the resolver for the addJiraComment field.
func (r *mutationResolver) AddJiraComment(ctx context.Context, key string, body string) (bool, error) {
	return r.plexams.AddJiraComment(ctx, key, body)
}

// TransitionJiraIssue is the resolver for the transitionJiraIssue field.
func (r *mutationResolver) TransitionJiraIssue(ctx context.Context, key string, transitionID string) (bool, error) {
	return r.plexams.TransitionJiraIssue(ctx, key, transitionID)
}

// JiraConnection is the resolver for the jiraConnection field.
func (r *queryResolver) JiraConnection(ctx context.Context) (*model.JiraUser, error) {
	return r.plexams.JiraConnection(ctx)
}

// JiraIssue is the resolver for the jiraIssue field.
func (r *queryResolver) JiraIssue(ctx context.Context, key string) (*model.JiraIssue, error) {
	return r.plexams.GetJiraIssue(ctx, key)
}

// JiraTransitions is the resolver for the jiraTransitions field.
func (r *queryResolver) JiraTransitions(ctx context.Context, key string) ([]*model.JiraTransition, error) {
	return r.plexams.JiraTransitions(ctx, key)
}

// JiraOpenIssues is the resolver for the jiraOpenIssues field.
func (r *queryResolver) JiraOpenIssues(ctx context.Context, project *string) ([]*model.JiraIssue, error) {
	return r.plexams.JiraOpenIssues(ctx, project)
}

// JiraOpenIssuesByType is the resolver for the jiraOpenIssuesByType field.
func (r *queryResolver) JiraOpenIssuesByType(ctx context.Context, project *string) ([]*model.JiraIssueGroup, error) {
	return r.plexams.JiraOpenIssuesByType(ctx, project)
}

// JiraOpenIssuesByRequestType is the resolver for the jiraOpenIssuesByRequestType field.
func (r *queryResolver) JiraOpenIssuesByRequestType(ctx context.Context, project *string) ([]*model.JiraRequestTypeGroup, error) {
	return r.plexams.JiraOpenIssuesByRequestType(ctx, project)
}
