package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// ImportJointExams is the resolver for the importJointExams field.
func (r *mutationResolver) ImportJointExams(ctx context.Context, csv string) (*model.ImportJointResult, error) {
	return r.plexams.ImportJointExams(ctx, csv)
}

// SetExternalExamTime is the resolver for the setExternalExamTime field.
func (r *mutationResolver) SetExternalExamTime(ctx context.Context, ancode int, date string, time string) (bool, error) {
	return r.plexams.SetExternalExamTime(ctx, ancode, date, time)
}

// SetJointZpaLink is the resolver for the setJointZpaLink field.
func (r *mutationResolver) SetJointZpaLink(ctx context.Context, program string, primussAncode int, zpaAncode int) (*model.JointExam, error) {
	return r.plexams.SetJointZpaLink(ctx, program, primussAncode, zpaAncode)
}

// RemoveJointLink is the resolver for the removeJointLink field.
func (r *mutationResolver) RemoveJointLink(ctx context.Context, program string, primussAncode int) (*model.JointExam, error) {
	return r.plexams.RemoveJointLink(ctx, program, primussAncode)
}

// JointZpaCandidates is the resolver for the jointZpaCandidates field.
func (r *queryResolver) JointZpaCandidates(ctx context.Context, program string, primussAncode int) ([]*model.ZPAExam, error) {
	return r.plexams.JointZpaCandidates(ctx, program, primussAncode)
}
