package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// ImportMucDaiExams is the resolver for the importMucDaiExams field.
func (r *mutationResolver) ImportMucDaiExams(ctx context.Context, csv string) (*model.ImportMucDaiResult, error) {
	return r.plexams.ImportMucDaiExams(ctx, csv)
}
