package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/obcode/plexams.go/graph/model"
)

// MutationLog is the resolver for the mutationLog field.
func (r *queryResolver) MutationLog(ctx context.Context, typeArg *string, name *string, ancode *int, args []*model.ArgFilterInput, user *string, since *time.Time, until *time.Time, limit *int) ([]*model.MutationLogEntry, error) {
	return r.plexams.MutationLog(ctx, typeArg, name, ancode, args, user, since, until, limit)
}

// MutationLogNames is the resolver for the mutationLogNames field.
func (r *queryResolver) MutationLogNames(ctx context.Context) ([]string, error) {
	return r.plexams.MutationLogNames(ctx)
}
