package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// Ntas is the resolver for the ntas field.
func (r *queryResolver) Ntas(ctx context.Context) ([]*model.NTA, error) {
	return r.plexams.Ntas(ctx)
}

// NtasWithRegs is the resolver for the ntasWithRegs field.
func (r *queryResolver) NtasWithRegs(ctx context.Context) ([]*model.Student, error) {
	return r.plexams.NtasWithRegs(ctx)
}
