package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AddNta is the resolver for the addNTA field.
func (r *mutationResolver) AddNta(ctx context.Context, input model.NTAInput) (*model.NTA, error) {
	return r.plexams.AddNta(ctx, input)
}

// UpdateNta is the resolver for the updateNTA field.
func (r *mutationResolver) UpdateNta(ctx context.Context, input model.NTAInput) (*model.NTA, error) {
	return r.plexams.UpdateNta(ctx, input)
}

// SetNTAActive is the resolver for the setNTAActive field.
func (r *mutationResolver) SetNTAActive(ctx context.Context, mtknr string, active bool) (*model.NTA, error) {
	return r.plexams.SetNTAActive(ctx, mtknr, active)
}

// Ntas is the resolver for the ntas field.
func (r *queryResolver) Ntas(ctx context.Context) ([]*model.NTA, error) {
	return r.plexams.Ntas(ctx)
}

// NtasWithRegs is the resolver for the ntasWithRegs field.
func (r *queryResolver) NtasWithRegs(ctx context.Context) ([]*model.Student, error) {
	return r.plexams.NtasWithRegs(ctx)
}

// Deprecated: Nta is the resolver for the nta field.
func (r *queryResolver) Nta(ctx context.Context, mtknr string) (*model.NTAWithRegs, error) {
	return r.plexams.Nta(ctx, mtknr)
}

// ExamsWithNtas is the resolver for the examsWithNtas field.
func (r *queryResolver) ExamsWithNtas(ctx context.Context) ([]*model.PlannedExam, error) {
	return r.plexams.ExamsWithNtas(ctx)
}
