package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AddNtaRoomAloneWaiver is the resolver for the addNtaRoomAloneWaiver field.
func (r *mutationResolver) AddNtaRoomAloneWaiver(ctx context.Context, mtknr string, ancode int, reason string) (*model.NtaRoomAloneWaiver, error) {
	return r.plexams.AddNtaRoomAloneWaiver(ctx, mtknr, ancode, reason)
}

// RemoveNtaRoomAloneWaiver is the resolver for the removeNtaRoomAloneWaiver field.
func (r *mutationResolver) RemoveNtaRoomAloneWaiver(ctx context.Context, mtknr string, ancode int) (bool, error) {
	return r.plexams.RemoveNtaRoomAloneWaiver(ctx, mtknr, ancode)
}

// NtaRoomAloneWaivers is the resolver for the ntaRoomAloneWaivers field.
func (r *queryResolver) NtaRoomAloneWaivers(ctx context.Context) ([]*model.NtaRoomAloneWaiver, error) {
	return r.plexams.NtaRoomAloneWaivers(ctx)
}
