package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetPlaner is the resolver for the setPlaner field.
func (r *mutationResolver) SetPlaner(ctx context.Context, name string, email string) (*model.Planer, error) {
	return r.plexams.SetPlaner(ctx, name, email)
}

// Planer is the resolver for the planer field.
func (r *queryResolver) Planer(ctx context.Context) (*model.Planer, error) {
	return r.plexams.GetPlaner(ctx)
}
