package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/obcode/plexams.go/graph/model"
)

// SetExamTime is the resolver for the setExamTime field.
func (r *mutationResolver) SetExamTime(ctx context.Context, ancode int, starttime time.Time) (bool, error) {
	return r.plexams.SetExamTime(ctx, ancode, starttime)
}

// AllProgramsInPlan is the resolver for the allProgramsInPlan field.
func (r *queryResolver) AllProgramsInPlan(ctx context.Context) ([]string, error) {
	return r.plexams.AllProgramsInPlan(ctx)
}

// AncodesInPlan is the resolver for the ancodesInPlan field.
func (r *queryResolver) AncodesInPlan(ctx context.Context) ([]int, error) {
	return r.plexams.AncodesInPlan(ctx)
}

// ExamerNamesInPlan is the resolver for the examerNamesInPlan field.
func (r *queryResolver) ExamerInPlan(ctx context.Context) ([]*model.ExamerInPlan, error) {
	return r.plexams.ExamerInPlan(ctx)
}

// ExamersWithExamsPlannedByMe is the resolver for the examersWithExamsPlannedByMe field.
func (r *queryResolver) ExamersWithExamsPlannedByMe(ctx context.Context) ([]*model.Teacher, error) {
	return r.plexams.ExamersWithExamsPlannedByMe(ctx)
}

// PreExamsAt is the resolver for the preExamsAt field.
func (r *queryResolver) PreExamsAt(ctx context.Context, starttime time.Time) ([]*model.PreExam, error) {
	return r.plexams.PreExamsAt(ctx, starttime)
}

// ExamsAt is the resolver for the examsAt field.
func (r *queryResolver) ExamsAt(ctx context.Context, starttime time.Time) ([]*model.PlannedExam, error) {
	return r.plexams.ExamsAt(ctx, starttime)
}

// ExamsWithoutSlot is the resolver for the examsWithoutSlot field.
func (r *queryResolver) ExamsWithoutSlot(ctx context.Context) ([]*model.PlannedExam, error) {
	return r.plexams.ExamsWithoutSlot(ctx)
}

// ExamsNotOnSlotGrid is the resolver for the examsNotOnSlotGrid field.
func (r *queryResolver) ExamsNotOnSlotGrid(ctx context.Context) ([]*model.PlannedExam, error) {
	return r.plexams.ExamsNotOnSlotGrid(ctx)
}

// AllowedSlots is the resolver for the allowedSlots field.
func (r *queryResolver) AllowedSlots(ctx context.Context, ancode int) ([]*model.Slot, error) {
	return r.plexams.AllowedSlots(ctx, ancode)
}

// AwkwardSlots is the resolver for the awkwardSlots field.
func (r *queryResolver) AwkwardSlots(ctx context.Context, ancode int) ([]*model.Slot, error) {
	return r.plexams.AwkwardSlots(ctx, ancode)
}
