package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// SetPlanningCondition is the resolver for the setPlanningCondition field.
func (r *mutationResolver) SetPlanningCondition(ctx context.Context, key string, done bool) (*model.PlanningState, error) {
	return r.plexams.SetPlanningCondition(ctx, key, done)
}

// PlanningState is the resolver for the planningState field.
func (r *queryResolver) PlanningState(ctx context.Context) (*model.PlanningState, error) {
	return r.plexams.PlanningState(ctx)
}
