package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// PreplanBookingSuggestions is the resolver for the preplanBookingSuggestions field.
func (r *queryResolver) PreplanBookingSuggestions(ctx context.Context, keepAssigned bool) (*model.PreplanBookingProposal, error) {
	return r.plexams.PreplanBookingSuggestions(ctx, keepAssigned)
}
