package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// GeneratePreparation is the resolver for the generatePreparation field.
func (r *mutationResolver) GeneratePreparation(ctx context.Context) (*model.GeneratePreparationResult, error) {
	return r.plexams.GeneratePreparation(ctx)
}
