package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// GeneratePreplanAssignment is the resolver for the generatePreplanAssignment field.
func (r *mutationResolver) GeneratePreplanAssignment(ctx context.Context, keepAssigned *bool) (*model.PreplanValidation, error) {
	keep := false
	if keepAssigned != nil {
		keep = *keepAssigned
	}
	return r.plexams.GeneratePreplanAssignment(ctx, keep)
}

// ValidatePreplanAssignment is the resolver for the validatePreplanAssignment field.
func (r *queryResolver) ValidatePreplanAssignment(ctx context.Context) (*model.PreplanValidation, error) {
	return r.plexams.ValidatePreplanAssignment(ctx)
}
