package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/obcode/plexams.go/graph/model"
)

// AddPreplanExam is the resolver for the addPreplanExam field.
func (r *mutationResolver) AddPreplanExam(ctx context.Context, input model.PreplanExamInput) (*model.PreplanExam, error) {
	return r.plexams.AddPreplanExam(ctx, &input)
}

// UpdatePreplanExam is the resolver for the updatePreplanExam field.
func (r *mutationResolver) UpdatePreplanExam(ctx context.Context, id int, input model.PreplanExamInput) (*model.PreplanExam, error) {
	return r.plexams.UpdatePreplanExam(ctx, id, &input)
}

// DeletePreplanExam is the resolver for the deletePreplanExam field.
func (r *mutationResolver) DeletePreplanExam(ctx context.Context, id int) (bool, error) {
	return r.plexams.DeletePreplanExam(ctx, id)
}

// ResetPreplanTimes is the resolver for the resetPreplanTimes field.
func (r *mutationResolver) ResetPreplanTimes(ctx context.Context) (int, error) {
	return r.plexams.ResetPreplanTimes(ctx)
}

// SetPreplanExamTime is the resolver for the setPreplanExamTime field.
func (r *mutationResolver) SetPreplanExamTime(ctx context.Context, id int, starttime *time.Time) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamTime(ctx, id, starttime)
}

// ConnectPreplanExamToAncode is the resolver for the connectPreplanExamToAncode field.
func (r *mutationResolver) ConnectPreplanExamToAncode(ctx context.Context, id int, ancode int) (*model.PreplanExam, error) {
	return r.plexams.ConnectPreplanExamToAncode(ctx, id, ancode)
}

// DisconnectPreplanExam is the resolver for the disconnectPreplanExam field.
func (r *mutationResolver) DisconnectPreplanExam(ctx context.Context, id int) (*model.PreplanExam, error) {
	return r.plexams.DisconnectPreplanExam(ctx, id)
}

// SetPreplanExamFixed is the resolver for the setPreplanExamFixed field.
func (r *mutationResolver) SetPreplanExamFixed(ctx context.Context, id int, fixed bool) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamFixed(ctx, id, fixed)
}

// SetPreplanExamNotSameSlot is the resolver for the setPreplanExamNotSameSlot field.
func (r *mutationResolver) SetPreplanExamNotSameSlot(ctx context.Context, id int, otherID int, conflict bool) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamNotSameSlot(ctx, id, otherID, conflict)
}

// SetPreplanExamCanShareSlot is the resolver for the setPreplanExamCanShareSlot field.
func (r *mutationResolver) SetPreplanExamCanShareSlot(ctx context.Context, id int, otherID int, canShare bool) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamCanShareSlot(ctx, id, otherID, canShare)
}

// SetPreplanExamConstraints is the resolver for the setPreplanExamConstraints field.
func (r *mutationResolver) SetPreplanExamConstraints(ctx context.Context, id int, constraints model.ConstraintsInput) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamConstraints(ctx, id, &constraints)
}

// PreplanExams is the resolver for the preplanExams field.
func (r *queryResolver) PreplanExams(ctx context.Context) ([]*model.PreplanExam, error) {
	return r.plexams.PreplanExams(ctx)
}

// PreplanExam is the resolver for the preplanExam field.
func (r *queryResolver) PreplanExam(ctx context.Context, id int) (*model.PreplanExam, error) {
	return r.plexams.PreplanExam(ctx, id)
}

// PreplanExamAncodeSuggestions is the resolver for the preplanExamAncodeSuggestions field.
func (r *queryResolver) PreplanExamAncodeSuggestions(ctx context.Context, id int) ([]*model.ZPAExam, error) {
	return r.plexams.PreplanExamAncodeSuggestions(ctx, id)
}

// PreplanSameSlotGroups is the resolver for the preplanSameSlotGroups field.
func (r *queryResolver) PreplanSameSlotGroups(ctx context.Context) ([]*model.PreplanSameSlotGroup, error) {
	return r.plexams.PreplanSameSlotGroups(ctx)
}
