package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// PreplanOverview is the resolver for the preplanOverview field.
func (r *queryResolver) PreplanOverview(ctx context.Context) (*model.PreplanOverview, error) {
	return r.plexams.PreplanOverview(ctx)
}
