package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AddPreplanExam is the resolver for the addPreplanExam field.
func (r *mutationResolver) AddPreplanExam(ctx context.Context, input model.PreplanExamInput) (*model.PreplanExam, error) {
	return r.plexams.AddPreplanExam(ctx, &input)
}

// UpdatePreplanExam is the resolver for the updatePreplanExam field.
func (r *mutationResolver) UpdatePreplanExam(ctx context.Context, id int, input model.PreplanExamInput) (*model.PreplanExam, error) {
	return r.plexams.UpdatePreplanExam(ctx, id, &input)
}

// DeletePreplanExam is the resolver for the deletePreplanExam field.
func (r *mutationResolver) DeletePreplanExam(ctx context.Context, id int) (bool, error) {
	return r.plexams.DeletePreplanExam(ctx, id)
}

// SetPreplanExamSlot is the resolver for the setPreplanExamSlot field.
func (r *mutationResolver) SetPreplanExamSlot(ctx context.Context, id int, dayNumber *int, slotNumber *int) (*model.PreplanExam, error) {
	return r.plexams.SetPreplanExamSlot(ctx, id, dayNumber, slotNumber)
}

// PreplanExams is the resolver for the preplanExams field.
func (r *queryResolver) PreplanExams(ctx context.Context) ([]*model.PreplanExam, error) {
	return r.plexams.PreplanExams(ctx)
}

// PreplanExam is the resolver for the preplanExam field.
func (r *queryResolver) PreplanExam(ctx context.Context, id int) (*model.PreplanExam, error) {
	return r.plexams.PreplanExam(ctx, id)
}
