package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// ResetPrimussData is the resolver for the resetPrimussData field.
func (r *mutationResolver) ResetPrimussData(ctx context.Context) ([]string, error) {
	return r.plexams.ResetPrimussData(ctx)
}

// AddStudentReg is the resolver for the addStudentReg field.
func (r *mutationResolver) AddStudentReg(ctx context.Context, program string, ancode int, mtknr string) (bool, error) {
	if err := r.plexams.AddStudentReg(ctx, program, ancode, mtknr); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveStudentReg is the resolver for the removeStudentReg field.
func (r *mutationResolver) RemoveStudentReg(ctx context.Context, program string, ancode int, mtknr string) (int, error) {
	return r.plexams.RemoveStudentReg(ctx, program, ancode, mtknr)
}

// PrimussExams is the resolver for the primussExams field.
func (r *queryResolver) PrimussExams(ctx context.Context) ([]*model.PrimussExamByProgram, error) {
	return r.plexams.PrimussExams(ctx)
}

// PrimussExam is the resolver for the primussExam field.
func (r *queryResolver) PrimussExam(ctx context.Context, program string, ancode int) (*model.PrimussExam, error) {
	return r.plexams.GetPrimussExam(ctx, program, ancode)
}

// PrimussExamsForAnCode is the resolver for the primussExamsForAnCode field.
func (r *queryResolver) PrimussExamsForAnCode(ctx context.Context, ancode int) ([]*model.PrimussExam, error) {
	return r.plexams.GetPrimussExamsForAncode(ctx, ancode)
}

// StudentRegsForProgram is the resolver for the studentRegsForProgram field.
func (r *queryResolver) StudentRegsForProgram(ctx context.Context, program string) ([]*model.StudentReg, error) {
	return r.plexams.StudentRegsForProgram(ctx, program)
}
