package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/obcode/plexams.go/graph/model"
)

// SetRoomRequestApproved is the resolver for the setRoomRequestApproved field.
func (r *mutationResolver) SetRoomRequestApproved(ctx context.Context, room string, starttime time.Time, approved bool) (*model.RoomRequest, error) {
	return r.plexams.SetRoomRequestApproved(ctx, room, starttime, approved)
}

// SetRoomRequestActive is the resolver for the setRoomRequestActive field.
func (r *mutationResolver) SetRoomRequestActive(ctx context.Context, room string, starttime time.Time, active bool) (*model.RoomRequest, error) {
	return r.plexams.SetRoomRequestActive(ctx, room, starttime, active)
}

// ApplyRoomRequestsPreview is the resolver for the applyRoomRequestsPreview field.
func (r *mutationResolver) ApplyRoomRequestsPreview(ctx context.Context, force bool) (int, error) {
	return r.plexams.ApplyRoomRequestsPreview(ctx, force)
}

// AddRoomRequest is the resolver for the addRoomRequest field.
func (r *mutationResolver) AddRoomRequest(ctx context.Context, room string, starttime time.Time, from time.Time, until time.Time) (*model.RoomRequest, error) {
	return r.plexams.AddRoomRequest(ctx, room, starttime, from, until)
}

// UpdateRoomRequestTime is the resolver for the updateRoomRequestTime field.
func (r *mutationResolver) UpdateRoomRequestTime(ctx context.Context, room string, starttime time.Time, from time.Time, until time.Time) (*model.RoomRequest, error) {
	return r.plexams.UpdateRoomRequestTime(ctx, room, starttime, from, until)
}

// RoomRequests is the resolver for the roomRequests field.
func (r *queryResolver) RoomRequests(ctx context.Context) ([]*model.RoomRequest, error) {
	return r.plexams.RoomRequests(ctx)
}

// RoomRequestsPreview is the resolver for the roomRequestsPreview field.
func (r *queryResolver) RoomRequestsPreview(ctx context.Context) ([]*model.RoomRequestPreview, error) {
	return r.plexams.GenerateRoomRequestsPreview(ctx)
}
