package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
	"github.com/obcode/plexams.go/plexams"
)

// PrePlanRoom is the resolver for the prePlanRoom field.
func (r *mutationResolver) PrePlanRoom(ctx context.Context, ancode int, roomName string, reserve bool, mtknr *string, seats *int) (bool, error) {
	return r.plexams.PreAddRoomToExam(ctx, ancode, roomName, mtknr, reserve, seats)
}

// RemovePrePlannedRoom is the resolver for the removePrePlannedRoom field.
func (r *mutationResolver) RemovePrePlannedRoom(ctx context.Context, ancode int, roomName string, mtknr *string) (bool, error) {
	return r.plexams.RemovePrePlannedRoom(ctx, ancode, roomName, mtknr)
}

// BlockRoomForSlot is the resolver for the blockRoomForSlot field.
func (r *mutationResolver) BlockRoomForSlot(ctx context.Context, room string, day int, slot int, reason *string) (*model.BlockedRoom, error) {
	return r.plexams.BlockRoomForSlot(ctx, room, day, slot, reason)
}

// UnblockRoomForSlot is the resolver for the unblockRoomForSlot field.
func (r *mutationResolver) UnblockRoomForSlot(ctx context.Context, room string, day int, slot int) (bool, error) {
	return r.plexams.UnblockRoomForSlot(ctx, room, day, slot)
}

// BlockRoomForSlots is the resolver for the blockRoomForSlots field.
func (r *mutationResolver) BlockRoomForSlots(ctx context.Context, room string, slots []*model.SlotInput, reason *string) ([]*model.BlockedRoom, error) {
	return r.plexams.BlockRoomForSlots(ctx, room, slots, reason)
}

// UnblockRoomForSlots is the resolver for the unblockRoomForSlots field.
func (r *mutationResolver) UnblockRoomForSlots(ctx context.Context, room string, slots []*model.SlotInput) (int, error) {
	return r.plexams.UnblockRoomForSlots(ctx, room, slots)
}

// SetRoomActive is the resolver for the setRoomActive field.
func (r *mutationResolver) SetRoomActive(ctx context.Context, name string, active bool) (*model.Room, error) {
	return r.plexams.SetRoomActive(ctx, name, active)
}

// AddRoom is the resolver for the addRoom field.
func (r *mutationResolver) AddRoom(ctx context.Context, input model.RoomInput) (*model.Room, error) {
	return r.plexams.AddRoom(ctx, input)
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, input model.RoomInput) (*model.Room, error) {
	return r.plexams.UpdateRoom(ctx, input)
}

// MigrateRoomsRequestWith is the resolver for the migrateRoomsRequestWith field.
func (r *mutationResolver) MigrateRoomsRequestWith(ctx context.Context) (int, error) {
	return r.plexams.MigrateRoomsRequestWith(ctx)
}

// ResetRoomsForExams is the resolver for the resetRoomsForExams field.
func (r *mutationResolver) ResetRoomsForExams(ctx context.Context) (bool, error) {
	if err := r.plexams.ResetRoomsForExams(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Room is the resolver for the room field.
func (r *plannedRoomResolver) Room(ctx context.Context, obj *model.PlannedRoom) (*model.Room, error) {
	return r.plexams.RoomByName(ctx, obj.RoomName)
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context) ([]*model.Room, error) {
	return r.plexams.Rooms(ctx)
}

// PrePlannedRooms is the resolver for the prePlannedRooms field.
func (r *queryResolver) PrePlannedRooms(ctx context.Context) ([]*model.PrePlannedRoom, error) {
	return r.plexams.PrePlannedRooms(ctx)
}

// RoomsForSlot is the resolver for the roomsForSlot field.
func (r *queryResolver) RoomsForSlot(ctx context.Context, day int, time int) (*model.RoomsForSlot, error) {
	return r.plexams.RoomsForSlot(ctx, day, time)
}

// RoomsForSlots is the resolver for the roomsForSlots field.
func (r *queryResolver) RoomsForSlots(ctx context.Context) ([]*model.RoomsForSlot, error) {
	return r.plexams.RoomsForSlots(ctx)
}

// PlannedRooms is the resolver for the plannedRooms field.
func (r *queryResolver) PlannedRooms(ctx context.Context) ([]*model.PlannedRoom, error) {
	return r.plexams.PlannedRooms(ctx)
}

// PlannedRoomNames is the resolver for the plannedRoomNames field.
func (r *queryResolver) PlannedRoomNames(ctx context.Context) ([]string, error) {
	return r.plexams.PlannedRoomNames(ctx)
}

// PlannedRoomNamesInSlot is the resolver for the plannedRoomNamesInSlot field.
func (r *queryResolver) PlannedRoomNamesInSlot(ctx context.Context, day int, time int) ([]string, error) {
	return r.plexams.PlannedRoomNamesInSlot(ctx, day, time)
}

// PlannedRoomsInSlot is the resolver for the plannedRoomsInSlot field.
func (r *queryResolver) PlannedRoomsInSlot(ctx context.Context, day int, time int) ([]*model.PlannedRoom, error) {
	return r.plexams.PlannedRoomsInSlot(ctx, day, time)
}

// PlannedRoomForNta is the resolver for the plannedRoomForNTA field.
func (r *queryResolver) PlannedRoomForStudent(ctx context.Context, ancode int, mtknr string) (*model.PlannedRoom, error) {
	return r.plexams.PlannedRoomForStudent(ctx, ancode, mtknr)
}

// BlockedRooms is the resolver for the blockedRooms field.
func (r *queryResolver) BlockedRooms(ctx context.Context) ([]*model.BlockedRoom, error) {
	return r.plexams.BlockedRooms(ctx)
}

// RoomsWithFreeSeatsForSlot is the resolver for the roomsWithFreeSeatsForSlot field.
func (r *queryResolver) RoomsWithFreeSeatsForSlot(ctx context.Context, day int, time int) ([]*model.RoomWithFreeSeats, error) {
	return r.plexams.RoomsWithFreeSeatsForSlot(ctx, day, time)
}

// UnplacedExams is the resolver for the unplacedExams field.
func (r *queryResolver) UnplacedExams(ctx context.Context) ([]*model.UnplacedExam, error) {
	return r.plexams.UnplacedExams(ctx)
}

// Rooms is the resolver for the rooms field.
func (r *roomsForSlotResolver) Rooms(ctx context.Context, obj *model.RoomsForSlot) ([]*model.Room, error) {
	return r.plexams.RoomsFromRoomNames(ctx, obj.RoomNames)
}

// AssignRoomsForExams is the resolver for the assignRoomsForExams field.
func (r *subscriptionResolver) AssignRoomsForExams(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		return r.plexams.PrepareRoomForExams(ctx, reporter)
	}), nil
}

// ImportAnnyBookings is the resolver for the importAnnyBookings field.
func (r *subscriptionResolver) ImportAnnyBookings(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		return r.plexams.FetchFromAnny(ctx, reporter)
	}), nil
}

// PlannedRoom returns generated.PlannedRoomResolver implementation.
func (r *Resolver) PlannedRoom() generated.PlannedRoomResolver { return &plannedRoomResolver{r} }

// RoomsForSlot returns generated.RoomsForSlotResolver implementation.
func (r *Resolver) RoomsForSlot() generated.RoomsForSlotResolver { return &roomsForSlotResolver{r} }

type plannedRoomResolver struct{ *Resolver }
type roomsForSlotResolver struct{ *Resolver }
