package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
)

// SetSemesterConfigInput is the resolver for the setSemesterConfigInput field.
func (r *mutationResolver) SetSemesterConfigInput(ctx context.Context, input model.SemesterConfigInputData) (*model.SaveSemesterConfigResult, error) {
	return r.plexams.SetSemesterConfigInput(ctx, &input)
}

// CreateSemester is the resolver for the createSemester field.
func (r *mutationResolver) CreateSemester(ctx context.Context, semester string, input model.SemesterConfigInputData) (*model.SaveSemesterConfigResult, error) {
	return r.plexams.CreateSemester(ctx, semester, &input)
}

// SetSemester is the resolver for the setSemester field.
func (r *mutationResolver) SetSemester(ctx context.Context, name string, semester *string) (*model.Semester, error) {
	override := ""
	if semester != nil {
		override = *semester
	}
	return r.plexams.SwitchSemester(ctx, name, override)
}

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, database string, fromSemester string) (*model.Semester, error) {
	return r.plexams.CreateWorkspace(ctx, database, fromSemester)
}

// SetSemesterReadOnly is the resolver for the setSemesterReadOnly field.
func (r *mutationResolver) SetSemesterReadOnly(ctx context.Context, readOnly bool) (*model.Semester, error) {
	return r.plexams.SetSemesterReadOnly(ctx, readOnly)
}

// AllSemesterNames is the resolver for the allSemesterNames field.
func (r *queryResolver) AllSemesterNames(ctx context.Context) ([]*model.Semester, error) {
	return r.plexams.GetAllSemesterNames(ctx)
}

// Semester is the resolver for the semester field.
func (r *queryResolver) Semester(ctx context.Context) (*model.Semester, error) {
	return r.plexams.GetSemester(ctx), nil
}

// SemesterConfig is the resolver for the SemesterConfig field.
func (r *queryResolver) SemesterConfig(ctx context.Context) (*model.SemesterConfig, error) {
	return r.plexams.GetSemesterConfig(), nil
}

// SemesterConfigInput is the resolver for the semesterConfigInput field.
func (r *queryResolver) SemesterConfigInput(ctx context.Context) (*model.SemesterConfigInput, error) {
	return r.plexams.SemesterConfigInput(ctx)
}

// NewSemesterConfigDefaults is the resolver for the newSemesterConfigDefaults field.
func (r *queryResolver) NewSemesterConfigDefaults(ctx context.Context) (*model.SemesterConfigInput, error) {
	return r.plexams.NewSemesterConfigDefaults(ctx)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
