package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// UpsertSpecialInterest is the resolver for the upsertSpecialInterest field.
func (r *mutationResolver) UpsertSpecialInterest(ctx context.Context, input model.SpecialInterestInput) (*model.SpecialInterest, error) {
	return r.plexams.UpsertSpecialInterest(ctx, &model.SpecialInterest{
		Name:     input.Name,
		Filename: input.Filename,
		Ancodes:  input.Ancodes,
	})
}

// DeleteSpecialInterest is the resolver for the deleteSpecialInterest field.
func (r *mutationResolver) DeleteSpecialInterest(ctx context.Context, name string) (bool, error) {
	return r.plexams.DeleteSpecialInterest(ctx, name)
}

// SpecialInterests is the resolver for the specialInterests field.
func (r *queryResolver) SpecialInterests(ctx context.Context) ([]*model.SpecialInterest, error) {
	return r.plexams.SpecialInterests(ctx)
}
