package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// ExamSpreadStatistics is the resolver for the examSpreadStatistics field.
func (r *queryResolver) ExamSpreadStatistics(ctx context.Context) (*model.ExamSpreadStatistics, error) {
	return r.plexams.ExamSpreadStatistics(ctx)
}
