package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
	"github.com/rs/zerolog/log"
)

// GenerateInvigilations is the resolver for the generateInvigilations field. It
// runs the automatic invigilation planning and streams its terminal-style output
// line by line to the subscribing client. The operation itself runs on a
// background context so that a started (non-dry-run) run finishes and writes even
// if the client disconnects; the subscription context only governs the streaming.
func (r *subscriptionResolver) GenerateInvigilations(ctx context.Context, dryRun bool, seed *int, iterations *int) (<-chan *model.LogLine, error) {
	ch := make(chan *model.LogLine, 256)

	var seedVal int64
	if seed != nil {
		seedVal = int64(*seed)
	}
	var iterVal int
	if iterations != nil {
		iterVal = *iterations
	}
	opts := r.plexams.OptimizerOptionsFromConfig(seedVal, iterVal)
	reporter := newStreamReporter(ctx, ch)

	go func() {
		defer close(ch)
		report, err := r.plexams.GenerateInvigilations(context.Background(), dryRun, opts, reporter)
		if err != nil {
			log.Error().Err(err).Msg("generate invigilations failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		if report != nil {
			reporter.send(&model.LogLine{Level: model.LogLevelResult, Text: "report", Report: report})
		}
		reporter.emit(model.LogLevelDone, "done")
	}()

	return ch, nil
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
