package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// UpsertStudyProgram is the resolver for the upsertStudyProgram field.
func (r *mutationResolver) UpsertStudyProgram(ctx context.Context, input model.StudyProgramInput) (*model.StudyProgram, error) {
	program := &model.StudyProgram{
		Shortname: input.Shortname,
		Name:      input.Name,
		Degree:    input.Degree,
		Category:  input.Category,
		Active:    input.Active,
		Retired:   input.Retired,
	}
	return r.plexams.UpsertStudyProgram(ctx, program)
}

// DeleteStudyProgram is the resolver for the deleteStudyProgram field.
func (r *mutationResolver) DeleteStudyProgram(ctx context.Context, shortname string) (bool, error) {
	return r.plexams.DeleteStudyProgram(ctx, shortname)
}

// SeedStudyProgramsFromConfig is the resolver for the seedStudyProgramsFromConfig field.
func (r *mutationResolver) SeedStudyProgramsFromConfig(ctx context.Context) (int, error) {
	return r.plexams.SeedStudyProgramsFromConfig(ctx)
}

// StudyPrograms is the resolver for the studyPrograms field.
func (r *queryResolver) StudyPrograms(ctx context.Context) ([]*model.StudyProgram, error) {
	return r.plexams.StudyPrograms(ctx)
}
