package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// GenerateStudentRegs is the resolver for the generateStudentRegs field.
func (r *mutationResolver) GenerateStudentRegs(ctx context.Context) (*model.GenerateStudentRegsResult, error) {
	return r.plexams.GenerateStudentRegs(ctx)
}

// StudentRegsState is the resolver for the studentRegsState field.
func (r *queryResolver) StudentRegsState(ctx context.Context) (*model.StudentRegsState, error) {
	return r.plexams.StudentRegsState(ctx)
}
