package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/obcode/plexams.go/graph/generated"
	"github.com/obcode/plexams.go/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.TodoInput) (*model.Todo, error) {
	return r.plexams.CreateTodo(ctx, input)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id int, input model.TodoInput) (*model.Todo, error) {
	return r.plexams.UpdateTodo(ctx, id, input)
}

// SetTodoDone is the resolver for the setTodoDone field.
func (r *mutationResolver) SetTodoDone(ctx context.Context, id int, done bool) (*model.Todo, error) {
	return r.plexams.SetTodoDone(ctx, id, done)
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id int) (bool, error) {
	return r.plexams.DeleteTodo(ctx, id)
}

// AddTodoComment is the resolver for the addTodoComment field.
func (r *mutationResolver) AddTodoComment(ctx context.Context, todoID int, body string) (*model.TodoComment, error) {
	return r.plexams.AddTodoComment(ctx, todoID, body)
}

// UpdateTodoComment is the resolver for the updateTodoComment field.
func (r *mutationResolver) UpdateTodoComment(ctx context.Context, id int, body string) (*model.TodoComment, error) {
	return r.plexams.UpdateTodoComment(ctx, id, body)
}

// AddTodoLink is the resolver for the addTodoLink field.
func (r *mutationResolver) AddTodoLink(ctx context.Context, todoID int, link model.TodoLinkInput) (*model.Todo, error) {
	return r.plexams.AddTodoLink(ctx, todoID, link)
}

// RemoveTodoLink is the resolver for the removeTodoLink field.
func (r *mutationResolver) RemoveTodoLink(ctx context.Context, todoID int, link model.TodoLinkInput) (*model.Todo, error) {
	return r.plexams.RemoveTodoLink(ctx, todoID, link)
}

// CarryOverTodos is the resolver for the carryOverTodos field.
func (r *mutationResolver) CarryOverTodos(ctx context.Context, fromSemester string) (int, error) {
	return r.plexams.CarryOverTodos(ctx, fromSemester)
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, filter *model.TodoFilter) ([]*model.Todo, error) {
	return r.plexams.Todos(ctx, filter)
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id int) (*model.Todo, error) {
	return r.plexams.Todo(ctx, id)
}

// TodoLabels is the resolver for the todoLabels field.
func (r *queryResolver) TodoLabels(ctx context.Context) ([]string, error) {
	return r.plexams.TodoLabels(ctx)
}

// TodoLinkSuggestions is the resolver for the todoLinkSuggestions field.
func (r *queryResolver) TodoLinkSuggestions(ctx context.Context, kind model.TodoLinkKind, query string) ([]*model.TodoLink, error) {
	return r.plexams.TodoLinkSuggestions(ctx, kind, query)
}

// OpenTodoCountsByLink is the resolver for the openTodoCountsByLink field.
func (r *queryResolver) OpenTodoCountsByLink(ctx context.Context, kind model.TodoLinkKind) ([]*model.TodoLinkCount, error) {
	return r.plexams.OpenTodoCountsByLink(ctx, kind)
}

// TodoCarryOverCandidates is the resolver for the todoCarryOverCandidates field.
func (r *queryResolver) TodoCarryOverCandidates(ctx context.Context, fromSemester string) (int, error) {
	return r.plexams.TodoCarryOverCandidates(ctx, fromSemester)
}

// Comments is the resolver for the comments field.
func (r *todoResolver) Comments(ctx context.Context, obj *model.Todo) ([]*model.TodoComment, error) {
	return r.plexams.TodoComments(ctx, obj.ID)
}

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
