package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/obcode/plexams.go/plexams"
	"github.com/rs/zerolog/log"
)

// runValidation runs a single validator and streams its output. It registers the
// validation with the write-guard (blocking mutations while it runs), streams the
// human-readable lines, then emits the structured ValidationReport on the final
// RESULT line followed by a DONE line. The validator runs on a background context
// so it finishes cleanly even if the client disconnects.
func (r *subscriptionResolver) runValidation(
	ctx context.Context,
	fn func(reporter plexams.Reporter) (*model.ValidationReport, error),
) <-chan *model.LogLine {
	ch := make(chan *model.LogLine, 256)
	reporter := newStreamReporter(ctx, ch)
	r.plexams.BeginValidation()

	go func() {
		defer close(ch)
		defer r.plexams.EndValidation()
		report, err := fn(reporter)
		if err != nil {
			log.Error().Err(err).Msg("validation failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		if report != nil {
			reporter.send(&model.LogLine{Level: model.LogLevelResult, Text: "report", Validation: report})
		}
		reporter.emit(model.LogLevelDone, "done")
	}()

	return ch
}

// ValidateInvigilatorRequirements is the resolver for the validateInvigilatorRequirements field.
func (r *subscriptionResolver) ValidateInvigilatorRequirements(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runValidation(ctx, r.plexams.ValidateInvigilatorRequirements), nil
}

// ValidateInvigilationDuplicates is the resolver for the validateInvigilationDuplicates field.
func (r *subscriptionResolver) ValidateInvigilationDuplicates(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runValidation(ctx, r.plexams.ValidateInvigilationDups), nil
}

// ValidateInvigilatorSlots is the resolver for the validateInvigilatorSlots field.
func (r *subscriptionResolver) ValidateInvigilatorSlots(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runValidation(ctx, r.plexams.ValidateInvigilatorSlots), nil
}

// ValidateInvigilationsTimeDistance is the resolver for the validateInvigilationsTimeDistance field.
func (r *subscriptionResolver) ValidateInvigilationsTimeDistance(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runValidation(ctx, r.plexams.ValidateInvigilationsTimeDistance), nil
}

// ValidateInvigilationConstraints is the resolver for the validateInvigilationConstraints field.
func (r *subscriptionResolver) ValidateInvigilationConstraints(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runValidation(ctx, r.plexams.ValidateInvigilationConstraints), nil
}
