package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// AddZPAExamToPlan is the resolver for the addZPAExamToPlan field.
func (r *mutationResolver) AddZpaExamToPlan(ctx context.Context, ancode int) (bool, error) {
	return r.plexams.AddZpaExamToPlan(ctx, ancode)
}

// RmZPAExamFromPlan is the resolver for the rmZPAExamFromPlan field.
func (r *mutationResolver) RmZpaExamFromPlan(ctx context.Context, ancode int) (bool, error) {
	return r.plexams.RmZpaExamFromPlan(ctx, ancode)
}

// Teacher is the resolver for the teacher field.
func (r *queryResolver) Teacher(ctx context.Context, id int) (*model.Teacher, error) {
	return r.plexams.GetTeacher(ctx, id)
}

// Teachers is the resolver for the teachers field.
func (r *queryResolver) Teachers(ctx context.Context, fromZpa *bool) ([]*model.Teacher, error) {
	return r.plexams.GetTeachers(ctx, fromZpa)
}

// Invigilators is the resolver for the invigilators field.
func (r *queryResolver) Invigilators(ctx context.Context) ([]*model.ZPAInvigilator, error) {
	return r.plexams.GetInvigilators(ctx)
}

// ZpaExams is the resolver for the zpaExams field.
func (r *queryResolver) ZpaExams(ctx context.Context, fromZpa *bool) ([]*model.ZPAExam, error) {
	return r.plexams.GetZPAExams(ctx, fromZpa)
}

// SyncLog is the resolver for the syncLog field.
func (r *queryResolver) SyncLog(ctx context.Context, limit *int) ([]*model.SyncLogEntry, error) {
	l := 0
	if limit != nil {
		l = *limit
	}
	return r.plexams.SyncLog(ctx, l)
}
