package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/obcode/plexams.go/plexams"
	"github.com/rs/zerolog/log"
)

// UploadExamsToZpa is the resolver for the uploadExamsToZPA field.
func (r *subscriptionResolver) UploadExamsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, false, false, !dryRun, reporter)
		return err
	}), nil
}

// UploadExamsWithRoomsToZpa is the resolver for the uploadExamsWithRoomsToZPA field.
func (r *subscriptionResolver) UploadExamsWithRoomsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, true, false, !dryRun, reporter)
		return err
	}), nil
}

// UploadExamsWithInvigilatorsToZpa is the resolver for the uploadExamsWithInvigilatorsToZPA field.
func (r *subscriptionResolver) UploadExamsWithInvigilatorsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, true, true, !dryRun, reporter)
		return err
	}), nil
}

// UploadStudentRegsToZpa is the resolver for the uploadStudentRegsToZPA field.
func (r *subscriptionResolver) UploadStudentRegsToZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		// Empty path: skip writing a local JSON copy (a CLI-only convenience).
		_, _, err := r.plexams.PostStudentRegsToZPA(ctx, "", reporter)
		return err
	}), nil
}

// ImportTeachersFromZpa is the resolver for the importTeachersFromZPA field.
func (r *subscriptionResolver) ImportTeachersFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.ImportTeachersFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportExamsFromZpa is the resolver for the importExamsFromZPA field.
func (r *subscriptionResolver) ImportExamsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.ImportExamsFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportInvigilatorRequirementsFromZpa is the resolver for the importInvigilatorRequirementsFromZPA field.
func (r *subscriptionResolver) ImportInvigilatorRequirementsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, err := r.plexams.ImportInvigilatorRequirementsFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportStudentsFromZpa is the resolver for the importStudentsFromZPA field.
func (r *subscriptionResolver) ImportStudentsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(ctx context.Context, reporter plexams.Reporter) error {
		_, _, err := r.plexams.GetStudentsFromZPA(ctx, reporter)
		return err
	}), nil
}

// TriggerScheduledSync is the resolver for the triggerScheduledSync field. It runs the
// same job as the nightly scheduler on demand and streams its progress. Unlike the other
// transfer subscriptions it does not use runExclusiveOp: RunScheduledSync manages the
// exclusive-op guard itself (and skips cleanly when a transfer is already running). The
// op runs on a detached context so it completes even if the client leaves the page.
func (r *subscriptionResolver) TriggerScheduledSync(ctx context.Context) (<-chan *model.LogLine, error) {
	ch := make(chan *model.LogLine, 256)
	reporter := newStreamReporter(ctx, ch)
	opCtx := context.WithoutCancel(ctx)
	cfg := plexams.ScheduledSyncConfigFromViper()
	go func() {
		defer close(ch)
		if _, err := r.plexams.RunScheduledSync(opCtx, cfg, reporter); err != nil {
			log.Error().Err(err).Msg("triggered auto-sync failed")
			reporter.emit(model.LogLevelError, "error: "+err.Error())
		}
		reporter.emit(model.LogLevelDone, "done")
	}()
	return ch, nil
}
