package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
)

// UploadExamsToZpa is the resolver for the uploadExamsToZPA field.
func (r *mutationResolver) UploadExamsToZpa(ctx context.Context, dryRun bool) (*model.ZPAUploadResult, error) {
	return r.uploadResult(ctx, false, false, dryRun)
}

// UploadExamsWithRoomsToZpa is the resolver for the uploadExamsWithRoomsToZPA field.
func (r *mutationResolver) UploadExamsWithRoomsToZpa(ctx context.Context, dryRun bool) (*model.ZPAUploadResult, error) {
	return r.uploadResult(ctx, true, false, dryRun)
}

// UploadExamsWithInvigilatorsToZpa is the resolver for the uploadExamsWithInvigilatorsToZPA field.
func (r *mutationResolver) UploadExamsWithInvigilatorsToZpa(ctx context.Context, dryRun bool) (*model.ZPAUploadResult, error) {
	return r.uploadResult(ctx, true, true, dryRun)
}

// UploadStudentRegsToZpa is the resolver for the uploadStudentRegsToZPA field.
func (r *mutationResolver) UploadStudentRegsToZpa(ctx context.Context) (*model.ZPAStudentRegsResult, error) {
	// Empty path: skip writing a local JSON copy (that is a CLI-only convenience).
	posted, withErrors, err := r.plexams.PostStudentRegsToZPA(ctx, "")
	if err != nil {
		return nil, err
	}
	return &model.ZPAStudentRegsResult{
		Posted: len(posted),
		Errors: len(withErrors),
	}, nil
}

// ImportTeachersFromZpa is the resolver for the importTeachersFromZPA field.
func (r *mutationResolver) ImportTeachersFromZpa(ctx context.Context) (int, error) {
	fromZPA := true
	teachers, err := r.plexams.GetTeachers(ctx, &fromZPA)
	if err != nil {
		return 0, err
	}
	return len(teachers), nil
}

// ImportExamsFromZpa is the resolver for the importExamsFromZPA field.
func (r *mutationResolver) ImportExamsFromZpa(ctx context.Context) (int, error) {
	fromZPA := true
	exams, err := r.plexams.GetZPAExams(ctx, &fromZPA)
	if err != nil {
		return 0, err
	}
	return len(exams), nil
}

// ImportInvigilatorRequirementsFromZpa is the resolver for the importInvigilatorRequirementsFromZPA field.
func (r *mutationResolver) ImportInvigilatorRequirementsFromZpa(ctx context.Context) (int, error) {
	reqs, err := r.plexams.GetSupervisorRequirements(ctx)
	if err != nil {
		return 0, err
	}
	return len(reqs), nil
}

// ImportStudentsFromZpa is the resolver for the importStudentsFromZPA field.
func (r *mutationResolver) ImportStudentsFromZpa(ctx context.Context) (*model.ZPAStudentsImportResult, error) {
	found, notFound, err := r.plexams.GetStudentsFromZPA(ctx)
	if err != nil {
		return nil, err
	}
	return &model.ZPAStudentsImportResult{
		Found:    found,
		NotFound: notFound,
	}, nil
}
