package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/obcode/plexams.go/graph/model"
	"github.com/obcode/plexams.go/plexams"
)

// UploadExamsToZpa is the resolver for the uploadExamsToZPA field.
func (r *subscriptionResolver) UploadExamsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, false, false, !dryRun, reporter)
		return err
	}), nil
}

// UploadExamsWithRoomsToZpa is the resolver for the uploadExamsWithRoomsToZPA field.
func (r *subscriptionResolver) UploadExamsWithRoomsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, true, false, !dryRun, reporter)
		return err
	}), nil
}

// UploadExamsWithInvigilatorsToZpa is the resolver for the uploadExamsWithInvigilatorsToZPA field.
func (r *subscriptionResolver) UploadExamsWithInvigilatorsToZpa(ctx context.Context, dryRun bool) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.UploadPlan(ctx, true, true, !dryRun, reporter)
		return err
	}), nil
}

// UploadStudentRegsToZpa is the resolver for the uploadStudentRegsToZPA field.
func (r *subscriptionResolver) UploadStudentRegsToZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		// Empty path: skip writing a local JSON copy (a CLI-only convenience).
		_, _, err := r.plexams.PostStudentRegsToZPA(ctx, "", reporter)
		return err
	}), nil
}

// ImportTeachersFromZpa is the resolver for the importTeachersFromZPA field.
func (r *subscriptionResolver) ImportTeachersFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.ImportTeachersFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportExamsFromZpa is the resolver for the importExamsFromZPA field.
func (r *subscriptionResolver) ImportExamsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.ImportExamsFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportInvigilatorRequirementsFromZpa is the resolver for the importInvigilatorRequirementsFromZPA field.
func (r *subscriptionResolver) ImportInvigilatorRequirementsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, err := r.plexams.ImportInvigilatorRequirementsFromZPA(ctx, reporter)
		return err
	}), nil
}

// ImportStudentsFromZpa is the resolver for the importStudentsFromZPA field.
func (r *subscriptionResolver) ImportStudentsFromZpa(ctx context.Context) (<-chan *model.LogLine, error) {
	return r.runExclusiveOp(ctx, func(reporter plexams.Reporter) error {
		_, _, err := r.plexams.GetStudentsFromZPA(ctx, reporter)
		return err
	}), nil
}
