// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_semester.sql

package sqlc

import (
	"context"
)

const getActiveSemester = `-- name: GetActiveSemester :one
select a.semester_id, s.semester
from active_semester a
join semester s on s.id = a.semester_id
where a.id = 1
`

type GetActiveSemesterRow struct {
	SemesterID string
	Semester   string
}

// The stored answer is only the workspace id; the logical semester comes from the
// registry rather than being duplicated here. Under MongoDB both were written
// into the same document and could disagree after a workspace was renamed.
func (q *Queries) GetActiveSemester(ctx context.Context) (GetActiveSemesterRow, error) {
	row := q.db.QueryRow(ctx, getActiveSemester)
	var i GetActiveSemesterRow
	err := row.Scan(&i.SemesterID, &i.Semester)
	return i, err
}

const saveActiveSemester = `-- name: SaveActiveSemester :exec
insert into active_semester (id, semester_id)
values (1, $1)
on conflict (id) do update set semester_id = excluded.semester_id
`

func (q *Queries) SaveActiveSemester(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, saveActiveSemester, semesterID)
	return err
}
