// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_semester.sql

package sqlc

import (
	"context"
)

const getActiveSemester = `-- name: GetActiveSemester :one
select semester_id from active_semester where id = 1
`

// Only the semester is stored. Under MongoDB the document carried the database
// name AND a logical semester next to it, and the two could disagree.
func (q *Queries) GetActiveSemester(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getActiveSemester)
	var semester_id string
	err := row.Scan(&semester_id)
	return semester_id, err
}

const saveActiveSemester = `-- name: SaveActiveSemester :exec
insert into active_semester (id, semester_id)
values (1, $1)
on conflict (id) do update set semester_id = excluded.semester_id
`

func (q *Queries) SaveActiveSemester(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, saveActiveSemester, semesterID)
	return err
}
