// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anny_bookings.sql

package sqlc

import (
	"context"
	"time"
)

const deleteAnnyBookings = `-- name: DeleteAnnyBookings :exec
delete from anny_booking where semester_id = $1
`

func (q *Queries) DeleteAnnyBookings(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteAnnyBookings, semesterID)
	return err
}

const insertAnnyBooking = `-- name: InsertAnnyBooking :exec
insert into anny_booking (
    semester_id, number, start_date, end_date, blocker_start_date,
    blocker_end_date, charged_duration, description, note, room, status,
    status_reason, is_blocker, can_edit, is_editable, manually_created,
    has_custom_description, self_url, personalization_name,
    booking_group_identifier, resource_id, created_at, updated_at, canceled_at,
    cancelable_until
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25
)
on conflict (semester_id, number) do update set
    start_date               = excluded.start_date,
    end_date                 = excluded.end_date,
    blocker_start_date       = excluded.blocker_start_date,
    blocker_end_date         = excluded.blocker_end_date,
    charged_duration         = excluded.charged_duration,
    description              = excluded.description,
    note                     = excluded.note,
    room                     = excluded.room,
    status                   = excluded.status,
    status_reason            = excluded.status_reason,
    is_blocker               = excluded.is_blocker,
    can_edit                 = excluded.can_edit,
    is_editable              = excluded.is_editable,
    manually_created         = excluded.manually_created,
    has_custom_description   = excluded.has_custom_description,
    self_url                 = excluded.self_url,
    personalization_name     = excluded.personalization_name,
    booking_group_identifier = excluded.booking_group_identifier,
    resource_id              = excluded.resource_id,
    created_at               = excluded.created_at,
    updated_at               = excluded.updated_at,
    canceled_at              = excluded.canceled_at,
    cancelable_until         = excluded.cancelable_until
`

type InsertAnnyBookingParams struct {
	SemesterID             string
	Number                 string
	StartDate              time.Time
	EndDate                time.Time
	BlockerStartDate       time.Time
	BlockerEndDate         time.Time
	ChargedDuration        int
	Description            string
	Note                   string
	Room                   string
	Status                 string
	StatusReason           []byte
	IsBlocker              bool
	CanEdit                bool
	IsEditable             bool
	ManuallyCreated        bool
	HasCustomDescription   bool
	SelfUrl                string
	PersonalizationName    string
	BookingGroupIdentifier string
	ResourceID             string
	CreatedAt              *time.Time
	UpdatedAt              *time.Time
	CanceledAt             *time.Time
	CancelableUntil        *time.Time
}

func (q *Queries) InsertAnnyBooking(ctx context.Context, arg InsertAnnyBookingParams) error {
	_, err := q.db.Exec(ctx, insertAnnyBooking,
		arg.SemesterID,
		arg.Number,
		arg.StartDate,
		arg.EndDate,
		arg.BlockerStartDate,
		arg.BlockerEndDate,
		arg.ChargedDuration,
		arg.Description,
		arg.Note,
		arg.Room,
		arg.Status,
		arg.StatusReason,
		arg.IsBlocker,
		arg.CanEdit,
		arg.IsEditable,
		arg.ManuallyCreated,
		arg.HasCustomDescription,
		arg.SelfUrl,
		arg.PersonalizationName,
		arg.BookingGroupIdentifier,
		arg.ResourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CanceledAt,
		arg.CancelableUntil,
	)
	return err
}

const listAnnyBookings = `-- name: ListAnnyBookings :many

select semester_id, number, start_date, end_date, blocker_start_date, blocker_end_date, charged_duration, description, note, room, status, status_reason, is_blocker, can_edit, is_editable, manually_created, has_custom_description, self_url, personalization_name, booking_group_identifier, resource_id, created_at, updated_at, canceled_at, cancelable_until from anny_booking
where semester_id = $1
order by start_date, number collate "C"
`

// Room bookings fetched from Anny. Source data: re-fetchable at any time, so
// replacing them wholesale is safe -- nothing references a booking.
func (q *Queries) ListAnnyBookings(ctx context.Context, semesterID string) ([]AnnyBooking, error) {
	rows, err := q.db.Query(ctx, listAnnyBookings, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnyBooking{}
	for rows.Next() {
		var i AnnyBooking
		if err := rows.Scan(
			&i.SemesterID,
			&i.Number,
			&i.StartDate,
			&i.EndDate,
			&i.BlockerStartDate,
			&i.BlockerEndDate,
			&i.ChargedDuration,
			&i.Description,
			&i.Note,
			&i.Room,
			&i.Status,
			&i.StatusReason,
			&i.IsBlocker,
			&i.CanEdit,
			&i.IsEditable,
			&i.ManuallyCreated,
			&i.HasCustomDescription,
			&i.SelfUrl,
			&i.PersonalizationName,
			&i.BookingGroupIdentifier,
			&i.ResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
			&i.CancelableUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnyBookingsForRoom = `-- name: ListAnnyBookingsForRoom :many
select semester_id, number, start_date, end_date, blocker_start_date, blocker_end_date, charged_duration, description, note, room, status, status_reason, is_blocker, can_edit, is_editable, manually_created, has_custom_description, self_url, personalization_name, booking_group_identifier, resource_id, created_at, updated_at, canceled_at, cancelable_until from anny_booking
where semester_id = $1 and room = $2
order by start_date, number collate "C"
`

type ListAnnyBookingsForRoomParams struct {
	SemesterID string
	Room       string
}

// The room filter is applied in SQL rather than after the fact. The caller
// normalises the name first (upper case, spaces removed), as it always did.
func (q *Queries) ListAnnyBookingsForRoom(ctx context.Context, arg ListAnnyBookingsForRoomParams) ([]AnnyBooking, error) {
	rows, err := q.db.Query(ctx, listAnnyBookingsForRoom, arg.SemesterID, arg.Room)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnnyBooking{}
	for rows.Next() {
		var i AnnyBooking
		if err := rows.Scan(
			&i.SemesterID,
			&i.Number,
			&i.StartDate,
			&i.EndDate,
			&i.BlockerStartDate,
			&i.BlockerEndDate,
			&i.ChargedDuration,
			&i.Description,
			&i.Note,
			&i.Room,
			&i.Status,
			&i.StatusReason,
			&i.IsBlocker,
			&i.CanEdit,
			&i.IsEditable,
			&i.ManuallyCreated,
			&i.HasCustomDescription,
			&i.SelfUrl,
			&i.PersonalizationName,
			&i.BookingGroupIdentifier,
			&i.ResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanceledAt,
			&i.CancelableUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
