// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assembled_exams.sql

package sqlc

import (
	"context"
)

const countAssembledExams = `-- name: CountAssembledExams :one
select count(*) from assembled_exam where semester_id = $1
`

func (q *Queries) CountAssembledExams(ctx context.Context, semesterID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAssembledExams, semesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAssembledExams = `-- name: DeleteAssembledExams :execrows
delete from assembled_exam where semester_id = $1
`

func (q *Queries) DeleteAssembledExams(ctx context.Context, semesterID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssembledExams, semesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAssembledExamsState = `-- name: DeleteAssembledExamsState :exec
delete from assembled_exams_state where semester_id = $1
`

func (q *Queries) DeleteAssembledExamsState(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteAssembledExamsState, semesterID)
	return err
}

const getAssembledExam = `-- name: GetAssembledExam :one
select exam, format_version from assembled_exam
where semester_id = $1 and ancode = $2
`

type GetAssembledExamParams struct {
	SemesterID string
	Ancode     int
}

type GetAssembledExamRow struct {
	Exam          []byte
	FormatVersion int
}

func (q *Queries) GetAssembledExam(ctx context.Context, arg GetAssembledExamParams) (GetAssembledExamRow, error) {
	row := q.db.QueryRow(ctx, getAssembledExam, arg.SemesterID, arg.Ancode)
	var i GetAssembledExamRow
	err := row.Scan(&i.Exam, &i.FormatVersion)
	return i, err
}

const listAssembledExams = `-- name: ListAssembledExams :many

select exam, format_version from assembled_exam
where semester_id = $1
order by ancode
`

type ListAssembledExamsRow struct {
	Exam          []byte
	FormatVersion int
}

// The assembled-exam cache. Pulled forward from phase 3e because the plan reads
// it: ExamsAt, AncodesInPlan and ExamerInPlan are all built on top of it.
//
// jsonb, deliberately: the document is the denormalised join of tables that are
// already relational here. Normalising the copy would create a second source of
// truth for data whose first one is one query away.
func (q *Queries) ListAssembledExams(ctx context.Context, semesterID string) ([]ListAssembledExamsRow, error) {
	rows, err := q.db.Query(ctx, listAssembledExams, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssembledExamsRow{}
	for rows.Next() {
		var i ListAssembledExamsRow
		if err := rows.Scan(&i.Exam, &i.FormatVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssembledExamsForExamer = `-- name: ListAssembledExamsForExamer :many
select exam, format_version from assembled_exam
where semester_id = $1
  and (exam -> 'zpaExam' ->> 'mainExamerID')::int = $2::int
order by ancode
`

type ListAssembledExamsForExamerParams struct {
	SemesterID string
	ExamerID   int
}

type ListAssembledExamsForExamerRow struct {
	Exam          []byte
	FormatVersion int
}

// The examer lives inside the document. Mongo indexed nothing here either and
// scanned the collection; at ~320 exams both are a scan of the same size.
// The key is `zpaExam`/`mainExamerID` -- the json tags, camelCase -- and no
// longer the lowercased Go field names bson produced.
//
// @examer_id and not $2: with a cast on the left-hand side sqlc infers the
// parameter's type from the expression and would call it `Exam []byte`.
func (q *Queries) ListAssembledExamsForExamer(ctx context.Context, arg ListAssembledExamsForExamerParams) ([]ListAssembledExamsForExamerRow, error) {
	rows, err := q.db.Query(ctx, listAssembledExamsForExamer, arg.SemesterID, arg.ExamerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssembledExamsForExamerRow{}
	for rows.Next() {
		var i ListAssembledExamsForExamerRow
		if err := rows.Scan(&i.Exam, &i.FormatVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssembledExam = `-- name: UpsertAssembledExam :exec
insert into assembled_exam (semester_id, ancode, exam, format_version)
values ($1, $2, $3, $4)
on conflict (semester_id, ancode) do update set
    exam           = excluded.exam,
    format_version = excluded.format_version
`

type UpsertAssembledExamParams struct {
	SemesterID    string
	Ancode        int
	Exam          []byte
	FormatVersion int
}

func (q *Queries) UpsertAssembledExam(ctx context.Context, arg UpsertAssembledExamParams) error {
	_, err := q.db.Exec(ctx, upsertAssembledExam,
		arg.SemesterID,
		arg.Ancode,
		arg.Exam,
		arg.FormatVersion,
	)
	return err
}
