// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_templates.sql

package sqlc

import (
	"context"
)

const deleteEmailTemplate = `-- name: DeleteEmailTemplate :execrows
delete from email_template where name = $1
`

func (q *Queries) DeleteEmailTemplate(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailTemplate, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailTemplate = `-- name: GetEmailTemplate :one
select name, markdown from email_template where name = $1
`

func (q *Queries) GetEmailTemplate(ctx context.Context, name string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplate, name)
	var i EmailTemplate
	err := row.Scan(&i.Name, &i.Markdown)
	return i, err
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
select name, markdown from email_template order by name collate "C"
`

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailTemplate{}
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(&i.Name, &i.Markdown); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailTemplate = `-- name: SetEmailTemplate :exec
insert into email_template (name, markdown)
values ($1, $2)
on conflict (name) do update set markdown = excluded.markdown
`

type SetEmailTemplateParams struct {
	Name     string
	Markdown string
}

func (q *Queries) SetEmailTemplate(ctx context.Context, arg SetEmailTemplateParams) error {
	_, err := q.db.Exec(ctx, setEmailTemplate, arg.Name, arg.Markdown)
	return err
}
