// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exam_conflict.sql

package sqlc

import (
	"context"
)

const deleteCanShareSlot = `-- name: DeleteCanShareSlot :execrows
delete from exam_can_share_slot
where semester_id = $1
  and ancode = least($2::int, $3::int)
  and other_ancode = greatest($2::int, $3::int)
`

type DeleteCanShareSlotParams struct {
	SemesterID string
	Column2    int
	Column3    int
}

func (q *Queries) DeleteCanShareSlot(ctx context.Context, arg DeleteCanShareSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCanShareSlot, arg.SemesterID, arg.Column2, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConflictDecision = `-- name: DeleteConflictDecision :execrows
delete from exam_conflict_rating
where semester_id = $1
  and ancode = least($2::int, $3::int)
  and other_ancode = greatest($2::int, $3::int)
  and mtknr = $4
`

type DeleteConflictDecisionParams struct {
	SemesterID string
	Column2    int
	Column3    int
	Mtknr      string
}

func (q *Queries) DeleteConflictDecision(ctx context.Context, arg DeleteConflictDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConflictDecision,
		arg.SemesterID,
		arg.Column2,
		arg.Column3,
		arg.Mtknr,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCanShareSlotPairs = `-- name: ListCanShareSlotPairs :many
select ancode, other_ancode from exam_can_share_slot
where semester_id = $1
order by ancode, other_ancode
`

type ListCanShareSlotPairsRow struct {
	Ancode      int
	OtherAncode int
}

func (q *Queries) ListCanShareSlotPairs(ctx context.Context, semesterID string) ([]ListCanShareSlotPairsRow, error) {
	rows, err := q.db.Query(ctx, listCanShareSlotPairs, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCanShareSlotPairsRow{}
	for rows.Next() {
		var i ListCanShareSlotPairsRow
		if err := rows.Scan(&i.Ancode, &i.OtherAncode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictDecisions = `-- name: ListConflictDecisions :many

select ancode, other_ancode, mtknr, decision from exam_conflict_rating
where semester_id = $1
order by ancode, other_ancode, mtknr
`

type ListConflictDecisionsRow struct {
	Ancode      int
	OtherAncode int
	Mtknr       string
	Decision    string
}

// The two hand-entered judgements about a conflict between two exams: "these may
// share a slot" and, per student, "this one does not count" / "this one counts".
//
// Both are pairs of ancodes, and both are stored canonically (ancode <
// other_ancode). plexams normalises with conflictcalc.NormPair before it calls in
// (plexams/exam_conflict.go:75,93) -- but the CSV import does not
// (csv_export.go:869,908), so the ordering is done here as well. Under MongoDB a
// hand-edited CSV row with the ancodes the other way round created a second,
// unreachable document that the readers then counted twice.
func (q *Queries) ListConflictDecisions(ctx context.Context, semesterID string) ([]ListConflictDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listConflictDecisions, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConflictDecisionsRow{}
	for rows.Next() {
		var i ListConflictDecisionsRow
		if err := rows.Scan(
			&i.Ancode,
			&i.OtherAncode,
			&i.Mtknr,
			&i.Decision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCanShareSlot = `-- name: UpsertCanShareSlot :exec
insert into exam_can_share_slot (semester_id, ancode, other_ancode)
values ($1, least($2::int, $3::int), greatest($2::int, $3::int))
on conflict do nothing
`

type UpsertCanShareSlotParams struct {
	SemesterID string
	Column2    int
	Column3    int
}

func (q *Queries) UpsertCanShareSlot(ctx context.Context, arg UpsertCanShareSlotParams) error {
	_, err := q.db.Exec(ctx, upsertCanShareSlot, arg.SemesterID, arg.Column2, arg.Column3)
	return err
}

const upsertConflictDecision = `-- name: UpsertConflictDecision :exec
insert into exam_conflict_rating (semester_id, ancode, other_ancode, mtknr, decision)
values ($1, least($2::int, $3::int), greatest($2::int, $3::int), $4, $5)
on conflict (semester_id, ancode, other_ancode, mtknr) do update set
    decision = excluded.decision
`

type UpsertConflictDecisionParams struct {
	SemesterID string
	Column2    int
	Column3    int
	Mtknr      string
	Decision   string
}

func (q *Queries) UpsertConflictDecision(ctx context.Context, arg UpsertConflictDecisionParams) error {
	_, err := q.db.Exec(ctx, upsertConflictDecision,
		arg.SemesterID,
		arg.Column2,
		arg.Column3,
		arg.Mtknr,
		arg.Decision,
	)
	return err
}
