// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package sqlc

import (
	"context"
	"time"
)

const deleteExamsToPlan = `-- name: DeleteExamsToPlan :exec
delete from exam_to_plan where semester_id = $1
`

func (q *Queries) DeleteExamsToPlan(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteExamsToPlan, semesterID)
	return err
}

const deleteZPAPrimussAncodesForExam = `-- name: DeleteZPAPrimussAncodesForExam :exec
delete from exam_primuss_ancode
where semester_id = $1 and ancode = $2 and source = 'zpa'
`

type DeleteZPAPrimussAncodesForExamParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) DeleteZPAPrimussAncodesForExam(ctx context.Context, arg DeleteZPAPrimussAncodesForExamParams) error {
	_, err := q.db.Exec(ctx, deleteZPAPrimussAncodesForExam, arg.SemesterID, arg.Ancode)
	return err
}

const getExam = `-- name: GetExam :one
select semester_id, ancode, source, zpa_id, module, main_examer, main_examer_id, exam_type, exam_type_full, zpa_date, zpa_starttime, duration_min, is_repeater_exam, groups, faculty, withdrawn_at from exam
where semester_id = $1 and ancode = $2 and withdrawn_at is null
`

type GetExamParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) GetExam(ctx context.Context, arg GetExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, getExam, arg.SemesterID, arg.Ancode)
	var i Exam
	err := row.Scan(
		&i.SemesterID,
		&i.Ancode,
		&i.Source,
		&i.ZpaID,
		&i.Module,
		&i.MainExamer,
		&i.MainExamerID,
		&i.ExamType,
		&i.ExamTypeFull,
		&i.ZpaDate,
		&i.ZpaStarttime,
		&i.DurationMin,
		&i.IsRepeaterExam,
		&i.Groups,
		&i.Faculty,
		&i.WithdrawnAt,
	)
	return i, err
}

const insertZPAPrimussAncode = `-- name: InsertZPAPrimussAncode :exec
insert into exam_primuss_ancode (semester_id, ancode, program, primuss_ancode, source)
values ($1, $2, $3, $4, 'zpa')
on conflict (semester_id, ancode, program, primuss_ancode) do nothing
`

type InsertZPAPrimussAncodeParams struct {
	SemesterID    string
	Ancode        int
	Program       string
	PrimussAncode int
}

func (q *Queries) InsertZPAPrimussAncode(ctx context.Context, arg InsertZPAPrimussAncodeParams) error {
	_, err := q.db.Exec(ctx, insertZPAPrimussAncode,
		arg.SemesterID,
		arg.Ancode,
		arg.Program,
		arg.PrimussAncode,
	)
	return err
}

const listExamsBySource = `-- name: ListExamsBySource :many

select semester_id, ancode, source, zpa_id, module, main_examer, main_examer_id, exam_type, exam_type_full, zpa_date, zpa_starttime, duration_min, is_repeater_exam, groups, faculty, withdrawn_at from exam
where semester_id = $1 and source = $2 and withdrawn_at is null
order by ancode
`

type ListExamsBySourceParams struct {
	SemesterID string
	Source     string
}

// Exams, ZPA-imported and externally owned, plus the "do we plan it" decision.
//
// Reads that drive planning filter on `withdrawn_at is null`. Under MongoDB an
// exam ZPA stopped delivering simply vanished on the next import, taking the
// planner's constraints with it as orphans; here it is marked and everything
// hanging off it stays.
func (q *Queries) ListExamsBySource(ctx context.Context, arg ListExamsBySourceParams) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExamsBySource, arg.SemesterID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exam{}
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.Source,
			&i.ZpaID,
			&i.Module,
			&i.MainExamer,
			&i.MainExamerID,
			&i.ExamType,
			&i.ExamTypeFull,
			&i.ZpaDate,
			&i.ZpaStarttime,
			&i.DurationMin,
			&i.IsRepeaterExam,
			&i.Groups,
			&i.Faculty,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsToPlan = `-- name: ListExamsToPlan :many
select ancode from exam_to_plan
where semester_id = $1
order by ancode
`

// Absence of a row means UNDECIDED, a real third state: the ZPA import
// auto-preselects only the exams nobody has decided about yet.
func (q *Queries) ListExamsToPlan(ctx context.Context, semesterID string) ([]int, error) {
	rows, err := q.db.Query(ctx, listExamsToPlan, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var ancode int
		if err := rows.Scan(&ancode); err != nil {
			return nil, err
		}
		items = append(items, ancode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamsToPlanFiltered = `-- name: ListExamsToPlanFiltered :many
select ancode from exam_to_plan
where semester_id = $1 and to_plan = $2
order by ancode
`

type ListExamsToPlanFilteredParams struct {
	SemesterID string
	ToPlan     bool
}

func (q *Queries) ListExamsToPlanFiltered(ctx context.Context, arg ListExamsToPlanFilteredParams) ([]int, error) {
	rows, err := q.db.Query(ctx, listExamsToPlanFiltered, arg.SemesterID, arg.ToPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var ancode int
		if err := rows.Scan(&ancode); err != nil {
			return nil, err
		}
		items = append(items, ancode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZPAPrimussAncodes = `-- name: ListZPAPrimussAncodes :many
select ancode, program, primuss_ancode from exam_primuss_ancode
where semester_id = $1 and source = 'zpa'
order by ancode, program collate "C"
`

type ListZPAPrimussAncodesRow struct {
	Ancode        int
	Program       string
	PrimussAncode int
}

func (q *Queries) ListZPAPrimussAncodes(ctx context.Context, semesterID string) ([]ListZPAPrimussAncodesRow, error) {
	rows, err := q.db.Query(ctx, listZPAPrimussAncodes, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZPAPrimussAncodesRow{}
	for rows.Next() {
		var i ListZPAPrimussAncodesRow
		if err := rows.Scan(&i.Ancode, &i.Program, &i.PrimussAncode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZPAPrimussAncodesForExam = `-- name: ListZPAPrimussAncodesForExam :many
select program, primuss_ancode from exam_primuss_ancode
where semester_id = $1 and ancode = $2 and source = 'zpa'
order by program collate "C"
`

type ListZPAPrimussAncodesForExamParams struct {
	SemesterID string
	Ancode     int
}

type ListZPAPrimussAncodesForExamRow struct {
	Program       string
	PrimussAncode int
}

func (q *Queries) ListZPAPrimussAncodesForExam(ctx context.Context, arg ListZPAPrimussAncodesForExamParams) ([]ListZPAPrimussAncodesForExamRow, error) {
	rows, err := q.db.Query(ctx, listZPAPrimussAncodesForExam, arg.SemesterID, arg.Ancode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZPAPrimussAncodesForExamRow{}
	for rows.Next() {
		var i ListZPAPrimussAncodesForExamRow
		if err := rows.Scan(&i.Program, &i.PrimussAncode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExamToPlan = `-- name: SetExamToPlan :exec
insert into exam_to_plan (semester_id, ancode, to_plan)
values ($1, $2, $3)
on conflict (semester_id, ancode) do update set to_plan = excluded.to_plan
`

type SetExamToPlanParams struct {
	SemesterID string
	Ancode     int
	ToPlan     bool
}

func (q *Queries) SetExamToPlan(ctx context.Context, arg SetExamToPlanParams) error {
	_, err := q.db.Exec(ctx, setExamToPlan, arg.SemesterID, arg.Ancode, arg.ToPlan)
	return err
}

const upsertZPAExam = `-- name: UpsertZPAExam :exec
insert into exam (
    semester_id, ancode, source, zpa_id, module, main_examer, main_examer_id,
    exam_type, exam_type_full, zpa_date, zpa_starttime, duration_min,
    is_repeater_exam, groups, faculty, withdrawn_at
) values (
    $1, $2, 'zpa', $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, null
)
on conflict (semester_id, ancode) do update set
    source           = 'zpa',
    zpa_id           = excluded.zpa_id,
    module           = excluded.module,
    main_examer      = excluded.main_examer,
    main_examer_id   = excluded.main_examer_id,
    exam_type        = excluded.exam_type,
    exam_type_full   = excluded.exam_type_full,
    zpa_date         = excluded.zpa_date,
    zpa_starttime    = excluded.zpa_starttime,
    duration_min     = excluded.duration_min,
    is_repeater_exam = excluded.is_repeater_exam,
    groups           = excluded.groups,
    faculty          = excluded.faculty,
    withdrawn_at     = null
`

type UpsertZPAExamParams struct {
	SemesterID     string
	Ancode         int
	ZpaID          *int
	Module         string
	MainExamer     string
	MainExamerID   int
	ExamType       string
	ExamTypeFull   string
	ZpaDate        string
	ZpaStarttime   string
	DurationMin    int
	IsRepeaterExam bool
	Groups         []string
	Faculty        string
}

// The ZPA import UPSERTS. It must not drop and re-insert as CacheZPAExams did:
// the overlay tables reference these rows, and wiping the table would cascade the
// planner's decisions away with it. Reappearing clears withdrawn_at.
func (q *Queries) UpsertZPAExam(ctx context.Context, arg UpsertZPAExamParams) error {
	_, err := q.db.Exec(ctx, upsertZPAExam,
		arg.SemesterID,
		arg.Ancode,
		arg.ZpaID,
		arg.Module,
		arg.MainExamer,
		arg.MainExamerID,
		arg.ExamType,
		arg.ExamTypeFull,
		arg.ZpaDate,
		arg.ZpaStarttime,
		arg.DurationMin,
		arg.IsRepeaterExam,
		arg.Groups,
		arg.Faculty,
	)
	return err
}

const withdrawZPAExamsExcept = `-- name: WithdrawZPAExamsExcept :exec
update exam set withdrawn_at = $1::timestamptz
where semester_id = $2 and source = 'zpa'
  and withdrawn_at is null
  and ancode <> all($3::int[])
`

type WithdrawZPAExamsExceptParams struct {
	At         time.Time
	SemesterID string
	Keep       []int
}

// The other half of the import: what ZPA no longer delivers is marked, never
// deleted. An exam that is already marked keeps its original timestamp, so the
// report can say how long it has been gone.
func (q *Queries) WithdrawZPAExamsExcept(ctx context.Context, arg WithdrawZPAExamsExceptParams) error {
	_, err := q.db.Exec(ctx, withdrawZPAExamsExcept, arg.At, arg.SemesterID, arg.Keep)
	return err
}
