// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation_config.sql

package sqlc

import (
	"context"
)

const getGenerationConfig = `-- name: GetGenerationConfig :one
select id, config, format_version from generation_config where id = 1
`

// The ~33 generator weights are always read and written as a whole and never
// queried by field, so they live in one jsonb column instead of 33 columns that
// would need a migration every time a weight is added.
//
// format_version travels with the blob: the json tags are the GraphQL contract
// too, so renaming a field in the .graphqls would silently change the storage
// format. Reading a version this binary does not know has to fail loudly.
func (q *Queries) GetGenerationConfig(ctx context.Context) (GenerationConfig, error) {
	row := q.db.QueryRow(ctx, getGenerationConfig)
	var i GenerationConfig
	err := row.Scan(&i.ID, &i.Config, &i.FormatVersion)
	return i, err
}

const setGenerationConfig = `-- name: SetGenerationConfig :exec
insert into generation_config (id, config, format_version)
values (1, $1, $2)
on conflict (id) do update set
    config         = excluded.config,
    format_version = excluded.format_version
`

type SetGenerationConfigParams struct {
	Config        []byte
	FormatVersion int
}

func (q *Queries) SetGenerationConfig(ctx context.Context, arg SetGenerationConfigParams) error {
	_, err := q.db.Exec(ctx, setGenerationConfig, arg.Config, arg.FormatVersion)
	return err
}
