// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invigilation.sql

package sqlc

import (
	"context"
	"time"
)

const deleteGeneratedInvigilations = `-- name: DeleteGeneratedInvigilations :exec
delete from invigilation
where semester_id = $1 and not is_self_invigilation
`

func (q *Queries) DeleteGeneratedInvigilations(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteGeneratedInvigilations, semesterID)
	return err
}

const deleteInvigilationInRoomAt = `-- name: DeleteInvigilationInRoomAt :exec
delete from invigilation
where semester_id = $1 and starttime = $2
  and not is_self_invigilation
  and room_name is not distinct from $3
  and is_reserve = $4
`

type DeleteInvigilationInRoomAtParams struct {
	SemesterID string
	Starttime  time.Time
	RoomName   *string
	IsReserve  bool
}

// AddInvigilationAt replaced the document for that room (or the reserve) at that
// time, so a second call for the same slot moves the duty rather than adding one.
// The delete + insert is that replace; there is no unique key to hang an upsert
// on, because the generated invigilations legitimately repeat per room and slot.
func (q *Queries) DeleteInvigilationInRoomAt(ctx context.Context, arg DeleteInvigilationInRoomAtParams) error {
	_, err := q.db.Exec(ctx, deleteInvigilationInRoomAt,
		arg.SemesterID,
		arg.Starttime,
		arg.RoomName,
		arg.IsReserve,
	)
	return err
}

const deleteInvigilatorConstraint = `-- name: DeleteInvigilatorConstraint :execrows
delete from invigilator_constraint where semester_id = $1 and teacher_id = $2
`

type DeleteInvigilatorConstraintParams struct {
	SemesterID string
	TeacherID  int
}

func (q *Queries) DeleteInvigilatorConstraint(ctx context.Context, arg DeleteInvigilatorConstraintParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvigilatorConstraint, arg.SemesterID, arg.TeacherID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvigilatorExcludedDates = `-- name: DeleteInvigilatorExcludedDates :exec
delete from invigilator_excluded_date where semester_id = $1 and teacher_id = $2
`

type DeleteInvigilatorExcludedDatesParams struct {
	SemesterID string
	TeacherID  int
}

func (q *Queries) DeleteInvigilatorExcludedDates(ctx context.Context, arg DeleteInvigilatorExcludedDatesParams) error {
	_, err := q.db.Exec(ctx, deleteInvigilatorExcludedDates, arg.SemesterID, arg.TeacherID)
	return err
}

const deleteInvigilatorTimeWindows = `-- name: DeleteInvigilatorTimeWindows :exec
delete from invigilator_time_window where semester_id = $1 and teacher_id = $2
`

type DeleteInvigilatorTimeWindowsParams struct {
	SemesterID string
	TeacherID  int
}

func (q *Queries) DeleteInvigilatorTimeWindows(ctx context.Context, arg DeleteInvigilatorTimeWindowsParams) error {
	_, err := q.db.Exec(ctx, deleteInvigilatorTimeWindows, arg.SemesterID, arg.TeacherID)
	return err
}

const deletePrePlannedInvigilationAt = `-- name: DeletePrePlannedInvigilationAt :execrows
delete from pre_planned_invigilation
where semester_id = $1 and starttime = $2 and room_name is not distinct from $3
`

type DeletePrePlannedInvigilationAtParams struct {
	SemesterID string
	Starttime  time.Time
	RoomName   *string
}

func (q *Queries) DeletePrePlannedInvigilationAt(ctx context.Context, arg DeletePrePlannedInvigilationAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrePlannedInvigilationAt, arg.SemesterID, arg.Starttime, arg.RoomName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvigilationTodos = `-- name: GetInvigilationTodos :one

select todos, format_version from invigilation_todos where semester_id = $1
`

type GetInvigilationTodosRow struct {
	Todos         []byte
	FormatVersion int
}

// The computed fair-share summary. One row per semester, which is what the
// fixed-_id document always meant -- the primary key is now what the comment in
// db/invigilator.go had to arrange by hand against interleaved writers.
func (q *Queries) GetInvigilationTodos(ctx context.Context, semesterID string) (GetInvigilationTodosRow, error) {
	row := q.db.QueryRow(ctx, getInvigilationTodos, semesterID)
	var i GetInvigilationTodosRow
	err := row.Scan(&i.Todos, &i.FormatVersion)
	return i, err
}

const getInvigilatorConstraint = `-- name: GetInvigilatorConstraint :one
select semester_id, teacher_id, is_not_invigilator from invigilator_constraint
where semester_id = $1 and teacher_id = $2
`

type GetInvigilatorConstraintParams struct {
	SemesterID string
	TeacherID  int
}

func (q *Queries) GetInvigilatorConstraint(ctx context.Context, arg GetInvigilatorConstraintParams) (InvigilatorConstraint, error) {
	row := q.db.QueryRow(ctx, getInvigilatorConstraint, arg.SemesterID, arg.TeacherID)
	var i InvigilatorConstraint
	err := row.Scan(&i.SemesterID, &i.TeacherID, &i.IsNotInvigilator)
	return i, err
}

const getInvigilatorRequirement = `-- name: GetInvigilatorRequirement :one
select semester_id, invigilator_id, invigilator, excluded_dates, part_time, oral_exams_contribution, livecoding_contribution, master_contribution, free_semester, overtime_last_semester, overtime_this_semester from invigilator_requirement
where semester_id = $1 and invigilator_id = $2
`

type GetInvigilatorRequirementParams struct {
	SemesterID    string
	InvigilatorID int
}

func (q *Queries) GetInvigilatorRequirement(ctx context.Context, arg GetInvigilatorRequirementParams) (InvigilatorRequirement, error) {
	row := q.db.QueryRow(ctx, getInvigilatorRequirement, arg.SemesterID, arg.InvigilatorID)
	var i InvigilatorRequirement
	err := row.Scan(
		&i.SemesterID,
		&i.InvigilatorID,
		&i.Invigilator,
		&i.ExcludedDates,
		&i.PartTime,
		&i.OralExamsContribution,
		&i.LivecodingContribution,
		&i.MasterContribution,
		&i.FreeSemester,
		&i.OvertimeLastSemester,
		&i.OvertimeThisSemester,
	)
	return i, err
}

const insertGeneratedInvigilation = `-- name: InsertGeneratedInvigilation :exec
insert into invigilation (
    semester_id, invigilator_id, starttime, room_name, duration_min,
    is_reserve, is_self_invigilation, pre_planned
) values ($1, $2, $3, $4, $5, $6, false, $7)
`

type InsertGeneratedInvigilationParams struct {
	SemesterID    string
	InvigilatorID int
	Starttime     time.Time
	RoomName      *string
	DurationMin   int
	IsReserve     bool
	PrePlanned    bool
}

func (q *Queries) InsertGeneratedInvigilation(ctx context.Context, arg InsertGeneratedInvigilationParams) error {
	_, err := q.db.Exec(ctx, insertGeneratedInvigilation,
		arg.SemesterID,
		arg.InvigilatorID,
		arg.Starttime,
		arg.RoomName,
		arg.DurationMin,
		arg.IsReserve,
		arg.PrePlanned,
	)
	return err
}

const insertInvigilatorExcludedDate = `-- name: InsertInvigilatorExcludedDate :exec
insert into invigilator_excluded_date (semester_id, teacher_id, excluded_on)
values ($1, $2, $3)
on conflict do nothing
`

type InsertInvigilatorExcludedDateParams struct {
	SemesterID string
	TeacherID  int
	ExcludedOn time.Time
}

func (q *Queries) InsertInvigilatorExcludedDate(ctx context.Context, arg InsertInvigilatorExcludedDateParams) error {
	_, err := q.db.Exec(ctx, insertInvigilatorExcludedDate, arg.SemesterID, arg.TeacherID, arg.ExcludedOn)
	return err
}

const insertInvigilatorTimeWindow = `-- name: InsertInvigilatorTimeWindow :exec
insert into invigilator_time_window (
    semester_id, teacher_id, window_date, available_from, available_until
) values ($1, $2, $3, $4, $5)
on conflict (semester_id, teacher_id, window_date) do update set
    available_from  = excluded.available_from,
    available_until = excluded.available_until
`

type InsertInvigilatorTimeWindowParams struct {
	SemesterID     string
	TeacherID      int
	WindowDate     time.Time
	AvailableFrom  *time.Time
	AvailableUntil *time.Time
}

func (q *Queries) InsertInvigilatorTimeWindow(ctx context.Context, arg InsertInvigilatorTimeWindowParams) error {
	_, err := q.db.Exec(ctx, insertInvigilatorTimeWindow,
		arg.SemesterID,
		arg.TeacherID,
		arg.WindowDate,
		arg.AvailableFrom,
		arg.AvailableUntil,
	)
	return err
}

const listInvigilations = `-- name: ListInvigilations :many

select id, semester_id, invigilator_id, starttime, room_name, duration_min, is_reserve, is_self_invigilation, pre_planned from invigilation
where semester_id = $1
order by starttime, room_name collate "C" nulls last, invigilator_id
`

// Aufsichten. invigilations_self and invigilations_other are one table told apart
// by is_self_invigilation -- the distinction is a property of the row, not of a
// collection. Every read that used to concatenate two cursors is one query here.
//
// The `reserve` pseudo-room: a duty not tied to a room is stored with a NULL
// room_name and is_reserve. The Mongo filters spelled that out as
// {roomname: nil, isreserve: true}; here it stays two predicates for the same
// reason -- a room duty must not match the reserve slot and the other way round.
func (q *Queries) ListInvigilations(ctx context.Context, semesterID string) ([]Invigilation, error) {
	rows, err := q.db.Query(ctx, listInvigilations, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invigilation{}
	for rows.Next() {
		var i Invigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsSelfInvigilation,
			&i.PrePlanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilationsBySelf = `-- name: ListInvigilationsBySelf :many
select id, semester_id, invigilator_id, starttime, room_name, duration_min, is_reserve, is_self_invigilation, pre_planned from invigilation
where semester_id = $1 and is_self_invigilation = $2
order by starttime, room_name collate "C" nulls last, invigilator_id
`

type ListInvigilationsBySelfParams struct {
	SemesterID         string
	IsSelfInvigilation bool
}

func (q *Queries) ListInvigilationsBySelf(ctx context.Context, arg ListInvigilationsBySelfParams) ([]Invigilation, error) {
	rows, err := q.db.Query(ctx, listInvigilationsBySelf, arg.SemesterID, arg.IsSelfInvigilation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invigilation{}
	for rows.Next() {
		var i Invigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsSelfInvigilation,
			&i.PrePlanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilationsForInvigilator = `-- name: ListInvigilationsForInvigilator :many
select id, semester_id, invigilator_id, starttime, room_name, duration_min, is_reserve, is_self_invigilation, pre_planned from invigilation
where semester_id = $1 and invigilator_id = $2
order by starttime, room_name collate "C" nulls last
`

type ListInvigilationsForInvigilatorParams struct {
	SemesterID    string
	InvigilatorID int
}

func (q *Queries) ListInvigilationsForInvigilator(ctx context.Context, arg ListInvigilationsForInvigilatorParams) ([]Invigilation, error) {
	rows, err := q.db.Query(ctx, listInvigilationsForInvigilator, arg.SemesterID, arg.InvigilatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invigilation{}
	for rows.Next() {
		var i Invigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsSelfInvigilation,
			&i.PrePlanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilationsInRoomAt = `-- name: ListInvigilationsInRoomAt :many
select id, semester_id, invigilator_id, starttime, room_name, duration_min, is_reserve, is_self_invigilation, pre_planned from invigilation
where semester_id = $1 and starttime = $2
  and room_name = $3 and not is_reserve
order by invigilator_id
`

type ListInvigilationsInRoomAtParams struct {
	SemesterID string
	Starttime  time.Time
	RoomName   *string
}

func (q *Queries) ListInvigilationsInRoomAt(ctx context.Context, arg ListInvigilationsInRoomAtParams) ([]Invigilation, error) {
	rows, err := q.db.Query(ctx, listInvigilationsInRoomAt, arg.SemesterID, arg.Starttime, arg.RoomName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invigilation{}
	for rows.Next() {
		var i Invigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsSelfInvigilation,
			&i.PrePlanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorConstraints = `-- name: ListInvigilatorConstraints :many

select semester_id, teacher_id, is_not_invigilator from invigilator_constraint
where semester_id = $1
order by teacher_id
`

// The planner's per-invigilator constraints, edited in the GUI.
func (q *Queries) ListInvigilatorConstraints(ctx context.Context, semesterID string) ([]InvigilatorConstraint, error) {
	rows, err := q.db.Query(ctx, listInvigilatorConstraints, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvigilatorConstraint{}
	for rows.Next() {
		var i InvigilatorConstraint
		if err := rows.Scan(&i.SemesterID, &i.TeacherID, &i.IsNotInvigilator); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorExcludedDates = `-- name: ListInvigilatorExcludedDates :many
select teacher_id, excluded_on from invigilator_excluded_date
where semester_id = $1
order by teacher_id, excluded_on
`

type ListInvigilatorExcludedDatesRow struct {
	TeacherID  int
	ExcludedOn time.Time
}

func (q *Queries) ListInvigilatorExcludedDates(ctx context.Context, semesterID string) ([]ListInvigilatorExcludedDatesRow, error) {
	rows, err := q.db.Query(ctx, listInvigilatorExcludedDates, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvigilatorExcludedDatesRow{}
	for rows.Next() {
		var i ListInvigilatorExcludedDatesRow
		if err := rows.Scan(&i.TeacherID, &i.ExcludedOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorExcludedDatesForTeacher = `-- name: ListInvigilatorExcludedDatesForTeacher :many
select excluded_on from invigilator_excluded_date
where semester_id = $1 and teacher_id = $2
order by excluded_on
`

type ListInvigilatorExcludedDatesForTeacherParams struct {
	SemesterID string
	TeacherID  int
}

func (q *Queries) ListInvigilatorExcludedDatesForTeacher(ctx context.Context, arg ListInvigilatorExcludedDatesForTeacherParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listInvigilatorExcludedDatesForTeacher, arg.SemesterID, arg.TeacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var excluded_on time.Time
		if err := rows.Scan(&excluded_on); err != nil {
			return nil, err
		}
		items = append(items, excluded_on)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorRequirements = `-- name: ListInvigilatorRequirements :many

select semester_id, invigilator_id, invigilator, excluded_dates, part_time, oral_exams_contribution, livecoding_contribution, master_contribution, free_semester, overtime_last_semester, overtime_this_semester from invigilator_requirement
where semester_id = $1
order by invigilator_id
`

// The ZPA-sourced requirements, written by ReplaceAll (db/save.go).
func (q *Queries) ListInvigilatorRequirements(ctx context.Context, semesterID string) ([]InvigilatorRequirement, error) {
	rows, err := q.db.Query(ctx, listInvigilatorRequirements, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvigilatorRequirement{}
	for rows.Next() {
		var i InvigilatorRequirement
		if err := rows.Scan(
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Invigilator,
			&i.ExcludedDates,
			&i.PartTime,
			&i.OralExamsContribution,
			&i.LivecodingContribution,
			&i.MasterContribution,
			&i.FreeSemester,
			&i.OvertimeLastSemester,
			&i.OvertimeThisSemester,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorTimeWindows = `-- name: ListInvigilatorTimeWindows :many
select teacher_id, window_date, available_from, available_until
from invigilator_time_window
where semester_id = $1
order by teacher_id, window_date
`

type ListInvigilatorTimeWindowsRow struct {
	TeacherID      int
	WindowDate     time.Time
	AvailableFrom  *time.Time
	AvailableUntil *time.Time
}

func (q *Queries) ListInvigilatorTimeWindows(ctx context.Context, semesterID string) ([]ListInvigilatorTimeWindowsRow, error) {
	rows, err := q.db.Query(ctx, listInvigilatorTimeWindows, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvigilatorTimeWindowsRow{}
	for rows.Next() {
		var i ListInvigilatorTimeWindowsRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.WindowDate,
			&i.AvailableFrom,
			&i.AvailableUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvigilatorTimeWindowsForTeacher = `-- name: ListInvigilatorTimeWindowsForTeacher :many
select window_date, available_from, available_until
from invigilator_time_window
where semester_id = $1 and teacher_id = $2
order by window_date
`

type ListInvigilatorTimeWindowsForTeacherParams struct {
	SemesterID string
	TeacherID  int
}

type ListInvigilatorTimeWindowsForTeacherRow struct {
	WindowDate     time.Time
	AvailableFrom  *time.Time
	AvailableUntil *time.Time
}

func (q *Queries) ListInvigilatorTimeWindowsForTeacher(ctx context.Context, arg ListInvigilatorTimeWindowsForTeacherParams) ([]ListInvigilatorTimeWindowsForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listInvigilatorTimeWindowsForTeacher, arg.SemesterID, arg.TeacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvigilatorTimeWindowsForTeacherRow{}
	for rows.Next() {
		var i ListInvigilatorTimeWindowsForTeacherRow
		if err := rows.Scan(&i.WindowDate, &i.AvailableFrom, &i.AvailableUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrePlannedInvigilations = `-- name: ListPrePlannedInvigilations :many

select id, semester_id, invigilator_id, starttime, room_name, is_reserve from pre_planned_invigilation
where semester_id = $1
order by starttime, room_name collate "C" nulls last
`

// The pre-planning, keyed by (starttime, room_name) -- see the table comment in
// 00006 for why not by the invigilator.
func (q *Queries) ListPrePlannedInvigilations(ctx context.Context, semesterID string) ([]PrePlannedInvigilation, error) {
	rows, err := q.db.Query(ctx, listPrePlannedInvigilations, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrePlannedInvigilation{}
	for rows.Next() {
		var i PrePlannedInvigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.IsReserve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrePlannedInvigilationsForInvigilator = `-- name: ListPrePlannedInvigilationsForInvigilator :many
select id, semester_id, invigilator_id, starttime, room_name, is_reserve from pre_planned_invigilation
where semester_id = $1 and invigilator_id = $2
order by starttime, room_name collate "C" nulls last
`

type ListPrePlannedInvigilationsForInvigilatorParams struct {
	SemesterID    string
	InvigilatorID int
}

func (q *Queries) ListPrePlannedInvigilationsForInvigilator(ctx context.Context, arg ListPrePlannedInvigilationsForInvigilatorParams) ([]PrePlannedInvigilation, error) {
	rows, err := q.db.Query(ctx, listPrePlannedInvigilationsForInvigilator, arg.SemesterID, arg.InvigilatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrePlannedInvigilation{}
	for rows.Next() {
		var i PrePlannedInvigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.IsReserve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReserveInvigilationsAt = `-- name: ListReserveInvigilationsAt :many
select id, semester_id, invigilator_id, starttime, room_name, duration_min, is_reserve, is_self_invigilation, pre_planned from invigilation
where semester_id = $1 and starttime = $2
  and room_name is null and is_reserve
order by invigilator_id
`

type ListReserveInvigilationsAtParams struct {
	SemesterID string
	Starttime  time.Time
}

func (q *Queries) ListReserveInvigilationsAt(ctx context.Context, arg ListReserveInvigilationsAtParams) ([]Invigilation, error) {
	rows, err := q.db.Query(ctx, listReserveInvigilationsAt, arg.SemesterID, arg.Starttime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invigilation{}
	for rows.Next() {
		var i Invigilation
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.InvigilatorID,
			&i.Starttime,
			&i.RoomName,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsSelfInvigilation,
			&i.PrePlanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvigilationPrePlannedAt = `-- name: SetInvigilationPrePlannedAt :execrows
update invigilation set pre_planned = $5
where semester_id = $1 and starttime = $2
  and not is_self_invigilation
  and room_name is not distinct from $3
  and is_reserve = $4
`

type SetInvigilationPrePlannedAtParams struct {
	SemesterID string
	Starttime  time.Time
	RoomName   *string
	IsReserve  bool
	PrePlanned bool
}

// is_reserve is passed rather than derived from `room_name is null` in SQL: the
// caller already knows it (the Mongo filter spelled it `isreserve: roomName ==
// nil`), and deriving it here makes sqlc see the same parameter as both text and
// *text.
func (q *Queries) SetInvigilationPrePlannedAt(ctx context.Context, arg SetInvigilationPrePlannedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInvigilationPrePlannedAt,
		arg.SemesterID,
		arg.Starttime,
		arg.RoomName,
		arg.IsReserve,
		arg.PrePlanned,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertInvigilationTodos = `-- name: UpsertInvigilationTodos :exec
insert into invigilation_todos (semester_id, todos, format_version)
values ($1, $2, $3)
on conflict (semester_id) do update set
    todos          = excluded.todos,
    format_version = excluded.format_version
`

type UpsertInvigilationTodosParams struct {
	SemesterID    string
	Todos         []byte
	FormatVersion int
}

func (q *Queries) UpsertInvigilationTodos(ctx context.Context, arg UpsertInvigilationTodosParams) error {
	_, err := q.db.Exec(ctx, upsertInvigilationTodos, arg.SemesterID, arg.Todos, arg.FormatVersion)
	return err
}

const upsertInvigilatorConstraint = `-- name: UpsertInvigilatorConstraint :exec
insert into invigilator_constraint (semester_id, teacher_id, is_not_invigilator)
values ($1, $2, $3)
on conflict (semester_id, teacher_id) do update set
    is_not_invigilator = excluded.is_not_invigilator
`

type UpsertInvigilatorConstraintParams struct {
	SemesterID       string
	TeacherID        int
	IsNotInvigilator bool
}

func (q *Queries) UpsertInvigilatorConstraint(ctx context.Context, arg UpsertInvigilatorConstraintParams) error {
	_, err := q.db.Exec(ctx, upsertInvigilatorConstraint, arg.SemesterID, arg.TeacherID, arg.IsNotInvigilator)
	return err
}

const upsertPrePlannedInvigilation = `-- name: UpsertPrePlannedInvigilation :exec
insert into pre_planned_invigilation (
    semester_id, invigilator_id, starttime, room_name, is_reserve
) values ($1, $2, $3, $4, $5)
on conflict (semester_id, starttime, room_name) do update set
    invigilator_id = excluded.invigilator_id,
    is_reserve     = excluded.is_reserve
`

type UpsertPrePlannedInvigilationParams struct {
	SemesterID    string
	InvigilatorID int
	Starttime     time.Time
	RoomName      *string
	IsReserve     bool
}

func (q *Queries) UpsertPrePlannedInvigilation(ctx context.Context, arg UpsertPrePlannedInvigilationParams) error {
	_, err := q.db.Exec(ctx, upsertPrePlannedInvigilation,
		arg.SemesterID,
		arg.InvigilatorID,
		arg.Starttime,
		arg.RoomName,
		arg.IsReserve,
	)
	return err
}
