// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: joint.sql

package sqlc

import (
	"context"
)

const deleteJointExamsForProgram = `-- name: DeleteJointExamsForProgram :exec

delete from joint_exam where semester_id = $1 and program = $2
`

type DeleteJointExamsForProgramParams struct {
	SemesterID string
	Program    string
}

// Exams of joint study programs (MUC.DAI, MUC.HEALTH), imported from their CSV.
// Was joint_<PROG>, keyed by the German column names of the source file (Nr,
// Modulname, Prüfungsform, ...); those are a header mapping in the importer now.
func (q *Queries) DeleteJointExamsForProgram(ctx context.Context, arg DeleteJointExamsForProgramParams) error {
	_, err := q.db.Exec(ctx, deleteJointExamsForProgram, arg.SemesterID, arg.Program)
	return err
}

const deleteJointLink = `-- name: DeleteJointLink :exec
delete from joint_link
where semester_id = $1 and program = $2 and primuss_ancode = $3
`

type DeleteJointLinkParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
}

func (q *Queries) DeleteJointLink(ctx context.Context, arg DeleteJointLinkParams) error {
	_, err := q.db.Exec(ctx, deleteJointLink, arg.SemesterID, arg.Program, arg.PrimussAncode)
	return err
}

const getJointExam = `-- name: GetJointExam :one
select semester_id, program, primuss_ancode, module, exam_type, grading, duration_min, main_examer, second_examer, is_repeater_exam, planer from joint_exam
where semester_id = $1 and program = $2 and primuss_ancode = $3
`

type GetJointExamParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
}

func (q *Queries) GetJointExam(ctx context.Context, arg GetJointExamParams) (JointExam, error) {
	row := q.db.QueryRow(ctx, getJointExam, arg.SemesterID, arg.Program, arg.PrimussAncode)
	var i JointExam
	err := row.Scan(
		&i.SemesterID,
		&i.Program,
		&i.PrimussAncode,
		&i.Module,
		&i.ExamType,
		&i.Grading,
		&i.DurationMin,
		&i.MainExamer,
		&i.SecondExamer,
		&i.IsRepeaterExam,
		&i.Planer,
	)
	return i, err
}

const getJointLink = `-- name: GetJointLink :one
select semester_id, program, primuss_ancode, kind, ancode, status, source, module, main_examer from joint_link
where semester_id = $1 and program = $2 and primuss_ancode = $3
`

type GetJointLinkParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
}

func (q *Queries) GetJointLink(ctx context.Context, arg GetJointLinkParams) (JointLink, error) {
	row := q.db.QueryRow(ctx, getJointLink, arg.SemesterID, arg.Program, arg.PrimussAncode)
	var i JointLink
	err := row.Scan(
		&i.SemesterID,
		&i.Program,
		&i.PrimussAncode,
		&i.Kind,
		&i.Ancode,
		&i.Status,
		&i.Source,
		&i.Module,
		&i.MainExamer,
	)
	return i, err
}

const insertJointExam = `-- name: InsertJointExam :exec
insert into joint_exam (
    semester_id, program, primuss_ancode, module, exam_type, grading,
    duration_min, main_examer, second_examer, is_repeater_exam, planer
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type InsertJointExamParams struct {
	SemesterID     string
	Program        string
	PrimussAncode  int
	Module         string
	ExamType       string
	Grading        string
	DurationMin    int
	MainExamer     string
	SecondExamer   string
	IsRepeaterExam string
	Planer         string
}

func (q *Queries) InsertJointExam(ctx context.Context, arg InsertJointExamParams) error {
	_, err := q.db.Exec(ctx, insertJointExam,
		arg.SemesterID,
		arg.Program,
		arg.PrimussAncode,
		arg.Module,
		arg.ExamType,
		arg.Grading,
		arg.DurationMin,
		arg.MainExamer,
		arg.SecondExamer,
		arg.IsRepeaterExam,
		arg.Planer,
	)
	return err
}

const listJointExamsForProgram = `-- name: ListJointExamsForProgram :many
select semester_id, program, primuss_ancode, module, exam_type, grading, duration_min, main_examer, second_examer, is_repeater_exam, planer from joint_exam
where semester_id = $1 and program = $2
order by primuss_ancode
`

type ListJointExamsForProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) ListJointExamsForProgram(ctx context.Context, arg ListJointExamsForProgramParams) ([]JointExam, error) {
	rows, err := q.db.Query(ctx, listJointExamsForProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JointExam{}
	for rows.Next() {
		var i JointExam
		if err := rows.Scan(
			&i.SemesterID,
			&i.Program,
			&i.PrimussAncode,
			&i.Module,
			&i.ExamType,
			&i.Grading,
			&i.DurationMin,
			&i.MainExamer,
			&i.SecondExamer,
			&i.IsRepeaterExam,
			&i.Planer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJointLinks = `-- name: ListJointLinks :many
select semester_id, program, primuss_ancode, kind, ancode, status, source, module, main_examer from joint_link
where semester_id = $1
order by program collate "C", primuss_ancode
`

// The link from a joint exam to the local (external or ZPA) ancode representing
// it. Stored explicitly so a later ZPA re-import cannot silently break it.
func (q *Queries) ListJointLinks(ctx context.Context, semesterID string) ([]JointLink, error) {
	rows, err := q.db.Query(ctx, listJointLinks, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JointLink{}
	for rows.Next() {
		var i JointLink
		if err := rows.Scan(
			&i.SemesterID,
			&i.Program,
			&i.PrimussAncode,
			&i.Kind,
			&i.Ancode,
			&i.Status,
			&i.Source,
			&i.Module,
			&i.MainExamer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJointLink = `-- name: UpsertJointLink :exec
insert into joint_link (
    semester_id, program, primuss_ancode, kind, ancode, status, source, module, main_examer
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
on conflict (semester_id, program, primuss_ancode) do update set
    kind        = excluded.kind,
    ancode      = excluded.ancode,
    status      = excluded.status,
    source      = excluded.source,
    module      = excluded.module,
    main_examer = excluded.main_examer
`

type UpsertJointLinkParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
	Kind          string
	Ancode        *int
	Status        string
	Source        string
	Module        string
	MainExamer    string
}

func (q *Queries) UpsertJointLink(ctx context.Context, arg UpsertJointLinkParams) error {
	_, err := q.db.Exec(ctx, upsertJointLink,
		arg.SemesterID,
		arg.Program,
		arg.PrimussAncode,
		arg.Kind,
		arg.Ancode,
		arg.Status,
		arg.Source,
		arg.Module,
		arg.MainExamer,
	)
	return err
}
