// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs_and_state.sql

package sqlc

import (
	"context"
	"time"
)

const deleteEmailAttachments = `-- name: DeleteEmailAttachments :execrows
delete from email_attachment where semester_id = $1 and kind = $2
`

type DeleteEmailAttachmentsParams struct {
	SemesterID string
	Kind       string
}

func (q *Queries) DeleteEmailAttachments(ctx context.Context, arg DeleteEmailAttachmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailAttachments, arg.SemesterID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssembledExamsState = `-- name: GetAssembledExamsState :one

select semester_id, dirty, reason, changed_at from assembled_exams_state where semester_id = $1
`

// Whether the assembled-exam cache is stale. One row per semester -- the Mongo
// version replaced "the" document with an empty filter, which is the same thing
// as long as there is exactly one.
func (q *Queries) GetAssembledExamsState(ctx context.Context, semesterID string) (AssembledExamsState, error) {
	row := q.db.QueryRow(ctx, getAssembledExamsState, semesterID)
	var i AssembledExamsState
	err := row.Scan(
		&i.SemesterID,
		&i.Dirty,
		&i.Reason,
		&i.ChangedAt,
	)
	return i, err
}

const getEmailAttachment = `-- name: GetEmailAttachment :one
select semester_id, kind, key, filename, content_type, size, data, uploaded_at from email_attachment
where semester_id = $1 and kind = $2 and key = $3
`

type GetEmailAttachmentParams struct {
	SemesterID string
	Kind       string
	Key        string
}

func (q *Queries) GetEmailAttachment(ctx context.Context, arg GetEmailAttachmentParams) (EmailAttachment, error) {
	row := q.db.QueryRow(ctx, getEmailAttachment, arg.SemesterID, arg.Kind, arg.Key)
	var i EmailAttachment
	err := row.Scan(
		&i.SemesterID,
		&i.Kind,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedAt,
	)
	return i, err
}

const insertMutationLogEntry = `-- name: InsertMutationLogEntry :exec
insert into mutation_log (
    semester_id, logged_at, name, type, user_email, args, ancodes, error, duration_ms
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMutationLogEntryParams struct {
	SemesterID string
	LoggedAt   time.Time
	Name       string
	Type       string
	UserEmail  *string
	Args       []byte
	Ancodes    []int
	Error      *string
	DurationMs int
}

func (q *Queries) InsertMutationLogEntry(ctx context.Context, arg InsertMutationLogEntryParams) error {
	_, err := q.db.Exec(ctx, insertMutationLogEntry,
		arg.SemesterID,
		arg.LoggedAt,
		arg.Name,
		arg.Type,
		arg.UserEmail,
		arg.Args,
		arg.Ancodes,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const insertSyncLogEntry = `-- name: InsertSyncLogEntry :exec
insert into sync_log (
    semester_id, logged_at, operation, label, direction, system, ok, summary,
    added, changed, removed, entries, format_version
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertSyncLogEntryParams struct {
	SemesterID    string
	LoggedAt      time.Time
	Operation     string
	Label         string
	Direction     string
	System        string
	Ok            bool
	Summary       string
	Added         int
	Changed       int
	Removed       int
	Entries       []byte
	FormatVersion int
}

func (q *Queries) InsertSyncLogEntry(ctx context.Context, arg InsertSyncLogEntryParams) error {
	_, err := q.db.Exec(ctx, insertSyncLogEntry,
		arg.SemesterID,
		arg.LoggedAt,
		arg.Operation,
		arg.Label,
		arg.Direction,
		arg.System,
		arg.Ok,
		arg.Summary,
		arg.Added,
		arg.Changed,
		arg.Removed,
		arg.Entries,
		arg.FormatVersion,
	)
	return err
}

const latestMutationTime = `-- name: LatestMutationTime :one
select logged_at from mutation_log
where semester_id = $1
order by logged_at desc, id desc
limit 1
`

func (q *Queries) LatestMutationTime(ctx context.Context, semesterID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestMutationTime, semesterID)
	var logged_at time.Time
	err := row.Scan(&logged_at)
	return logged_at, err
}

const listEmailAttachmentInfos = `-- name: ListEmailAttachmentInfos :many

select kind, key, filename, content_type, size, uploaded_at
from email_attachment
where semester_id = $1 and kind = $2
order by key collate "C"
`

type ListEmailAttachmentInfosParams struct {
	SemesterID string
	Kind       string
}

type ListEmailAttachmentInfosRow struct {
	Kind        string
	Key         string
	Filename    string
	ContentType string
	Size        int
	UploadedAt  time.Time
}

// Email attachments. The bytes live in the row, as they did in the document.
// The listing deliberately does NOT select data: it drives a GUI table, and a
// cover-page PDF per teacher is megabytes nobody asked for. That was Mongo's
// projection {data: 0}; here it is simply a column list.
func (q *Queries) ListEmailAttachmentInfos(ctx context.Context, arg ListEmailAttachmentInfosParams) ([]ListEmailAttachmentInfosRow, error) {
	rows, err := q.db.Query(ctx, listEmailAttachmentInfos, arg.SemesterID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailAttachmentInfosRow{}
	for rows.Next() {
		var i ListEmailAttachmentInfosRow
		if err := rows.Scan(
			&i.Kind,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutationLog = `-- name: ListMutationLog :many

select id, semester_id, logged_at, name, type, user_email, args, ancodes, error, duration_ms from mutation_log
where semester_id = $1
  and ($2::text is null or type = $2)
  and ($3::text is null or name = $3)
  and ($4::text is null or user_email = $4)
  and ($5::int is null or $5::int = any(ancodes))
  and ($6::jsonb is null or args @> $6::jsonb)
  and ($7::timestamptz is null or logged_at >= $7)
  and ($8::timestamptz is null or logged_at <= $8)
order by logged_at desc, id desc
limit nullif($9::int, 0)
`

type ListMutationLogParams struct {
	SemesterID string
	OpType     *string
	OpName     *string
	UserEmail  *string
	Ancode     *int
	ArgFilters []byte
	Since      *time.Time
	Until      *time.Time
	MaxRows    int
}

// The two audit logs and the two little state tables.
//
// Both logs keep their payload as jsonb -- the mutation args and the sync diff
// are read and written whole with their row, never joined and (with one
// exception below) never queried into.
// The one exception: the mutation-log filter can ask for an argument key/value
// pair, which was Mongo's single $elemMatch (db/mutation_log.go:51). The jsonb
// containment operator says the same thing, and unlike $elemMatch it can use a
// GIN index later if the log ever grows enough to need one.
//
// Every filter is optional and spelled the same way: a NULL parameter means "do
// not filter". A limit of 0 or less means all rows -- the Mongo version simply
// did not call SetLimit.
//
// sqlc.narg, not @name: emit_pointers_for_null_types reaches nullable *columns*,
// not parameters, so a plain @op_type would arrive as a non-nullable string and
// "no filter" would become "filter on the empty string".
func (q *Queries) ListMutationLog(ctx context.Context, arg ListMutationLogParams) ([]MutationLog, error) {
	rows, err := q.db.Query(ctx, listMutationLog,
		arg.SemesterID,
		arg.OpType,
		arg.OpName,
		arg.UserEmail,
		arg.Ancode,
		arg.ArgFilters,
		arg.Since,
		arg.Until,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MutationLog{}
	for rows.Next() {
		var i MutationLog
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.LoggedAt,
			&i.Name,
			&i.Type,
			&i.UserEmail,
			&i.Args,
			&i.Ancodes,
			&i.Error,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutationLogNames = `-- name: ListMutationLogNames :many
select name from (
    select distinct name from mutation_log where semester_id = $1
) n order by name collate "C"
`

// The distinct in a subquery, sorted outside: `select distinct ... order by x
// collate "C"` is error 42P10.
func (q *Queries) ListMutationLogNames(ctx context.Context, semesterID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMutationLogNames, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanningConditions = `-- name: ListPlanningConditions :many

select condition_key from planning_state
where semester_id = $1
order by condition_key collate "C"
`

// The planning state: a set of keys, where presence is truth.
func (q *Queries) ListPlanningConditions(ctx context.Context, semesterID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlanningConditions, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var condition_key string
		if err := rows.Scan(&condition_key); err != nil {
			return nil, err
		}
		items = append(items, condition_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncLog = `-- name: ListSyncLog :many
select id, semester_id, logged_at, operation, label, direction, system, ok, summary, added, changed, removed, entries, format_version from sync_log
where semester_id = $1
order by logged_at desc, id desc
limit nullif($2::int, 0)
`

type ListSyncLogParams struct {
	SemesterID string
	MaxRows    int
}

func (q *Queries) ListSyncLog(ctx context.Context, arg ListSyncLogParams) ([]SyncLog, error) {
	rows, err := q.db.Query(ctx, listSyncLog, arg.SemesterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncLog{}
	for rows.Next() {
		var i SyncLog
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.LoggedAt,
			&i.Operation,
			&i.Label,
			&i.Direction,
			&i.System,
			&i.Ok,
			&i.Summary,
			&i.Added,
			&i.Changed,
			&i.Removed,
			&i.Entries,
			&i.FormatVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssembledExamsState = `-- name: SetAssembledExamsState :exec
insert into assembled_exams_state (semester_id, dirty, reason, changed_at)
values ($1, $2, $3, $4)
on conflict (semester_id) do update set
    dirty      = excluded.dirty,
    reason     = excluded.reason,
    changed_at = excluded.changed_at
`

type SetAssembledExamsStateParams struct {
	SemesterID string
	Dirty      bool
	Reason     *string
	ChangedAt  *time.Time
}

func (q *Queries) SetAssembledExamsState(ctx context.Context, arg SetAssembledExamsStateParams) error {
	_, err := q.db.Exec(ctx, setAssembledExamsState,
		arg.SemesterID,
		arg.Dirty,
		arg.Reason,
		arg.ChangedAt,
	)
	return err
}

const setPlanningCondition = `-- name: SetPlanningCondition :exec
insert into planning_state (semester_id, condition_key)
values ($1, $2)
on conflict do nothing
`

type SetPlanningConditionParams struct {
	SemesterID   string
	ConditionKey string
}

func (q *Queries) SetPlanningCondition(ctx context.Context, arg SetPlanningConditionParams) error {
	_, err := q.db.Exec(ctx, setPlanningCondition, arg.SemesterID, arg.ConditionKey)
	return err
}

const unsetPlanningCondition = `-- name: UnsetPlanningCondition :exec
delete from planning_state where semester_id = $1 and condition_key = $2
`

type UnsetPlanningConditionParams struct {
	SemesterID   string
	ConditionKey string
}

func (q *Queries) UnsetPlanningCondition(ctx context.Context, arg UnsetPlanningConditionParams) error {
	_, err := q.db.Exec(ctx, unsetPlanningCondition, arg.SemesterID, arg.ConditionKey)
	return err
}

const upsertEmailAttachment = `-- name: UpsertEmailAttachment :exec
insert into email_attachment (
    semester_id, kind, key, filename, content_type, size, data, uploaded_at
) values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (semester_id, kind, key) do update set
    filename     = excluded.filename,
    content_type = excluded.content_type,
    size         = excluded.size,
    data         = excluded.data,
    uploaded_at  = excluded.uploaded_at
`

type UpsertEmailAttachmentParams struct {
	SemesterID  string
	Kind        string
	Key         string
	Filename    string
	ContentType string
	Size        int
	Data        []byte
	UploadedAt  time.Time
}

func (q *Queries) UpsertEmailAttachment(ctx context.Context, arg UpsertEmailAttachmentParams) error {
	_, err := q.db.Exec(ctx, upsertEmailAttachment,
		arg.SemesterID,
		arg.Kind,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Data,
		arg.UploadedAt,
	)
	return err
}
