// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AaspfDegree struct {
	Aaspf  int
	Degree string
}

type ActiveSemester struct {
	ID         int
	SemesterID string
}

type AnnyConfig struct {
	ID                   int
	PersonalizationNames []string
}

type AppUser struct {
	Email     string
	Name      string
	Role      string
	Shortname string
}

type BlockedRoom struct {
	SemesterID string
	RoomName   string
	Starttime  pgtype.Timestamptz
	Reason     *string
}

type EmailTemplate struct {
	Name     string
	Markdown string
}

type Exam struct {
	SemesterID     string
	Ancode         int
	Source         string
	ZpaID          *int
	Module         string
	MainExamer     string
	MainExamerID   int
	ExamType       string
	ExamTypeFull   string
	ZpaDate        string
	ZpaStarttime   string
	DurationMin    int
	IsRepeaterExam bool
	Groups         []string
	Faculty        string
	WithdrawnAt    pgtype.Timestamptz
}

type ExamAllowedRoom struct {
	SemesterID string
	Ancode     int
	RoomName   string
}

type ExamCanShareSlot struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
}

type ExamConflictRating struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
	Mtknr       string
	Decision    string
}

type ExamConstraint struct {
	SemesterID       string
	Ancode           int
	NotPlannedByMe   bool
	NotPlannedByMeFk *string
	DoNotPublish     bool
	Online           bool
	Location         *string
	ExcludeDays      []pgtype.Timestamptz
	PossibleDays     []pgtype.Timestamptz
	FixedDay         pgtype.Timestamptz
	FixedTime        pgtype.Timestamptz
}

type ExamDurationOverride struct {
	SemesterID  string
	Ancode      int
	DurationMin int
}

type ExamPrimussAncode struct {
	SemesterID    string
	Ancode        int
	Program       string
	PrimussAncode int
	Source        string
}

type ExamRoomConstraint struct {
	SemesterID       string
	Ancode           int
	PlacesWithSocket bool
	Lab              bool
	Exahm            bool
	Seb              bool
	KdpJiraUrl       *string
	MaxStudents      *int
	AdditionalSeats  *int
	PreExamMinutes   *int
	PostExamMinutes  *int
	Comments         *string
}

type ExamSameSlot struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
}

type ExamToPlan struct {
	SemesterID string
	Ancode     int
	ToPlan     bool
}

type GenerationConfig struct {
	ID            int
	Config        []byte
	FormatVersion int
}

type JointExam struct {
	SemesterID     string
	Program        string
	PrimussAncode  int
	Module         string
	ExamType       string
	Grading        string
	DurationMin    int
	MainExamer     string
	SecondExamer   string
	IsRepeaterExam string
	Planer         string
}

type JointLink struct {
	SemesterID    string
	Program       string
	PrimussAncode int
	Kind          string
	Ancode        *int
	Status        string
	Source        string
	Module        string
	MainExamer    string
}

type NTARow struct {
	Mtknr                string
	Name                 string
	Email                *string
	Compensation         string
	DeltaDurationPercent int
	NeedsRoomAlone       bool
	NeedsHardware        bool
	Program              string
	ValidFrom            string
	ValidUntil           string
	LastSemester         *string
	Deactivated          bool
}

type NtaRoomAloneWaiver struct {
	SemesterID string
	Ancode     int
	Mtknr      string
	Reason     string
}

type PermanentNonInvigilator struct {
	TeacherID  int
	Name       string
	Reason     string
	ValidFrom  *string
	ValidUntil *string
}

type PlanEntry struct {
	SemesterID string
	Ancode     int
	Starttime  pgtype.Timestamptz
	Locked     bool
	PhaseFixed bool
	External   bool
}

type Planer struct {
	ID          int
	Name        string
	Email       string
	TestMail    *string
	Cc          *string
	NoreplyMail *string
	NoreplyName *string
}

type PlannedRoom struct {
	ID                int64
	SemesterID        string
	Ancode            int
	RoomName          string
	DurationMin       int
	Handicap          bool
	HandicapRoomAlone bool
	Reserve           bool
	NtaMtknr          *string
	PrePlanned        bool
}

type PlannedRoomStudent struct {
	PlannedRoomID int64
	Mtknr         string
}

type PlannedRoomV struct {
	ID                int64
	SemesterID        string
	Ancode            int
	RoomName          string
	DurationMin       int
	Handicap          bool
	HandicapRoomAlone bool
	Reserve           bool
	NtaMtknr          *string
	PrePlanned        bool
	Starttime         pgtype.Timestamptz
}

type PrePlannedRoom struct {
	SemesterID string
	Ancode     int
	RoomName   string
	Mtknr      *string
	Reserve    bool
	Seats      *int
}

type PreplanCanShareSlot struct {
	SemesterID string
	ID         int
	OtherID    int
}

type PreplanExam struct {
	SemesterID       string
	ID               int
	ExamKind         string
	ExamerID         int
	ExamerName       string
	Module           string
	Programs         []string
	ExpectedStudents int
	DurationMin      *int
	PlannedStarttime pgtype.Timestamptz
	IsFixed          bool
	Ancode           *int
	Notes            string
	Constraints      []byte
	FormatVersion    int
}

type PreplanNotSameSlot struct {
	SemesterID string
	ID         int
	OtherID    int
}

type PrimussConflict struct {
	SemesterID  string
	Program     string
	Ancode      int
	OtherAncode int
	NumStudents int
}

type PrimussCount struct {
	SemesterID string
	Program    string
	Ancode     int
	Total      int
	Raw        []byte
}

type PrimussExam struct {
	SemesterID string
	Program    string
	Ancode     int
	Module     string
	MainExamer string
	ExamType   string
	Presence   string
	Raw        []byte
}

type Room struct {
	Name             string
	Seats            int
	Handicap         bool
	Lab              bool
	PlacesWithSocket bool
	RequestWith      string
	NeedsRequest     bool
	RequestPriority  int
	Exahm            bool
	Seb              bool
	SebSeats         *int
	HmebSeats        *int
	Deactivated      bool
	Hitzewert        *int
}

type RoomRequest struct {
	SemesterID string
	RoomName   string
	Starttime  pgtype.Timestamptz
	ValidFrom  pgtype.Timestamptz
	ValidUntil pgtype.Timestamptz
	Approved   bool
	Active     bool
}

type SchedulerState struct {
	ID           int
	LastFireAt   pgtype.Timestamptz
	LastFinished pgtype.Timestamptz
	LastStatus   string
	LastTrigger  string
	SemesterID   *string
	TotalChanges int
}

type Semester struct {
	ID            string
	Semester      string
	SchemaVersion int
	ReadOnly      bool
	LastDumpAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type SemesterConfigInput struct {
	SemesterID    string
	Config        []byte
	FormatVersion int
}

type StudentPrepared struct {
	SemesterID    string
	Mtknr         string
	Student       []byte
	FormatVersion int
}

type StudentRegsState struct {
	SemesterID string
	Dirty      bool
}

type Studentreg struct {
	ID            int64
	SemesterID    string
	Program       string
	PrimussAncode int
	Mtknr         string
	GroupName     string
	Name          string
	Presence      string
	Aaspf         *int
	Raw           []byte
}

type StudyProgram struct {
	Shortname         string
	Name              string
	Degree            *string
	ZpaCode           string
	Category          string
	Active            bool
	Retired           bool
	ExternalExamsBase *int
	JointFaculty      *string
}

type UnplacedExam struct {
	SemesterID string
	Ancode     int
	Mtknrs     []string
	NtaMtknr   *string
}

type UserSecret struct {
	Email          string
	JiraKeyVersion *int
	JiraNonce      []byte
	JiraCiphertext []byte
	JiraUpdatedAt  pgtype.Timestamptz
}
