// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveSemester struct {
	ID         int
	SemesterID string
}

type AnnyConfig struct {
	ID                   int
	PersonalizationNames []string
}

type AppUser struct {
	Email     string
	Name      string
	Role      string
	Shortname string
}

type EmailTemplate struct {
	Name     string
	Markdown string
}

type Exam struct {
	SemesterID     string
	Ancode         int
	Source         string
	ZpaID          *int
	Module         string
	MainExamer     string
	MainExamerID   int
	ExamType       string
	ExamTypeFull   string
	ZpaDate        string
	ZpaStarttime   string
	DurationMin    int
	IsRepeaterExam bool
	Groups         []string
	Faculty        string
	WithdrawnAt    pgtype.Timestamptz
}

type ExamAllowedRoom struct {
	SemesterID string
	Ancode     int
	RoomName   string
}

type ExamCanShareSlot struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
}

type ExamConflictRating struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
	Mtknr       string
	Decision    string
}

type ExamConstraint struct {
	SemesterID       string
	Ancode           int
	NotPlannedByMe   bool
	NotPlannedByMeFk *string
	DoNotPublish     bool
	Online           bool
	Location         *string
	ExcludeDays      []pgtype.Timestamptz
	PossibleDays     []pgtype.Timestamptz
	FixedDay         pgtype.Timestamptz
	FixedTime        pgtype.Timestamptz
}

type ExamDurationOverride struct {
	SemesterID  string
	Ancode      int
	DurationMin int
}

type ExamPrimussAncode struct {
	SemesterID    string
	Ancode        int
	Program       string
	PrimussAncode int
	Source        string
}

type ExamRoomConstraint struct {
	SemesterID       string
	Ancode           int
	PlacesWithSocket bool
	Lab              bool
	Exahm            bool
	Seb              bool
	KdpJiraUrl       *string
	MaxStudents      *int
	AdditionalSeats  *int
	PreExamMinutes   *int
	PostExamMinutes  *int
	Comments         *string
}

type ExamSameSlot struct {
	SemesterID  string
	Ancode      int
	OtherAncode int
}

type ExamToPlan struct {
	SemesterID string
	Ancode     int
	ToPlan     bool
}

type GenerationConfig struct {
	ID            int
	Config        []byte
	FormatVersion int
}

type NTARow struct {
	Mtknr                string
	Name                 string
	Email                *string
	Compensation         string
	DeltaDurationPercent int
	NeedsRoomAlone       bool
	NeedsHardware        bool
	Program              string
	ValidFrom            string
	ValidUntil           string
	LastSemester         *string
	Deactivated          bool
}

type PermanentNonInvigilator struct {
	TeacherID  int
	Name       string
	Reason     string
	ValidFrom  *string
	ValidUntil *string
}

type Planer struct {
	ID          int
	Name        string
	Email       string
	TestMail    *string
	Cc          *string
	NoreplyMail *string
	NoreplyName *string
}

type Room struct {
	Name             string
	Seats            int
	Handicap         bool
	Lab              bool
	PlacesWithSocket bool
	RequestWith      string
	NeedsRequest     bool
	RequestPriority  int
	Exahm            bool
	Seb              bool
	SebSeats         *int
	HmebSeats        *int
	Deactivated      bool
	Hitzewert        *int
}

type SchedulerState struct {
	ID           int
	LastFireAt   pgtype.Timestamptz
	LastFinished pgtype.Timestamptz
	LastStatus   string
	LastTrigger  string
	SemesterID   *string
	TotalChanges int
}

type Semester struct {
	ID            string
	Semester      string
	SchemaVersion int
	ReadOnly      bool
	LastDumpAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type SemesterConfigInput struct {
	SemesterID    string
	Config        []byte
	FormatVersion int
}

type StudyProgram struct {
	Shortname         string
	Name              string
	Degree            *string
	ZpaCode           string
	Category          string
	Active            bool
	Retired           bool
	ExternalExamsBase *int
	JointFaculty      *string
}

type UserSecret struct {
	Email          string
	JiraKeyVersion *int
	JiraNonce      []byte
	JiraCiphertext []byte
	JiraUpdatedAt  pgtype.Timestamptz
}
