// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nta.sql

package sqlc

import (
	"context"
)

const getNta = `-- name: GetNta :one
select mtknr, name, email, compensation, delta_duration_percent, needs_room_alone, needs_hardware, program, valid_from, valid_until, last_semester, deactivated from nta where mtknr = $1
`

func (q *Queries) GetNta(ctx context.Context, mtknr string) (NTARow, error) {
	row := q.db.QueryRow(ctx, getNta, mtknr)
	var i NTARow
	err := row.Scan(
		&i.Mtknr,
		&i.Name,
		&i.Email,
		&i.Compensation,
		&i.DeltaDurationPercent,
		&i.NeedsRoomAlone,
		&i.NeedsHardware,
		&i.Program,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.LastSemester,
		&i.Deactivated,
	)
	return i, err
}

const getSemesterLabel = `-- name: GetSemesterLabel :one
select semester from semester where id = $1
`

// The label written into nta.last_semester is the LOGICAL semester ("2026 SS"),
// not the workspace id ("2026-WS") -- verified against the 63 stored values.
func (q *Queries) GetSemesterLabel(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSemesterLabel, id)
	var semester string
	err := row.Scan(&semester)
	return semester, err
}

const insertNta = `-- name: InsertNta :one
insert into nta (
    mtknr, name, email, compensation, delta_duration_percent,
    needs_room_alone, needs_hardware, program, valid_from, valid_until,
    last_semester, deactivated
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
returning mtknr, name, email, compensation, delta_duration_percent, needs_room_alone, needs_hardware, program, valid_from, valid_until, last_semester, deactivated
`

type InsertNtaParams struct {
	Mtknr                string
	Name                 string
	Email                *string
	Compensation         string
	DeltaDurationPercent int
	NeedsRoomAlone       bool
	NeedsHardware        bool
	Program              string
	ValidFrom            string
	ValidUntil           string
	LastSemester         *string
	Deactivated          bool
}

func (q *Queries) InsertNta(ctx context.Context, arg InsertNtaParams) (NTARow, error) {
	row := q.db.QueryRow(ctx, insertNta,
		arg.Mtknr,
		arg.Name,
		arg.Email,
		arg.Compensation,
		arg.DeltaDurationPercent,
		arg.NeedsRoomAlone,
		arg.NeedsHardware,
		arg.Program,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.LastSemester,
		arg.Deactivated,
	)
	var i NTARow
	err := row.Scan(
		&i.Mtknr,
		&i.Name,
		&i.Email,
		&i.Compensation,
		&i.DeltaDurationPercent,
		&i.NeedsRoomAlone,
		&i.NeedsHardware,
		&i.Program,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.LastSemester,
		&i.Deactivated,
	)
	return i, err
}

const listNtas = `-- name: ListNtas :many
select mtknr, name, email, compensation, delta_duration_percent, needs_room_alone, needs_hardware, program, valid_from, valid_until, last_semester, deactivated from nta order by name
`

func (q *Queries) ListNtas(ctx context.Context) ([]NTARow, error) {
	rows, err := q.db.Query(ctx, listNtas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NTARow{}
	for rows.Next() {
		var i NTARow
		if err := rows.Scan(
			&i.Mtknr,
			&i.Name,
			&i.Email,
			&i.Compensation,
			&i.DeltaDurationPercent,
			&i.NeedsRoomAlone,
			&i.NeedsHardware,
			&i.Program,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.LastSemester,
			&i.Deactivated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceNta = `-- name: ReplaceNta :one
update nta set
    name                   = $2,
    email                  = $3,
    compensation           = $4,
    delta_duration_percent = $5,
    needs_room_alone       = $6,
    needs_hardware         = $7,
    program                = $8,
    valid_from             = $9,
    valid_until            = $10,
    last_semester          = $11,
    deactivated            = $12
where mtknr = $1
returning mtknr, name, email, compensation, delta_duration_percent, needs_room_alone, needs_hardware, program, valid_from, valid_until, last_semester, deactivated
`

type ReplaceNtaParams struct {
	Mtknr                string
	Name                 string
	Email                *string
	Compensation         string
	DeltaDurationPercent int
	NeedsRoomAlone       bool
	NeedsHardware        bool
	Program              string
	ValidFrom            string
	ValidUntil           string
	LastSemester         *string
	Deactivated          bool
}

// ReplaceNta mirrors the Mongo ReplaceOne: it does NOT upsert. A missing row
// changes nothing and returns no row, which the caller maps to (nil, nil).
func (q *Queries) ReplaceNta(ctx context.Context, arg ReplaceNtaParams) (NTARow, error) {
	row := q.db.QueryRow(ctx, replaceNta,
		arg.Mtknr,
		arg.Name,
		arg.Email,
		arg.Compensation,
		arg.DeltaDurationPercent,
		arg.NeedsRoomAlone,
		arg.NeedsHardware,
		arg.Program,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.LastSemester,
		arg.Deactivated,
	)
	var i NTARow
	err := row.Scan(
		&i.Mtknr,
		&i.Name,
		&i.Email,
		&i.Compensation,
		&i.DeltaDurationPercent,
		&i.NeedsRoomAlone,
		&i.NeedsHardware,
		&i.Program,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.LastSemester,
		&i.Deactivated,
	)
	return i, err
}

const setLastSemesterOnNtas = `-- name: SetLastSemesterOnNtas :many
update nta set last_semester = $1
where mtknr = any($2::text[])
returning mtknr
`

type SetLastSemesterOnNtasParams struct {
	LastSemester *string
	Mtknrs       []string
}

// SetSemesterOnNTAs marks the NTAs that appear in this semester's registrations.
// The Mongo version issued one FindOneAndUpdate per student; this is the same
// work as a single statement, and `returning` still tells the caller which mtknr
// had no NTA so the log message survives.
func (q *Queries) SetLastSemesterOnNtas(ctx context.Context, arg SetLastSemesterOnNtasParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setLastSemesterOnNtas, arg.LastSemester, arg.Mtknrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var mtknr string
		if err := rows.Scan(&mtknr); err != nil {
			return nil, err
		}
		items = append(items, mtknr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNtaDeactivated = `-- name: SetNtaDeactivated :one
update nta set deactivated = $2 where mtknr = $1 returning mtknr, name, email, compensation, delta_duration_percent, needs_room_alone, needs_hardware, program, valid_from, valid_until, last_semester, deactivated
`

type SetNtaDeactivatedParams struct {
	Mtknr       string
	Deactivated bool
}

func (q *Queries) SetNtaDeactivated(ctx context.Context, arg SetNtaDeactivatedParams) (NTARow, error) {
	row := q.db.QueryRow(ctx, setNtaDeactivated, arg.Mtknr, arg.Deactivated)
	var i NTARow
	err := row.Scan(
		&i.Mtknr,
		&i.Name,
		&i.Email,
		&i.Compensation,
		&i.DeltaDurationPercent,
		&i.NeedsRoomAlone,
		&i.NeedsHardware,
		&i.Program,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.LastSemester,
		&i.Deactivated,
	)
	return i, err
}
