// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permanent_non_invigilators.sql

package sqlc

import (
	"context"
)

const deletePermanentNonInvigilator = `-- name: DeletePermanentNonInvigilator :execrows
delete from permanent_non_invigilator where teacher_id = $1
`

func (q *Queries) DeletePermanentNonInvigilator(ctx context.Context, teacherID int) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermanentNonInvigilator, teacherID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPermanentNonInvigilators = `-- name: ListPermanentNonInvigilators :many
select teacher_id, name, reason, valid_from, valid_until from permanent_non_invigilator order by name
`

// The Mongo version returned these in natural order, i.e. whatever the storage
// engine felt like. Ordering by the denormalized name makes the GUI list stable;
// no caller depended on the old order. Deliberately no `collate "C"` here: these
// are people's names, so the cluster collation is the right one to follow.
func (q *Queries) ListPermanentNonInvigilators(ctx context.Context) ([]PermanentNonInvigilator, error) {
	rows, err := q.db.Query(ctx, listPermanentNonInvigilators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermanentNonInvigilator{}
	for rows.Next() {
		var i PermanentNonInvigilator
		if err := rows.Scan(
			&i.TeacherID,
			&i.Name,
			&i.Reason,
			&i.ValidFrom,
			&i.ValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPermanentNonInvigilator = `-- name: UpsertPermanentNonInvigilator :exec
insert into permanent_non_invigilator (
    teacher_id, name, reason, valid_from, valid_until
) values (
    $1, $2, $3, $4, $5
)
on conflict (teacher_id) do update set
    name        = excluded.name,
    reason      = excluded.reason,
    valid_from  = excluded.valid_from,
    valid_until = excluded.valid_until
`

type UpsertPermanentNonInvigilatorParams struct {
	TeacherID  int
	Name       string
	Reason     string
	ValidFrom  *string
	ValidUntil *string
}

func (q *Queries) UpsertPermanentNonInvigilator(ctx context.Context, arg UpsertPermanentNonInvigilatorParams) error {
	_, err := q.db.Exec(ctx, upsertPermanentNonInvigilator,
		arg.TeacherID,
		arg.Name,
		arg.Reason,
		arg.ValidFrom,
		arg.ValidUntil,
	)
	return err
}
