// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package sqlc

import (
	"context"
	"time"
)

const clearAllPhaseFixed = `-- name: ClearAllPhaseFixed :exec
update plan_entry set phase_fixed = false
where semester_id = $1 and phase_fixed
`

func (q *Queries) ClearAllPhaseFixed(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, clearAllPhaseFixed, semesterID)
	return err
}

const deleteGeneratedPlanEntries = `-- name: DeleteGeneratedPlanEntries :execrows
delete from plan_entry
where semester_id = $1 and not external and not locked and not phase_fixed
`

// Everything the generator produced, which is everything that is neither an
// external entry, nor manually locked, nor frozen by phase A. Mongo spelled the
// three exclusions as `$ne: true`, which also matched documents where the field
// was absent; the columns are NOT NULL here, so plain negation is the same set.
func (q *Queries) DeleteGeneratedPlanEntries(ctx context.Context, semesterID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeneratedPlanEntries, semesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPlanEntry = `-- name: GetPlanEntry :one
select semester_id, ancode, starttime, locked, phase_fixed, external from plan_entry
where semester_id = $1 and ancode = $2
`

type GetPlanEntryParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) GetPlanEntry(ctx context.Context, arg GetPlanEntryParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, getPlanEntry, arg.SemesterID, arg.Ancode)
	var i PlanEntry
	err := row.Scan(
		&i.SemesterID,
		&i.Ancode,
		&i.Starttime,
		&i.Locked,
		&i.PhaseFixed,
		&i.External,
	)
	return i, err
}

const listPlanEntries = `-- name: ListPlanEntries :many

select semester_id, ancode, starttime, locked, phase_fixed, external from plan_entry
where semester_id = $1
order by ancode
`

// The schedule: one row per exam that has been placed, or that is known to the
// plan but not yet placed (starttime null).
//
// Nothing here reads or writes a room's start time. That is the whole point of
// planned_room_v -- see db/queries/rooms.sql.
func (q *Queries) ListPlanEntries(ctx context.Context, semesterID string) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, listPlanEntries, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanEntry{}
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.Starttime,
			&i.Locked,
			&i.PhaseFixed,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanEntriesAt = `-- name: ListPlanEntriesAt :many
select semester_id, ancode, starttime, locked, phase_fixed, external from plan_entry
where semester_id = $1 and starttime = $2
order by ancode
`

type ListPlanEntriesAtParams struct {
	SemesterID string
	Starttime  *time.Time
}

func (q *Queries) ListPlanEntriesAt(ctx context.Context, arg ListPlanEntriesAtParams) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, listPlanEntriesAt, arg.SemesterID, arg.Starttime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanEntry{}
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.Starttime,
			&i.Locked,
			&i.PhaseFixed,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWholePlan = `-- name: LockWholePlan :execrows
update plan_entry set locked = true
where semester_id = $1 and not locked
`

func (q *Queries) LockWholePlan(ctx context.Context, semesterID string) (int64, error) {
	result, err := q.db.Exec(ctx, lockWholePlan, semesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPlanEntryLocked = `-- name: SetPlanEntryLocked :exec
update plan_entry set locked = $3
where semester_id = $1 and ancode = $2
`

type SetPlanEntryLockedParams struct {
	SemesterID string
	Ancode     int
	Locked     bool
}

func (q *Queries) SetPlanEntryLocked(ctx context.Context, arg SetPlanEntryLockedParams) error {
	_, err := q.db.Exec(ctx, setPlanEntryLocked, arg.SemesterID, arg.Ancode, arg.Locked)
	return err
}

const setPlanEntryPhaseFixed = `-- name: SetPlanEntryPhaseFixed :exec
update plan_entry set phase_fixed = $3
where semester_id = $1 and ancode = $2
`

type SetPlanEntryPhaseFixedParams struct {
	SemesterID string
	Ancode     int
	PhaseFixed bool
}

func (q *Queries) SetPlanEntryPhaseFixed(ctx context.Context, arg SetPlanEntryPhaseFixedParams) error {
	_, err := q.db.Exec(ctx, setPlanEntryPhaseFixed, arg.SemesterID, arg.Ancode, arg.PhaseFixed)
	return err
}

const upsertPlanEntry = `-- name: UpsertPlanEntry :exec
insert into plan_entry (semester_id, ancode, starttime, locked, phase_fixed, external)
values ($1, $2, $3, $4, $5, $6)
on conflict (semester_id, ancode) do update set
    starttime   = excluded.starttime,
    locked      = excluded.locked,
    phase_fixed = excluded.phase_fixed,
    external    = excluded.external
`

type UpsertPlanEntryParams struct {
	SemesterID string
	Ancode     int
	Starttime  *time.Time
	Locked     bool
	PhaseFixed bool
	External   bool
}

// AddExamToSlot replaced the whole document: Mongo deleted every entry for the
// ancode and inserted the new one, so the flags came from the passed entry and
// not from what was there before. An upsert that sets every column is the same
// write, minus the window in which the exam was unplanned.
func (q *Queries) UpsertPlanEntry(ctx context.Context, arg UpsertPlanEntryParams) error {
	_, err := q.db.Exec(ctx, upsertPlanEntry,
		arg.SemesterID,
		arg.Ancode,
		arg.Starttime,
		arg.Locked,
		arg.PhaseFixed,
		arg.External,
	)
	return err
}
