// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preplan_exams.sql

package sqlc

import (
	"context"
	"time"
)

const deletePreplanCanShareSlotFor = `-- name: DeletePreplanCanShareSlotFor :exec
delete from preplan_can_share_slot
where semester_id = $1 and (id = $2::int or other_id = $2::int)
`

type DeletePreplanCanShareSlotForParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) DeletePreplanCanShareSlotFor(ctx context.Context, arg DeletePreplanCanShareSlotForParams) error {
	_, err := q.db.Exec(ctx, deletePreplanCanShareSlotFor, arg.SemesterID, arg.ID)
	return err
}

const deletePreplanExam = `-- name: DeletePreplanExam :execrows
delete from preplan_exam where semester_id = $1 and id = $2
`

type DeletePreplanExamParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) DeletePreplanExam(ctx context.Context, arg DeletePreplanExamParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePreplanExam, arg.SemesterID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePreplanNotSameSlotFor = `-- name: DeletePreplanNotSameSlotFor :exec
delete from preplan_not_same_slot
where semester_id = $1 and (id = $2::int or other_id = $2::int)
`

type DeletePreplanNotSameSlotForParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) DeletePreplanNotSameSlotFor(ctx context.Context, arg DeletePreplanNotSameSlotForParams) error {
	_, err := q.db.Exec(ctx, deletePreplanNotSameSlotFor, arg.SemesterID, arg.ID)
	return err
}

const getPreplanExam = `-- name: GetPreplanExam :one
select semester_id, id, exam_kind, examer_id, examer_name, module, programs, expected_students, duration_min, planned_starttime, is_fixed, ancode, notes, constraints, format_version from preplan_exam
where semester_id = $1 and id = $2
`

type GetPreplanExamParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) GetPreplanExam(ctx context.Context, arg GetPreplanExamParams) (PreplanExam, error) {
	row := q.db.QueryRow(ctx, getPreplanExam, arg.SemesterID, arg.ID)
	var i PreplanExam
	err := row.Scan(
		&i.SemesterID,
		&i.ID,
		&i.ExamKind,
		&i.ExamerID,
		&i.ExamerName,
		&i.Module,
		&i.Programs,
		&i.ExpectedStudents,
		&i.DurationMin,
		&i.PlannedStarttime,
		&i.IsFixed,
		&i.Ancode,
		&i.Notes,
		&i.Constraints,
		&i.FormatVersion,
	)
	return i, err
}

const insertPreplanCanShareSlot = `-- name: InsertPreplanCanShareSlot :exec
insert into preplan_can_share_slot (semester_id, id, other_id)
values ($1, least($2::int, $3::int), greatest($2::int, $3::int))
on conflict do nothing
`

type InsertPreplanCanShareSlotParams struct {
	SemesterID string
	Column2    int
	Column3    int
}

func (q *Queries) InsertPreplanCanShareSlot(ctx context.Context, arg InsertPreplanCanShareSlotParams) error {
	_, err := q.db.Exec(ctx, insertPreplanCanShareSlot, arg.SemesterID, arg.Column2, arg.Column3)
	return err
}

const insertPreplanNotSameSlot = `-- name: InsertPreplanNotSameSlot :exec
insert into preplan_not_same_slot (semester_id, id, other_id)
values ($1, least($2::int, $3::int), greatest($2::int, $3::int))
on conflict do nothing
`

type InsertPreplanNotSameSlotParams struct {
	SemesterID string
	Column2    int
	Column3    int
}

func (q *Queries) InsertPreplanNotSameSlot(ctx context.Context, arg InsertPreplanNotSameSlotParams) error {
	_, err := q.db.Exec(ctx, insertPreplanNotSameSlot, arg.SemesterID, arg.Column2, arg.Column3)
	return err
}

const listPreplanCanShareSlot = `-- name: ListPreplanCanShareSlot :many
select id, other_id from preplan_can_share_slot
where semester_id = $1
order by id, other_id
`

type ListPreplanCanShareSlotRow struct {
	ID      int
	OtherID int
}

func (q *Queries) ListPreplanCanShareSlot(ctx context.Context, semesterID string) ([]ListPreplanCanShareSlotRow, error) {
	rows, err := q.db.Query(ctx, listPreplanCanShareSlot, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreplanCanShareSlotRow{}
	for rows.Next() {
		var i ListPreplanCanShareSlotRow
		if err := rows.Scan(&i.ID, &i.OtherID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreplanExams = `-- name: ListPreplanExams :many

select semester_id, id, exam_kind, examer_id, examer_name, module, programs, expected_students, duration_min, planned_starttime, is_fixed, ancode, notes, constraints, format_version from preplan_exam
where semester_id = $1
order by id
`

// Vorplanung: the EXaHM/SEB pseudo-exams that size the Anny bookings before the
// real ZPA exams are known.
//
// The id stays an explicit per-semester integer rather than an identity column:
// the two pair tables reference it, and the CSV round-trip re-imports rows by id
// so those references survive a restore. That is what UpsertPreplanExam is for.
func (q *Queries) ListPreplanExams(ctx context.Context, semesterID string) ([]PreplanExam, error) {
	rows, err := q.db.Query(ctx, listPreplanExams, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PreplanExam{}
	for rows.Next() {
		var i PreplanExam
		if err := rows.Scan(
			&i.SemesterID,
			&i.ID,
			&i.ExamKind,
			&i.ExamerID,
			&i.ExamerName,
			&i.Module,
			&i.Programs,
			&i.ExpectedStudents,
			&i.DurationMin,
			&i.PlannedStarttime,
			&i.IsFixed,
			&i.Ancode,
			&i.Notes,
			&i.Constraints,
			&i.FormatVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreplanNotSameSlot = `-- name: ListPreplanNotSameSlot :many

select id, other_id from preplan_not_same_slot
where semester_id = $1
order by id, other_id
`

type ListPreplanNotSameSlotRow struct {
	ID      int
	OtherID int
}

// The two pair relations. Like exam_same_slot these are canonical unordered
// pairs, so a read for one pre-exam looks in both columns and a write orders the
// ids first.
func (q *Queries) ListPreplanNotSameSlot(ctx context.Context, semesterID string) ([]ListPreplanNotSameSlotRow, error) {
	rows, err := q.db.Query(ctx, listPreplanNotSameSlot, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreplanNotSameSlotRow{}
	for rows.Next() {
		var i ListPreplanNotSameSlotRow
		if err := rows.Scan(&i.ID, &i.OtherID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPreplanExamID = `-- name: NextPreplanExamID :one
select (coalesce(max(id), 0) + 1)::int from preplan_exam where semester_id = $1
`

// max(id)+1, starting at 1. Same answer as the Mongo sort-descending-take-one,
// and coalesce covers the empty table the way ErrNoDocuments did.
//
// The ::int cast is needed: max() over an int4 is int8 in sqlc's eyes, and the
// int override in sqlc.yaml only reaches pg_catalog.int4.
func (q *Queries) NextPreplanExamID(ctx context.Context, semesterID string) (int, error) {
	row := q.db.QueryRow(ctx, nextPreplanExamID, semesterID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const preplanExamExists = `-- name: PreplanExamExists :one
select exists (select 1 from preplan_exam where semester_id = $1 and id = $2)
`

type PreplanExamExistsParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) PreplanExamExists(ctx context.Context, arg PreplanExamExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, preplanExamExists, arg.SemesterID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPreplanExam = `-- name: UpsertPreplanExam :exec
insert into preplan_exam (
    semester_id, id, exam_kind, examer_id, examer_name, module, programs,
    expected_students, duration_min, planned_starttime, is_fixed, ancode, notes,
    constraints, format_version
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
on conflict (semester_id, id) do update set
    exam_kind         = excluded.exam_kind,
    examer_id         = excluded.examer_id,
    examer_name       = excluded.examer_name,
    module            = excluded.module,
    programs          = excluded.programs,
    expected_students = excluded.expected_students,
    duration_min      = excluded.duration_min,
    planned_starttime = excluded.planned_starttime,
    is_fixed          = excluded.is_fixed,
    ancode            = excluded.ancode,
    notes             = excluded.notes,
    constraints       = excluded.constraints,
    format_version    = excluded.format_version
`

type UpsertPreplanExamParams struct {
	SemesterID       string
	ID               int
	ExamKind         string
	ExamerID         int
	ExamerName       string
	Module           string
	Programs         []string
	ExpectedStudents int
	DurationMin      *int
	PlannedStarttime *time.Time
	IsFixed          bool
	Ancode           *int
	Notes            string
	Constraints      []byte
	FormatVersion    int
}

func (q *Queries) UpsertPreplanExam(ctx context.Context, arg UpsertPreplanExamParams) error {
	_, err := q.db.Exec(ctx, upsertPreplanExam,
		arg.SemesterID,
		arg.ID,
		arg.ExamKind,
		arg.ExamerID,
		arg.ExamerName,
		arg.Module,
		arg.Programs,
		arg.ExpectedStudents,
		arg.DurationMin,
		arg.PlannedStarttime,
		arg.IsFixed,
		arg.Ancode,
		arg.Notes,
		arg.Constraints,
		arg.FormatVersion,
	)
	return err
}
