// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: primuss_exams.sql

package sqlc

import (
	"context"
)

const changePrimussExamAncode = `-- name: ChangePrimussExamAncode :one
update primuss_exam set ancode = $4
where semester_id = $1 and program = $2 and ancode = $3
returning semester_id, program, ancode, module, main_examer, exam_type, presence, raw
`

type ChangePrimussExamAncodeParams struct {
	SemesterID string
	Program    string
	Ancode     int
	Ancode_2   int
}

// Renumbering a Primuss exam. The counter and both sides of every conflict follow
// by ON UPDATE CASCADE, so this single statement replaces what used to be three
// writes plus a $rename over field names.
func (q *Queries) ChangePrimussExamAncode(ctx context.Context, arg ChangePrimussExamAncodeParams) (PrimussExam, error) {
	row := q.db.QueryRow(ctx, changePrimussExamAncode,
		arg.SemesterID,
		arg.Program,
		arg.Ancode,
		arg.Ancode_2,
	)
	var i PrimussExam
	err := row.Scan(
		&i.SemesterID,
		&i.Program,
		&i.Ancode,
		&i.Module,
		&i.MainExamer,
		&i.ExamType,
		&i.Presence,
		&i.Raw,
	)
	return i, err
}

const deletePrimussExamsForSemester = `-- name: DeletePrimussExamsForSemester :exec
delete from primuss_exam where semester_id = $1
`

func (q *Queries) DeletePrimussExamsForSemester(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deletePrimussExamsForSemester, semesterID)
	return err
}

const deleteStudentRegsForSemester = `-- name: DeleteStudentRegsForSemester :exec
delete from studentreg where semester_id = $1
`

// studentreg has no foreign key to primuss_exam (source data, nothing hand-entered
// hangs off it), so it is not reached by the cascade and has to be cleared here.
func (q *Queries) DeleteStudentRegsForSemester(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteStudentRegsForSemester, semesterID)
	return err
}

const getPrimussExam = `-- name: GetPrimussExam :one
select semester_id, program, ancode, module, main_examer, exam_type, presence, raw from primuss_exam where semester_id = $1 and program = $2 and ancode = $3
`

type GetPrimussExamParams struct {
	SemesterID string
	Program    string
	Ancode     int
}

func (q *Queries) GetPrimussExam(ctx context.Context, arg GetPrimussExamParams) (PrimussExam, error) {
	row := q.db.QueryRow(ctx, getPrimussExam, arg.SemesterID, arg.Program, arg.Ancode)
	var i PrimussExam
	err := row.Scan(
		&i.SemesterID,
		&i.Program,
		&i.Ancode,
		&i.Module,
		&i.MainExamer,
		&i.ExamType,
		&i.Presence,
		&i.Raw,
	)
	return i, err
}

const listPrimussExamsForAncode = `-- name: ListPrimussExamsForAncode :many
select semester_id, program, ancode, module, main_examer, exam_type, presence, raw from primuss_exam
where semester_id = $1 and ancode = $2
order by program collate "C"
`

type ListPrimussExamsForAncodeParams struct {
	SemesterID string
	Ancode     int
}

// One ancode across all programs. The Mongo version looped over the programs and
// did one lookup each, logging (and swallowing) a not-found per program.
func (q *Queries) ListPrimussExamsForAncode(ctx context.Context, arg ListPrimussExamsForAncodeParams) ([]PrimussExam, error) {
	rows, err := q.db.Query(ctx, listPrimussExamsForAncode, arg.SemesterID, arg.Ancode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrimussExam{}
	for rows.Next() {
		var i PrimussExam
		if err := rows.Scan(
			&i.SemesterID,
			&i.Program,
			&i.Ancode,
			&i.Module,
			&i.MainExamer,
			&i.ExamType,
			&i.Presence,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrimussExamsForProgram = `-- name: ListPrimussExamsForProgram :many
select semester_id, program, ancode, module, main_examer, exam_type, presence, raw from primuss_exam
where semester_id = $1 and program = $2
order by ancode
`

type ListPrimussExamsForProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) ListPrimussExamsForProgram(ctx context.Context, arg ListPrimussExamsForProgramParams) ([]PrimussExam, error) {
	rows, err := q.db.Query(ctx, listPrimussExamsForProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrimussExam{}
	for rows.Next() {
		var i PrimussExam
		if err := rows.Scan(
			&i.SemesterID,
			&i.Program,
			&i.Ancode,
			&i.Module,
			&i.MainExamer,
			&i.ExamType,
			&i.Presence,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrimussPrograms = `-- name: ListPrimussPrograms :many
select p.program from (
    select distinct program from primuss_exam where semester_id = $1
) p
order by p.program collate "C"
`

// Program discovery. Under MongoDB this was a regex over collection names
// (`^exams_[A-Z]{2,4}(-[BM])?$`), which is also why DropPrimussData had to drop
// the collections rather than empty them: an empty exams_XY kept the program
// visible forever. Here "has exams" is the definition, so deleting the rows makes
// the program disappear by itself.
// The DISTINCT happens in a subquery: SELECT DISTINCT refuses to order by an
// expression that is not in its select list, and putting the collate there makes
// sqlc lose the column type.
func (q *Queries) ListPrimussPrograms(ctx context.Context, semesterID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPrimussPrograms, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var program string
		if err := rows.Scan(&program); err != nil {
			return nil, err
		}
		items = append(items, program)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const primussExamExists = `-- name: PrimussExamExists :one
select exists (
    select 1 from primuss_exam where semester_id = $1 and program = $2 and ancode = $3
)
`

type PrimussExamExistsParams struct {
	SemesterID string
	Program    string
	Ancode     int
}

func (q *Queries) PrimussExamExists(ctx context.Context, arg PrimussExamExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, primussExamExists, arg.SemesterID, arg.Program, arg.Ancode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
