// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: primuss_ancodes.sql

package sqlc

import (
	"context"
)

const addPrimussAncode = `-- name: AddPrimussAncode :exec
insert into exam_primuss_ancode (semester_id, ancode, program, primuss_ancode, source)
values ($1, $2, $3, $4, 'added')
on conflict (semester_id, ancode, program, primuss_ancode) do update set source = 'added'
`

type AddPrimussAncodeParams struct {
	SemesterID    string
	Ancode        int
	Program       string
	PrimussAncode int
}

// The manually added Primuss ancode mapping of a ZPA exam. Under MongoDB this was
// its own collection holding ONLY the added ones, with a unique index on
// (ancode, program); the ZPA-delivered mappings lived inside the zpaexams
// document. Here both live in one table and are told apart by `source`.
func (q *Queries) AddPrimussAncode(ctx context.Context, arg AddPrimussAncodeParams) error {
	_, err := q.db.Exec(ctx, addPrimussAncode,
		arg.SemesterID,
		arg.Ancode,
		arg.Program,
		arg.PrimussAncode,
	)
	return err
}

const deleteOtherAddedPrimussAncodes = `-- name: DeleteOtherAddedPrimussAncodes :exec
delete from exam_primuss_ancode
where semester_id = $1 and ancode = $2 and program = $3
  and source = 'added' and primuss_ancode <> $4
`

type DeleteOtherAddedPrimussAncodesParams struct {
	SemesterID    string
	Ancode        int
	Program       string
	PrimussAncode int
}

// The other half of the Mongo ReplaceOne, whose filter was (ancode, program):
// setting a different Primuss ancode for the same program replaced the mapping
// rather than adding a second one. Runs after the insert, so a crash between the
// two leaves a duplicate rather than nothing.
func (q *Queries) DeleteOtherAddedPrimussAncodes(ctx context.Context, arg DeleteOtherAddedPrimussAncodesParams) error {
	_, err := q.db.Exec(ctx, deleteOtherAddedPrimussAncodes,
		arg.SemesterID,
		arg.Ancode,
		arg.Program,
		arg.PrimussAncode,
	)
	return err
}

const listAddedPrimussAncodes = `-- name: ListAddedPrimussAncodes :many
select ancode, program, primuss_ancode from exam_primuss_ancode
where semester_id = $1 and source = 'added'
order by ancode, program collate "C"
`

type ListAddedPrimussAncodesRow struct {
	Ancode        int
	Program       string
	PrimussAncode int
}

func (q *Queries) ListAddedPrimussAncodes(ctx context.Context, semesterID string) ([]ListAddedPrimussAncodesRow, error) {
	rows, err := q.db.Query(ctx, listAddedPrimussAncodes, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddedPrimussAncodesRow{}
	for rows.Next() {
		var i ListAddedPrimussAncodesRow
		if err := rows.Scan(&i.Ancode, &i.Program, &i.PrimussAncode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddedPrimussAncodesForAncode = `-- name: ListAddedPrimussAncodesForAncode :many
select ancode, program, primuss_ancode from exam_primuss_ancode
where semester_id = $1 and ancode = $2 and source = 'added'
order by program collate "C"
`

type ListAddedPrimussAncodesForAncodeParams struct {
	SemesterID string
	Ancode     int
}

type ListAddedPrimussAncodesForAncodeRow struct {
	Ancode        int
	Program       string
	PrimussAncode int
}

func (q *Queries) ListAddedPrimussAncodesForAncode(ctx context.Context, arg ListAddedPrimussAncodesForAncodeParams) ([]ListAddedPrimussAncodesForAncodeRow, error) {
	rows, err := q.db.Query(ctx, listAddedPrimussAncodesForAncode, arg.SemesterID, arg.Ancode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddedPrimussAncodesForAncodeRow{}
	for rows.Next() {
		var i ListAddedPrimussAncodesForAncodeRow
		if err := rows.Scan(&i.Ancode, &i.Program, &i.PrimussAncode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAddedPrimussAncode = `-- name: RemoveAddedPrimussAncode :execrows
delete from exam_primuss_ancode
where semester_id = $1 and ancode = $2 and program = $3 and source = 'added'
`

type RemoveAddedPrimussAncodeParams struct {
	SemesterID string
	Ancode     int
	Program    string
}

func (q *Queries) RemoveAddedPrimussAncode(ctx context.Context, arg RemoveAddedPrimussAncodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeAddedPrimussAncode, arg.SemesterID, arg.Ancode, arg.Program)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
