// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: primuss_conflicts.sql

package sqlc

import (
	"context"
)

const listPrimussConflictsForAncode = `-- name: ListPrimussConflictsForAncode :many
select e.ancode, e.module, e.main_examer, c.other_ancode, c.num_students
from primuss_exam e
left join primuss_conflict c
       on c.semester_id = e.semester_id
      and c.program     = e.program
      and c.ancode      = e.ancode
where e.semester_id = $1 and e.program = $2 and e.ancode = $3
order by c.other_ancode
`

type ListPrimussConflictsForAncodeParams struct {
	SemesterID string
	Program    string
	Ancode     int
}

type ListPrimussConflictsForAncodeRow struct {
	Ancode      int
	Module      string
	MainExamer  string
	OtherAncode *int
	NumStudents *int
}

// The conflicts of one exam. The LEFT JOIN is what makes "this exam has no
// conflicts" a row with nulls instead of no row at all: under MongoDB every exam
// had a conflicts document even when it carried no counterpart keys, and callers
// rely on getting the module and examer back. Verified across four programs of
// 2026-SS: exactly one conflicts document per exam, in both directions.
//
// Module and main examer come from primuss_exam rather than from a second copy in
// the conflicts document (Titel/Prüfer), which could disagree with the catalogue.
func (q *Queries) ListPrimussConflictsForAncode(ctx context.Context, arg ListPrimussConflictsForAncodeParams) ([]ListPrimussConflictsForAncodeRow, error) {
	rows, err := q.db.Query(ctx, listPrimussConflictsForAncode, arg.SemesterID, arg.Program, arg.Ancode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrimussConflictsForAncodeRow{}
	for rows.Next() {
		var i ListPrimussConflictsForAncodeRow
		if err := rows.Scan(
			&i.Ancode,
			&i.Module,
			&i.MainExamer,
			&i.OtherAncode,
			&i.NumStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrimussConflictsForProgram = `-- name: ListPrimussConflictsForProgram :many
select e.ancode, e.module, e.main_examer, c.other_ancode, c.num_students
from primuss_exam e
left join primuss_conflict c
       on c.semester_id = e.semester_id
      and c.program     = e.program
      and c.ancode      = e.ancode
where e.semester_id = $1 and e.program = $2
order by e.ancode, c.other_ancode
`

type ListPrimussConflictsForProgramParams struct {
	SemesterID string
	Program    string
}

type ListPrimussConflictsForProgramRow struct {
	Ancode      int
	Module      string
	MainExamer  string
	OtherAncode *int
	NumStudents *int
}

// All conflicts of a program at once, for assembling exams without a per-exam
// lookup. Same shape, one query instead of a hand-decoded cursor.
func (q *Queries) ListPrimussConflictsForProgram(ctx context.Context, arg ListPrimussConflictsForProgramParams) ([]ListPrimussConflictsForProgramRow, error) {
	rows, err := q.db.Query(ctx, listPrimussConflictsForProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPrimussConflictsForProgramRow{}
	for rows.Next() {
		var i ListPrimussConflictsForProgramRow
		if err := rows.Scan(
			&i.Ancode,
			&i.Module,
			&i.MainExamer,
			&i.OtherAncode,
			&i.NumStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
