// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: primuss_import.sql

package sqlc

import (
	"context"
)

const deletePrimussConflictsOfProgram = `-- name: DeletePrimussConflictsOfProgram :exec
delete from primuss_conflict where semester_id = $1 and program = $2
`

type DeletePrimussConflictsOfProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) DeletePrimussConflictsOfProgram(ctx context.Context, arg DeletePrimussConflictsOfProgramParams) error {
	_, err := q.db.Exec(ctx, deletePrimussConflictsOfProgram, arg.SemesterID, arg.Program)
	return err
}

const deletePrimussCountsOfProgram = `-- name: DeletePrimussCountsOfProgram :exec
delete from primuss_count where semester_id = $1 and program = $2
`

type DeletePrimussCountsOfProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) DeletePrimussCountsOfProgram(ctx context.Context, arg DeletePrimussCountsOfProgramParams) error {
	_, err := q.db.Exec(ctx, deletePrimussCountsOfProgram, arg.SemesterID, arg.Program)
	return err
}

const deletePrimussExamsOfProgram = `-- name: DeletePrimussExamsOfProgram :exec

delete from primuss_exam where semester_id = $1 and program = $2
`

type DeletePrimussExamsOfProgramParams struct {
	SemesterID string
	Program    string
}

// Writing the Primuss Sammellisten. What used to be a drop-and-insert of
// untyped documents into five collections per program is a delete-and-insert of
// typed rows into four tables, inside one transaction per program.
//
// Order matters and the foreign keys enforce it: primuss_count and
// primuss_conflict reference primuss_exam, so the catalogue has to be written
// before the numbers that talk about it.
func (q *Queries) DeletePrimussExamsOfProgram(ctx context.Context, arg DeletePrimussExamsOfProgramParams) error {
	_, err := q.db.Exec(ctx, deletePrimussExamsOfProgram, arg.SemesterID, arg.Program)
	return err
}

const deleteStudentRegsOfProgram = `-- name: DeleteStudentRegsOfProgram :exec
delete from studentreg where semester_id = $1 and program = $2
`

type DeleteStudentRegsOfProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) DeleteStudentRegsOfProgram(ctx context.Context, arg DeleteStudentRegsOfProgramParams) error {
	_, err := q.db.Exec(ctx, deleteStudentRegsOfProgram, arg.SemesterID, arg.Program)
	return err
}

const importStudentReg = `-- name: ImportStudentReg :exec
insert into studentreg (
    semester_id, program, student_program, primuss_ancode, mtknr, group_name,
    name, presence, aaspf, raw
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type ImportStudentRegParams struct {
	SemesterID     string
	Program        string
	StudentProgram string
	PrimussAncode  int
	Mtknr          string
	GroupName      string
	Name           string
	Presence       string
	Aaspf          *int
	Raw            []byte
}

// Named ImportStudentReg because InsertStudentReg is the manual single-row
// add in studentregs.sql: that one knows neither the student's own program nor
// the AASPF, and must not start pretending it does.
func (q *Queries) ImportStudentReg(ctx context.Context, arg ImportStudentRegParams) error {
	_, err := q.db.Exec(ctx, importStudentReg,
		arg.SemesterID,
		arg.Program,
		arg.StudentProgram,
		arg.PrimussAncode,
		arg.Mtknr,
		arg.GroupName,
		arg.Name,
		arg.Presence,
		arg.Aaspf,
		arg.Raw,
	)
	return err
}

const insertPrimussConflict = `-- name: InsertPrimussConflict :exec
insert into primuss_conflict (
    semester_id, program, ancode, other_ancode, num_students
) values ($1, $2, $3, $4, $5)
`

type InsertPrimussConflictParams struct {
	SemesterID  string
	Program     string
	Ancode      int
	OtherAncode int
	NumStudents int
}

func (q *Queries) InsertPrimussConflict(ctx context.Context, arg InsertPrimussConflictParams) error {
	_, err := q.db.Exec(ctx, insertPrimussConflict,
		arg.SemesterID,
		arg.Program,
		arg.Ancode,
		arg.OtherAncode,
		arg.NumStudents,
	)
	return err
}

const insertPrimussCount = `-- name: InsertPrimussCount :exec
insert into primuss_count (semester_id, program, ancode, total, raw)
values ($1, $2, $3, $4, $5)
`

type InsertPrimussCountParams struct {
	SemesterID string
	Program    string
	Ancode     int
	Total      int
	Raw        []byte
}

func (q *Queries) InsertPrimussCount(ctx context.Context, arg InsertPrimussCountParams) error {
	_, err := q.db.Exec(ctx, insertPrimussCount,
		arg.SemesterID,
		arg.Program,
		arg.Ancode,
		arg.Total,
		arg.Raw,
	)
	return err
}

const insertPrimussExam = `-- name: InsertPrimussExam :exec
insert into primuss_exam (
    semester_id, program, ancode, module, main_examer, exam_type, presence, raw
) values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPrimussExamParams struct {
	SemesterID string
	Program    string
	Ancode     int
	Module     string
	MainExamer string
	ExamType   string
	Presence   string
	Raw        []byte
}

func (q *Queries) InsertPrimussExam(ctx context.Context, arg InsertPrimussExamParams) error {
	_, err := q.db.Exec(ctx, insertPrimussExam,
		arg.SemesterID,
		arg.Program,
		arg.Ancode,
		arg.Module,
		arg.MainExamer,
		arg.ExamType,
		arg.Presence,
		arg.Raw,
	)
	return err
}

const listPrimussAncodesOfProgram = `-- name: ListPrimussAncodesOfProgram :many
select ancode from primuss_exam
where semester_id = $1 and program = $2
order by ancode
`

type ListPrimussAncodesOfProgramParams struct {
	SemesterID string
	Program    string
}

// Which ancodes the catalogue of a program knows. The importer needs it to tell
// a conflict naming an unknown exam from one it can store -- under MongoDB such
// a cell was written anyway, as a field name nobody could resolve.
func (q *Queries) ListPrimussAncodesOfProgram(ctx context.Context, arg ListPrimussAncodesOfProgramParams) ([]int, error) {
	rows, err := q.db.Query(ctx, listPrimussAncodesOfProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var ancode int
		if err := rows.Scan(&ancode); err != nil {
			return nil, err
		}
		items = append(items, ancode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentRegRowsOfProgram = `-- name: ListStudentRegRowsOfProgram :many
select primuss_ancode, mtknr, student_program, group_name, name, presence, aaspf, raw
from studentreg
where semester_id = $1 and program = $2
order by primuss_ancode, mtknr
`

type ListStudentRegRowsOfProgramParams struct {
	SemesterID string
	Program    string
}

type ListStudentRegRowsOfProgramRow struct {
	PrimussAncode  int
	Mtknr          string
	StudentProgram string
	GroupName      string
	Name           string
	Presence       string
	Aaspf          *int
	Raw            []byte
}

func (q *Queries) ListStudentRegRowsOfProgram(ctx context.Context, arg ListStudentRegRowsOfProgramParams) ([]ListStudentRegRowsOfProgramRow, error) {
	rows, err := q.db.Query(ctx, listStudentRegRowsOfProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentRegRowsOfProgramRow{}
	for rows.Next() {
		var i ListStudentRegRowsOfProgramRow
		if err := rows.Scan(
			&i.PrimussAncode,
			&i.Mtknr,
			&i.StudentProgram,
			&i.GroupName,
			&i.Name,
			&i.Presence,
			&i.Aaspf,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
