// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms_unplaced.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUnplacedExams = `-- name: DeleteUnplacedExams :exec
delete from unplaced_exam where semester_id = $1
`

func (q *Queries) DeleteUnplacedExams(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteUnplacedExams, semesterID)
	return err
}

const listUnplacedExams = `-- name: ListUnplacedExams :many

select u.semester_id, u.ancode, u.mtknrs, u.nta_mtknr, pe.starttime
from unplaced_exam u
join plan_entry pe using (semester_id, ancode)
where u.semester_id = $1
order by u.ancode
`

type ListUnplacedExamsRow struct {
	SemesterID string
	Ancode     int
	Mtknrs     []string
	NtaMtknr   *string
	Starttime  *time.Time
}

// Students who did not fit into any room during room generation. One row per
// exam: the generator groups by ancode (plexams/roomplan_build.go:416), which is
// why this table -- unlike planned_room -- is keyed by the ancode alone.
// Starttime is joined from the plan entry, not stored -- the same treatment
// planned_room got, for the same reason. No view of its own: there is exactly one
// reader.
func (q *Queries) ListUnplacedExams(ctx context.Context, semesterID string) ([]ListUnplacedExamsRow, error) {
	rows, err := q.db.Query(ctx, listUnplacedExams, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnplacedExamsRow{}
	for rows.Next() {
		var i ListUnplacedExamsRow
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.Mtknrs,
			&i.NtaMtknr,
			&i.Starttime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUnplacedExam = `-- name: UpsertUnplacedExam :exec
insert into unplaced_exam (semester_id, ancode, mtknrs, nta_mtknr)
values ($1, $2, $3, $4)
on conflict (semester_id, ancode) do update set
    mtknrs    = excluded.mtknrs,
    nta_mtknr = excluded.nta_mtknr
`

type UpsertUnplacedExamParams struct {
	SemesterID string
	Ancode     int
	Mtknrs     []string
	NtaMtknr   *string
}

func (q *Queries) UpsertUnplacedExam(ctx context.Context, arg UpsertUnplacedExamParams) error {
	_, err := q.db.Exec(ctx, upsertUnplacedExam,
		arg.SemesterID,
		arg.Ancode,
		arg.Mtknrs,
		arg.NtaMtknr,
	)
	return err
}
