// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_requests.sql

package sqlc

import (
	"context"
	"time"
)

const deleteRoomRequests = `-- name: DeleteRoomRequests :exec
delete from room_request where semester_id = $1
`

func (q *Queries) DeleteRoomRequests(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteRoomRequests, semesterID)
	return err
}

const getRoomRequest = `-- name: GetRoomRequest :one
select semester_id, room_name, starttime, valid_from, valid_until, approved, active from room_request
where semester_id = $1 and room_name = $2 and starttime = $3
`

type GetRoomRequestParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
}

func (q *Queries) GetRoomRequest(ctx context.Context, arg GetRoomRequestParams) (RoomRequest, error) {
	row := q.db.QueryRow(ctx, getRoomRequest, arg.SemesterID, arg.RoomName, arg.Starttime)
	var i RoomRequest
	err := row.Scan(
		&i.SemesterID,
		&i.RoomName,
		&i.Starttime,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Approved,
		&i.Active,
	)
	return i, err
}

const insertRoomRequest = `-- name: InsertRoomRequest :exec
insert into room_request (
    semester_id, room_name, starttime, valid_from, valid_until, approved, active
) values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRoomRequestParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
	ValidFrom  time.Time
	ValidUntil time.Time
	Approved   bool
	Active     bool
}

func (q *Queries) InsertRoomRequest(ctx context.Context, arg InsertRoomRequestParams) error {
	_, err := q.db.Exec(ctx, insertRoomRequest,
		arg.SemesterID,
		arg.RoomName,
		arg.Starttime,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.Approved,
		arg.Active,
	)
	return err
}

const listRoomRequests = `-- name: ListRoomRequests :many

select semester_id, room_name, starttime, valid_from, valid_until, approved, active from room_request
where semester_id = $1
order by room_name collate "C", starttime
`

// Room requests to Gebäudemanagement, keyed by (room, starttime) -- see the
// table comment in 00005 for why not by valid_from.
func (q *Queries) ListRoomRequests(ctx context.Context, semesterID string) ([]RoomRequest, error) {
	rows, err := q.db.Query(ctx, listRoomRequests, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomRequest{}
	for rows.Next() {
		var i RoomRequest
		if err := rows.Scan(
			&i.SemesterID,
			&i.RoomName,
			&i.Starttime,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Approved,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomRequestActive = `-- name: SetRoomRequestActive :one
update room_request set active = $4
where semester_id = $1 and room_name = $2 and starttime = $3
returning semester_id, room_name, starttime, valid_from, valid_until, approved, active
`

type SetRoomRequestActiveParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
	Active     bool
}

func (q *Queries) SetRoomRequestActive(ctx context.Context, arg SetRoomRequestActiveParams) (RoomRequest, error) {
	row := q.db.QueryRow(ctx, setRoomRequestActive,
		arg.SemesterID,
		arg.RoomName,
		arg.Starttime,
		arg.Active,
	)
	var i RoomRequest
	err := row.Scan(
		&i.SemesterID,
		&i.RoomName,
		&i.Starttime,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Approved,
		&i.Active,
	)
	return i, err
}

const setRoomRequestApproved = `-- name: SetRoomRequestApproved :one
update room_request set approved = $4
where semester_id = $1 and room_name = $2 and starttime = $3
returning semester_id, room_name, starttime, valid_from, valid_until, approved, active
`

type SetRoomRequestApprovedParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
	Approved   bool
}

// The Mongo versions were $set of a single field and returned nil when nothing
// matched. `returning *` says both at once: no row back means no such request.
func (q *Queries) SetRoomRequestApproved(ctx context.Context, arg SetRoomRequestApprovedParams) (RoomRequest, error) {
	row := q.db.QueryRow(ctx, setRoomRequestApproved,
		arg.SemesterID,
		arg.RoomName,
		arg.Starttime,
		arg.Approved,
	)
	var i RoomRequest
	err := row.Scan(
		&i.SemesterID,
		&i.RoomName,
		&i.Starttime,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Approved,
		&i.Active,
	)
	return i, err
}

const setRoomRequestWindow = `-- name: SetRoomRequestWindow :one
update room_request set valid_from = $4, valid_until = $5
where semester_id = $1 and room_name = $2 and starttime = $3
returning semester_id, room_name, starttime, valid_from, valid_until, approved, active
`

type SetRoomRequestWindowParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
	ValidFrom  time.Time
	ValidUntil time.Time
}

func (q *Queries) SetRoomRequestWindow(ctx context.Context, arg SetRoomRequestWindowParams) (RoomRequest, error) {
	row := q.db.QueryRow(ctx, setRoomRequestWindow,
		arg.SemesterID,
		arg.RoomName,
		arg.Starttime,
		arg.ValidFrom,
		arg.ValidUntil,
	)
	var i RoomRequest
	err := row.Scan(
		&i.SemesterID,
		&i.RoomName,
		&i.Starttime,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Approved,
		&i.Active,
	)
	return i, err
}
