// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms_blocked.sql

package sqlc

import (
	"context"
	"time"
)

const deleteBlockedRoom = `-- name: DeleteBlockedRoom :execrows
delete from blocked_room
where semester_id = $1 and room_name = $2 and starttime = $3
`

type DeleteBlockedRoomParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
}

func (q *Queries) DeleteBlockedRoom(ctx context.Context, arg DeleteBlockedRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlockedRoom, arg.SemesterID, arg.RoomName, arg.Starttime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlockedRooms = `-- name: ListBlockedRooms :many

select semester_id, room_name, starttime, reason from blocked_room
where semester_id = $1
order by room_name collate "C", starttime
`

// Rooms unavailable at a given time. Unlike the room plan, the start time here is
// the block's own -- not a copy of an exam's -- so it stays a column.
func (q *Queries) ListBlockedRooms(ctx context.Context, semesterID string) ([]BlockedRoom, error) {
	rows, err := q.db.Query(ctx, listBlockedRooms, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockedRoom{}
	for rows.Next() {
		var i BlockedRoom
		if err := rows.Scan(
			&i.SemesterID,
			&i.RoomName,
			&i.Starttime,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlockedRoom = `-- name: UpsertBlockedRoom :exec
insert into blocked_room (semester_id, room_name, starttime, reason)
values ($1, $2, $3, $4)
on conflict (semester_id, room_name, starttime) do update set
    reason = excluded.reason
`

type UpsertBlockedRoomParams struct {
	SemesterID string
	RoomName   string
	Starttime  time.Time
	Reason     *string
}

func (q *Queries) UpsertBlockedRoom(ctx context.Context, arg UpsertBlockedRoomParams) error {
	_, err := q.db.Exec(ctx, upsertBlockedRoom,
		arg.SemesterID,
		arg.RoomName,
		arg.Starttime,
		arg.Reason,
	)
	return err
}
