// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_state.sql

package sqlc

import (
	"context"
	"time"
)

const getSchedulerState = `-- name: GetSchedulerState :one
select id, last_fire_at, last_finished, last_status, last_trigger, semester_id, total_changes from scheduler_state where id = 1
`

func (q *Queries) GetSchedulerState(ctx context.Context) (SchedulerState, error) {
	row := q.db.QueryRow(ctx, getSchedulerState)
	var i SchedulerState
	err := row.Scan(
		&i.ID,
		&i.LastFireAt,
		&i.LastFinished,
		&i.LastStatus,
		&i.LastTrigger,
		&i.SemesterID,
		&i.TotalChanges,
	)
	return i, err
}

const saveSchedulerState = `-- name: SaveSchedulerState :exec
insert into scheduler_state (
    id, last_fire_at, last_finished, last_status, last_trigger, semester_id, total_changes
) values (
    1, $1, $2, $3, $4, $5, $6
)
on conflict (id) do update set
    last_fire_at  = excluded.last_fire_at,
    last_finished = excluded.last_finished,
    last_status   = excluded.last_status,
    last_trigger  = excluded.last_trigger,
    semester_id   = excluded.semester_id,
    total_changes = excluded.total_changes
`

type SaveSchedulerStateParams struct {
	LastFireAt   time.Time
	LastFinished *time.Time
	LastStatus   *string
	LastTrigger  string
	SemesterID   *string
	TotalChanges int
}

func (q *Queries) SaveSchedulerState(ctx context.Context, arg SaveSchedulerStateParams) error {
	_, err := q.db.Exec(ctx, saveSchedulerState,
		arg.LastFireAt,
		arg.LastFinished,
		arg.LastStatus,
		arg.LastTrigger,
		arg.SemesterID,
		arg.TotalChanges,
	)
	return err
}

const touchSchedulerFire = `-- name: TouchSchedulerFire :exec
insert into scheduler_state (id, last_fire_at, last_trigger, semester_id)
values (1, $1, $2, $3)
on conflict (id) do update set
    last_fire_at = excluded.last_fire_at,
    last_trigger = excluded.last_trigger,
    semester_id  = excluded.semester_id
`

type TouchSchedulerFireParams struct {
	LastFireAt  time.Time
	LastTrigger string
	SemesterID  *string
}

// TouchSchedulerFire records the start of a fire: the catch-up anchor, the
// trigger and the semester, before the run executes. It must not touch the
// previous run's outcome, so the ON CONFLICT branch lists only these three
// columns -- the same reason the Mongo version used $set rather than a replace.
func (q *Queries) TouchSchedulerFire(ctx context.Context, arg TouchSchedulerFireParams) error {
	_, err := q.db.Exec(ctx, touchSchedulerFire, arg.LastFireAt, arg.LastTrigger, arg.SemesterID)
	return err
}
