// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: semester_planer.sql

package sqlc

import (
	"context"
)

const deleteSemesterPlaner = `-- name: DeleteSemesterPlaner :exec
delete from semester_planer where semester_id = $1
`

func (q *Queries) DeleteSemesterPlaner(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteSemesterPlaner, semesterID)
	return err
}

const getSemesterPlaner = `-- name: GetSemesterPlaner :one

select semester_id, name, email, test_mail, cc, noreply_mail, noreply_name from semester_planer where semester_id = $1
`

// A semester's planner override. At most one row per semester; a missing row
// means the semester inherits the planner from the server config. Every column
// is nullable for the same reason: nil is "inherit", not "empty".
//
// The successor of the global `planer` singleton (dropped in migration 00008).
func (q *Queries) GetSemesterPlaner(ctx context.Context, semesterID string) (SemesterPlaner, error) {
	row := q.db.QueryRow(ctx, getSemesterPlaner, semesterID)
	var i SemesterPlaner
	err := row.Scan(
		&i.SemesterID,
		&i.Name,
		&i.Email,
		&i.TestMail,
		&i.Cc,
		&i.NoreplyMail,
		&i.NoreplyName,
	)
	return i, err
}

const saveSemesterPlaner = `-- name: SaveSemesterPlaner :exec
insert into semester_planer (semester_id, name, email, test_mail, cc, noreply_mail, noreply_name)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (semester_id) do update set
    name         = excluded.name,
    email        = excluded.email,
    test_mail    = excluded.test_mail,
    cc           = excluded.cc,
    noreply_mail = excluded.noreply_mail,
    noreply_name = excluded.noreply_name
`

type SaveSemesterPlanerParams struct {
	SemesterID  string
	Name        *string
	Email       *string
	TestMail    *string
	Cc          *string
	NoreplyMail *string
	NoreplyName *string
}

func (q *Queries) SaveSemesterPlaner(ctx context.Context, arg SaveSemesterPlanerParams) error {
	_, err := q.db.Exec(ctx, saveSemesterPlaner,
		arg.SemesterID,
		arg.Name,
		arg.Email,
		arg.TestMail,
		arg.Cc,
		arg.NoreplyMail,
		arg.NoreplyName,
	)
	return err
}
