// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: semester_registry.sql

package sqlc

import (
	"context"
	"time"
)

const ensureSemester = `-- name: EnsureSemester :exec
insert into semester (id, schema_version)
values ($1, $2)
on conflict (id) do update set
    schema_version = case
        when semester.schema_version = 0 then excluded.schema_version
        else semester.schema_version
    end
`

type EnsureSemesterParams struct {
	ID            string
	SchemaVersion int
}

// Registering a semester and stamping the schema version of a fresh row. An
// already registered semester keeps its version: this is called on every start,
// and the version is only ever moved by Migrate.
func (q *Queries) EnsureSemester(ctx context.Context, arg EnsureSemesterParams) error {
	_, err := q.db.Exec(ctx, ensureSemester, arg.ID, arg.SchemaVersion)
	return err
}

const getSemester = `-- name: GetSemester :one

select id, schema_version, read_only, last_dump_at, created_at from semester where id = $1
`

// The semester registry: what used to be one MongoDB database per semester is
// one row here.
//
// SemesterMeta was a single document in each database's `semester_meta`
// collection. Its fields are columns of `semester` now, which is why the registry
// can answer "which semesters exist, and are they compatible?" with one query
// instead of a ListDatabaseNames plus two probes per database.
func (q *Queries) GetSemester(ctx context.Context, id string) (Semester, error) {
	row := q.db.QueryRow(ctx, getSemester, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.SchemaVersion,
		&i.ReadOnly,
		&i.LastDumpAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSemesterConfigInput = `-- name: GetSemesterConfigInput :one

select config, format_version from semester_config_input where semester_id = $1
`

type GetSemesterConfigInputRow struct {
	Config        []byte
	FormatVersion int
}

// The per-semester planning config. One row per semester, jsonb: it is an
// editable document read and written whole, and the GUI form is its shape.
func (q *Queries) GetSemesterConfigInput(ctx context.Context, semesterID string) (GetSemesterConfigInputRow, error) {
	row := q.db.QueryRow(ctx, getSemesterConfigInput, semesterID)
	var i GetSemesterConfigInputRow
	err := row.Scan(&i.Config, &i.FormatVersion)
	return i, err
}

const listSemesters = `-- name: ListSemesters :many
select s.id, s.schema_version, s.read_only, s.last_dump_at, s.created_at, (c.semester_id is not null)::bool as has_config
from semester s
left join semester_config_input c on c.semester_id = s.id
order by s.id collate "C" desc
`

type ListSemestersRow struct {
	ID            string
	SchemaVersion int
	ReadOnly      bool
	LastDumpAt    *time.Time
	CreatedAt     time.Time
	HasConfig     bool
}

// Every semester, with whether it carries a config. `compatible` was "has a
// semester_config_input document"; the left join says the same thing.
//
// Newest first. That used to sort by the stored label with the id as tie-break,
// so the canonical database came before a test clone of the same semester; the
// clones are gone and the id sorts identically ("2026-WS" > "2026-SS" > "2025-WS"
// both as a label and as an id).
//
// The ::bool cast is not decoration: without it sqlc types has_config as
// interface{}.
func (q *Queries) ListSemesters(ctx context.Context) ([]ListSemestersRow, error) {
	rows, err := q.db.Query(ctx, listSemesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSemestersRow{}
	for rows.Next() {
		var i ListSemestersRow
		if err := rows.Scan(
			&i.ID,
			&i.SchemaVersion,
			&i.ReadOnly,
			&i.LastDumpAt,
			&i.CreatedAt,
			&i.HasConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const semesterExists = `-- name: SemesterExists :one
select exists (select 1 from semester where id = $1)
`

func (q *Queries) SemesterExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, semesterExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setSemesterConfigInput = `-- name: SetSemesterConfigInput :exec
insert into semester_config_input (semester_id, config, format_version)
values ($1, $2, $3)
on conflict (semester_id) do update set
    config         = excluded.config,
    format_version = excluded.format_version
`

type SetSemesterConfigInputParams struct {
	SemesterID    string
	Config        []byte
	FormatVersion int
}

func (q *Queries) SetSemesterConfigInput(ctx context.Context, arg SetSemesterConfigInputParams) error {
	_, err := q.db.Exec(ctx, setSemesterConfigInput, arg.SemesterID, arg.Config, arg.FormatVersion)
	return err
}

const setSemesterLastDumpAt = `-- name: SetSemesterLastDumpAt :exec
update semester set last_dump_at = $2 where id = $1
`

type SetSemesterLastDumpAtParams struct {
	ID         string
	LastDumpAt *time.Time
}

func (q *Queries) SetSemesterLastDumpAt(ctx context.Context, arg SetSemesterLastDumpAtParams) error {
	_, err := q.db.Exec(ctx, setSemesterLastDumpAt, arg.ID, arg.LastDumpAt)
	return err
}

const setSemesterReadOnly = `-- name: SetSemesterReadOnly :exec
update semester set read_only = $2 where id = $1
`

type SetSemesterReadOnlyParams struct {
	ID       string
	ReadOnly bool
}

func (q *Queries) SetSemesterReadOnly(ctx context.Context, arg SetSemesterReadOnlyParams) error {
	_, err := q.db.Exec(ctx, setSemesterReadOnly, arg.ID, arg.ReadOnly)
	return err
}

const setSemesterSchemaVersion = `-- name: SetSemesterSchemaVersion :exec
update semester set schema_version = $2 where id = $1
`

type SetSemesterSchemaVersionParams struct {
	ID            string
	SchemaVersion int
}

func (q *Queries) SetSemesterSchemaVersion(ctx context.Context, arg SetSemesterSchemaVersionParams) error {
	_, err := q.db.Exec(ctx, setSemesterSchemaVersion, arg.ID, arg.SchemaVersion)
	return err
}
