// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: small_overlays.sql

package sqlc

import (
	"context"
)

const deleteAdditionalExam = `-- name: DeleteAdditionalExam :execrows
delete from additional_exam where semester_id = $1 and ancode = $2
`

type DeleteAdditionalExamParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) DeleteAdditionalExam(ctx context.Context, arg DeleteAdditionalExamParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdditionalExam, arg.SemesterID, arg.Ancode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAdditionalExamRooms = `-- name: DeleteAdditionalExamRooms :exec
delete from additional_exam_room where semester_id = $1 and ancode = $2
`

type DeleteAdditionalExamRoomsParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) DeleteAdditionalExamRooms(ctx context.Context, arg DeleteAdditionalExamRoomsParams) error {
	_, err := q.db.Exec(ctx, deleteAdditionalExamRooms, arg.SemesterID, arg.Ancode)
	return err
}

const deleteExamDurationOverride = `-- name: DeleteExamDurationOverride :execrows
delete from exam_duration_override where semester_id = $1 and ancode = $2
`

type DeleteExamDurationOverrideParams struct {
	SemesterID string
	Ancode     int
}

func (q *Queries) DeleteExamDurationOverride(ctx context.Context, arg DeleteExamDurationOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExamDurationOverride, arg.SemesterID, arg.Ancode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNtaRoomAloneWaiver = `-- name: DeleteNtaRoomAloneWaiver :execrows
delete from nta_room_alone_waiver
where semester_id = $1 and mtknr = $2 and ancode = $3
`

type DeleteNtaRoomAloneWaiverParams struct {
	SemesterID string
	Mtknr      string
	Ancode     int
}

func (q *Queries) DeleteNtaRoomAloneWaiver(ctx context.Context, arg DeleteNtaRoomAloneWaiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNtaRoomAloneWaiver, arg.SemesterID, arg.Mtknr, arg.Ancode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSpecialInterest = `-- name: DeleteSpecialInterest :execrows
delete from special_interest where semester_id = $1 and name = $2
`

type DeleteSpecialInterestParams struct {
	SemesterID string
	Name       string
}

func (q *Queries) DeleteSpecialInterest(ctx context.Context, arg DeleteSpecialInterestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpecialInterest, arg.SemesterID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAdditionalExamRoom = `-- name: InsertAdditionalExamRoom :exec
insert into additional_exam_room (
    semester_id, ancode, room_name, invigilator_id, duration_min, is_reserve,
    is_handicap, student_count
) values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAdditionalExamRoomParams struct {
	SemesterID    string
	Ancode        int
	RoomName      string
	InvigilatorID int
	DurationMin   int
	IsReserve     bool
	IsHandicap    bool
	StudentCount  int
}

func (q *Queries) InsertAdditionalExamRoom(ctx context.Context, arg InsertAdditionalExamRoomParams) error {
	_, err := q.db.Exec(ctx, insertAdditionalExamRoom,
		arg.SemesterID,
		arg.Ancode,
		arg.RoomName,
		arg.InvigilatorID,
		arg.DurationMin,
		arg.IsReserve,
		arg.IsHandicap,
		arg.StudentCount,
	)
	return err
}

const listAdditionalExamRooms = `-- name: ListAdditionalExamRooms :many
select semester_id, ancode, room_name, invigilator_id, duration_min, is_reserve, is_handicap, student_count from additional_exam_room
where semester_id = $1
order by ancode, room_name collate "C"
`

func (q *Queries) ListAdditionalExamRooms(ctx context.Context, semesterID string) ([]AdditionalExamRoom, error) {
	rows, err := q.db.Query(ctx, listAdditionalExamRooms, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdditionalExamRoom{}
	for rows.Next() {
		var i AdditionalExamRoom
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.RoomName,
			&i.InvigilatorID,
			&i.DurationMin,
			&i.IsReserve,
			&i.IsHandicap,
			&i.StudentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdditionalExams = `-- name: ListAdditionalExams :many
select semester_id, ancode, exam_date, exam_time from additional_exam
where semester_id = $1
order by ancode
`

func (q *Queries) ListAdditionalExams(ctx context.Context, semesterID string) ([]AdditionalExam, error) {
	rows, err := q.db.Query(ctx, listAdditionalExams, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdditionalExam{}
	for rows.Next() {
		var i AdditionalExam
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.ExamDate,
			&i.ExamTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExamDurationOverrides = `-- name: ListExamDurationOverrides :many

select semester_id, ancode, duration_min from exam_duration_override
where semester_id = $1
order by ancode
`

// The small per-exam overlays: duration overrides, additional (publish-only)
// exams, special-interest groups and the NTA room-alone waivers.
//
// All four are hand-entered and all four hang off an exam, so all four have the
// foreign key that used to be a report in plexams/validate_db.go.
func (q *Queries) ListExamDurationOverrides(ctx context.Context, semesterID string) ([]ExamDurationOverride, error) {
	rows, err := q.db.Query(ctx, listExamDurationOverrides, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExamDurationOverride{}
	for rows.Next() {
		var i ExamDurationOverride
		if err := rows.Scan(&i.SemesterID, &i.Ancode, &i.DurationMin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNtaRoomAloneWaivers = `-- name: ListNtaRoomAloneWaivers :many
select semester_id, ancode, mtknr, reason from nta_room_alone_waiver
where semester_id = $1
order by mtknr, ancode
`

func (q *Queries) ListNtaRoomAloneWaivers(ctx context.Context, semesterID string) ([]NtaRoomAloneWaiver, error) {
	rows, err := q.db.Query(ctx, listNtaRoomAloneWaivers, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NtaRoomAloneWaiver{}
	for rows.Next() {
		var i NtaRoomAloneWaiver
		if err := rows.Scan(
			&i.SemesterID,
			&i.Ancode,
			&i.Mtknr,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecialInterests = `-- name: ListSpecialInterests :many
select semester_id, name, filename, ancodes from special_interest
where semester_id = $1
order by name collate "C"
`

func (q *Queries) ListSpecialInterests(ctx context.Context, semesterID string) ([]SpecialInterest, error) {
	rows, err := q.db.Query(ctx, listSpecialInterests, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpecialInterest{}
	for rows.Next() {
		var i SpecialInterest
		if err := rows.Scan(
			&i.SemesterID,
			&i.Name,
			&i.Filename,
			&i.Ancodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdditionalExam = `-- name: UpsertAdditionalExam :exec
insert into additional_exam (semester_id, ancode, exam_date, exam_time)
values ($1, $2, $3, $4)
on conflict (semester_id, ancode) do update set
    exam_date = excluded.exam_date,
    exam_time = excluded.exam_time
`

type UpsertAdditionalExamParams struct {
	SemesterID string
	Ancode     int
	ExamDate   string
	ExamTime   string
}

func (q *Queries) UpsertAdditionalExam(ctx context.Context, arg UpsertAdditionalExamParams) error {
	_, err := q.db.Exec(ctx, upsertAdditionalExam,
		arg.SemesterID,
		arg.Ancode,
		arg.ExamDate,
		arg.ExamTime,
	)
	return err
}

const upsertExamDurationOverride = `-- name: UpsertExamDurationOverride :exec
insert into exam_duration_override (semester_id, ancode, duration_min)
values ($1, $2, $3)
on conflict (semester_id, ancode) do update set duration_min = excluded.duration_min
`

type UpsertExamDurationOverrideParams struct {
	SemesterID  string
	Ancode      int
	DurationMin int
}

func (q *Queries) UpsertExamDurationOverride(ctx context.Context, arg UpsertExamDurationOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertExamDurationOverride, arg.SemesterID, arg.Ancode, arg.DurationMin)
	return err
}

const upsertNtaRoomAloneWaiver = `-- name: UpsertNtaRoomAloneWaiver :exec
insert into nta_room_alone_waiver (semester_id, ancode, mtknr, reason)
values ($1, $2, $3, $4)
on conflict (semester_id, ancode, mtknr) do update set reason = excluded.reason
`

type UpsertNtaRoomAloneWaiverParams struct {
	SemesterID string
	Ancode     int
	Mtknr      string
	Reason     string
}

func (q *Queries) UpsertNtaRoomAloneWaiver(ctx context.Context, arg UpsertNtaRoomAloneWaiverParams) error {
	_, err := q.db.Exec(ctx, upsertNtaRoomAloneWaiver,
		arg.SemesterID,
		arg.Ancode,
		arg.Mtknr,
		arg.Reason,
	)
	return err
}

const upsertSpecialInterest = `-- name: UpsertSpecialInterest :exec
insert into special_interest (semester_id, name, filename, ancodes)
values ($1, $2, $3, $4)
on conflict (semester_id, name) do update set
    filename = excluded.filename,
    ancodes  = excluded.ancodes
`

type UpsertSpecialInterestParams struct {
	SemesterID string
	Name       string
	Filename   string
	Ancodes    []int
}

func (q *Queries) UpsertSpecialInterest(ctx context.Context, arg UpsertSpecialInterestParams) error {
	_, err := q.db.Exec(ctx, upsertSpecialInterest,
		arg.SemesterID,
		arg.Name,
		arg.Filename,
		arg.Ancodes,
	)
	return err
}
