// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students_prepared.sql

package sqlc

import (
	"context"
	"time"
)

const countStudentsPrepared = `-- name: CountStudentsPrepared :one

select count(*) from student_prepared where semester_id = $1
`

// The prepared per-student view: every student with their registrations, ZPA data
// and NTA resolved in one place. A computed cache, rebuilt by PrepareStudentRegs,
// so the student is one jsonb document rather than a normalised second copy of
// data that already exists relationally.
//
// Ordering goes through the document (model.Student's json tag is "name") instead
// of a duplicated name column, so there is nothing that can drift out of step
// with the blob.
func (q *Queries) CountStudentsPrepared(ctx context.Context, semesterID string) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsPrepared, semesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStudentRegUploadErrors = `-- name: DeleteStudentRegUploadErrors :exec
delete from studentreg_upload_error where semester_id = $1
`

// The ZPA upload rejects, kept so the planner can see what did not go through.
func (q *Queries) DeleteStudentRegUploadErrors(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteStudentRegUploadErrors, semesterID)
	return err
}

const deleteStudentsPrepared = `-- name: DeleteStudentsPrepared :exec
delete from student_prepared where semester_id = $1
`

func (q *Queries) DeleteStudentsPrepared(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteStudentsPrepared, semesterID)
	return err
}

const getStudentPrepared = `-- name: GetStudentPrepared :one
select student, format_version from student_prepared
where semester_id = $1 and mtknr = $2
`

type GetStudentPreparedParams struct {
	SemesterID string
	Mtknr      string
}

type GetStudentPreparedRow struct {
	Student       []byte
	FormatVersion int
}

func (q *Queries) GetStudentPrepared(ctx context.Context, arg GetStudentPreparedParams) (GetStudentPreparedRow, error) {
	row := q.db.QueryRow(ctx, getStudentPrepared, arg.SemesterID, arg.Mtknr)
	var i GetStudentPreparedRow
	err := row.Scan(&i.Student, &i.FormatVersion)
	return i, err
}

const getStudentRegsState = `-- name: GetStudentRegsState :one
select dirty, reason, changed_at from student_regs_state where semester_id = $1
`

type GetStudentRegsStateRow struct {
	Dirty     bool
	Reason    *string
	ChangedAt *time.Time
}

func (q *Queries) GetStudentRegsState(ctx context.Context, semesterID string) (GetStudentRegsStateRow, error) {
	row := q.db.QueryRow(ctx, getStudentRegsState, semesterID)
	var i GetStudentRegsStateRow
	err := row.Scan(&i.Dirty, &i.Reason, &i.ChangedAt)
	return i, err
}

const insertStudentPrepared = `-- name: InsertStudentPrepared :exec
insert into student_prepared (semester_id, mtknr, student, format_version)
values ($1, $2, $3, $4)
on conflict (semester_id, mtknr) do update set
    student        = excluded.student,
    format_version = excluded.format_version
`

type InsertStudentPreparedParams struct {
	SemesterID    string
	Mtknr         string
	Student       []byte
	FormatVersion int
}

func (q *Queries) InsertStudentPrepared(ctx context.Context, arg InsertStudentPreparedParams) error {
	_, err := q.db.Exec(ctx, insertStudentPrepared,
		arg.SemesterID,
		arg.Mtknr,
		arg.Student,
		arg.FormatVersion,
	)
	return err
}

const insertStudentRegUploadError = `-- name: InsertStudentRegUploadError :exec
insert into studentreg_upload_error (semester_id, registration, error, format_version)
values ($1, $2, $3, $4)
`

type InsertStudentRegUploadErrorParams struct {
	SemesterID    string
	Registration  []byte
	Error         []byte
	FormatVersion int
}

func (q *Queries) InsertStudentRegUploadError(ctx context.Context, arg InsertStudentRegUploadErrorParams) error {
	_, err := q.db.Exec(ctx, insertStudentRegUploadError,
		arg.SemesterID,
		arg.Registration,
		arg.Error,
		arg.FormatVersion,
	)
	return err
}

const listStudentRegUploadErrors = `-- name: ListStudentRegUploadErrors :many
select registration, error, format_version from studentreg_upload_error
where semester_id = $1
order by id
`

type ListStudentRegUploadErrorsRow struct {
	Registration  []byte
	Error         []byte
	FormatVersion int
}

func (q *Queries) ListStudentRegUploadErrors(ctx context.Context, semesterID string) ([]ListStudentRegUploadErrorsRow, error) {
	rows, err := q.db.Query(ctx, listStudentRegUploadErrors, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentRegUploadErrorsRow{}
	for rows.Next() {
		var i ListStudentRegUploadErrorsRow
		if err := rows.Scan(&i.Registration, &i.Error, &i.FormatVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsPrepared = `-- name: ListStudentsPrepared :many
select student, format_version from student_prepared
where semester_id = $1
order by student ->> 'name'
`

type ListStudentsPreparedRow struct {
	Student       []byte
	FormatVersion int
}

func (q *Queries) ListStudentsPrepared(ctx context.Context, semesterID string) ([]ListStudentsPreparedRow, error) {
	rows, err := q.db.Query(ctx, listStudentsPrepared, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsPreparedRow{}
	for rows.Next() {
		var i ListStudentsPreparedRow
		if err := rows.Scan(&i.Student, &i.FormatVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsPreparedByMtknr = `-- name: ListStudentsPreparedByMtknr :many
select student, format_version from student_prepared
where semester_id = $1 and mtknr = any($2::text[])
order by student ->> 'name'
`

type ListStudentsPreparedByMtknrParams struct {
	SemesterID string
	Mtknrs     []string
}

type ListStudentsPreparedByMtknrRow struct {
	Student       []byte
	FormatVersion int
}

func (q *Queries) ListStudentsPreparedByMtknr(ctx context.Context, arg ListStudentsPreparedByMtknrParams) ([]ListStudentsPreparedByMtknrRow, error) {
	rows, err := q.db.Query(ctx, listStudentsPreparedByMtknr, arg.SemesterID, arg.Mtknrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsPreparedByMtknrRow{}
	for rows.Next() {
		var i ListStudentsPreparedByMtknrRow
		if err := rows.Scan(&i.Student, &i.FormatVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStudentRegsState = `-- name: SetStudentRegsState :exec
insert into student_regs_state (semester_id, dirty, reason, changed_at)
values ($1, $2, $3, $4)
on conflict (semester_id) do update set
    dirty      = excluded.dirty,
    reason     = excluded.reason,
    changed_at = excluded.changed_at
`

type SetStudentRegsStateParams struct {
	SemesterID string
	Dirty      bool
	Reason     *string
	ChangedAt  *time.Time
}

func (q *Queries) SetStudentRegsState(ctx context.Context, arg SetStudentRegsStateParams) error {
	_, err := q.db.Exec(ctx, setStudentRegsState,
		arg.SemesterID,
		arg.Dirty,
		arg.Reason,
		arg.ChangedAt,
	)
	return err
}
