// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: studentregs.sql

package sqlc

import (
	"context"
)

const changeStudentRegsAncode = `-- name: ChangeStudentRegsAncode :exec
update studentreg set primuss_ancode = $4
where semester_id = $1 and program = $2 and primuss_ancode = $3
`

type ChangeStudentRegsAncodeParams struct {
	SemesterID      string
	Program         string
	PrimussAncode   int
	PrimussAncode_2 int
}

// studentreg has no foreign key to primuss_exam, so this is a plain update and
// not something the exam rename cascades into. That is deliberate: the
// registrations are source data and nothing hand-entered hangs off them.
func (q *Queries) ChangeStudentRegsAncode(ctx context.Context, arg ChangeStudentRegsAncodeParams) error {
	_, err := q.db.Exec(ctx, changeStudentRegsAncode,
		arg.SemesterID,
		arg.Program,
		arg.PrimussAncode,
		arg.PrimussAncode_2,
	)
	return err
}

const deleteOneStudentReg = `-- name: DeleteOneStudentReg :execrows
delete from studentreg where id = (
    select s.id from studentreg s
    where s.semester_id = $1 and s.program = $2 and s.primuss_ancode = $3 and s.mtknr = $4
    order by s.id
    limit 1
)
`

type DeleteOneStudentRegParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
	Mtknr         string
}

// Exactly ONE row, because the Mongo DeleteOne deleted exactly one document. It
// matters precisely in the duplicate case, which is the reason this method
// exists: deleting every matching row would take the legitimate registration
// with the duplicate.
func (q *Queries) DeleteOneStudentReg(ctx context.Context, arg DeleteOneStudentRegParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOneStudentReg,
		arg.SemesterID,
		arg.Program,
		arg.PrimussAncode,
		arg.Mtknr,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStudentReg = `-- name: InsertStudentReg :exec
insert into studentreg (semester_id, program, primuss_ancode, mtknr, name)
values ($1, $2, $3, $4, $5)
`

type InsertStudentRegParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
	Mtknr         string
	Name          string
}

// The manual add knows the exam's program and the student's name, but not the
// student's own program -- the Mongo insert wrote AnCode, MTKNR and name and
// nothing else, so student_program stays at its default.
func (q *Queries) InsertStudentReg(ctx context.Context, arg InsertStudentRegParams) error {
	_, err := q.db.Exec(ctx, insertStudentReg,
		arg.SemesterID,
		arg.Program,
		arg.PrimussAncode,
		arg.Mtknr,
		arg.Name,
	)
	return err
}

const listDuplicateStudentRegs = `-- name: ListDuplicateStudentRegs :many
select primuss_ancode as ancode, mtknr, count(*)::int as n
from studentreg
where semester_id = $1 and program = $2
group by primuss_ancode, mtknr
having count(*) > 1
order by primuss_ancode, mtknr collate "C"
`

type ListDuplicateStudentRegsParams struct {
	SemesterID string
	Program    string
}

type ListDuplicateStudentRegsRow struct {
	Ancode int
	Mtknr  string
	N      int
}

// Students registered more than once for the same exam. Reported, never
// enforced: the Primuss source data really does contain such a duplicate, so a
// unique key would reject the import instead of protecting anything.
func (q *Queries) ListDuplicateStudentRegs(ctx context.Context, arg ListDuplicateStudentRegsParams) ([]ListDuplicateStudentRegsRow, error) {
	rows, err := q.db.Query(ctx, listDuplicateStudentRegs, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateStudentRegsRow{}
	for rows.Next() {
		var i ListDuplicateStudentRegsRow
		if err := rows.Scan(&i.Ancode, &i.Mtknr, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentMtknrsByName = `-- name: ListStudentMtknrsByName :many
select distinct mtknr from studentreg
where semester_id = $1 and name ~ $2
`

type ListStudentMtknrsByNameParams struct {
	SemesterID string
	Name       string
}

// Distinct students whose name matches, across every program. POSIX regex, where
// MongoDB used its own $regex flavour; for the name searches this serves that is
// the same language.
func (q *Queries) ListStudentMtknrsByName(ctx context.Context, arg ListStudentMtknrsByNameParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStudentMtknrsByName, arg.SemesterID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var mtknr string
		if err := rows.Scan(&mtknr); err != nil {
			return nil, err
		}
		items = append(items, mtknr)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentRegsForAncode = `-- name: ListStudentRegsForAncode :many

select id, semester_id, program, student_program, primuss_ancode, mtknr, group_name, name, presence, aaspf, raw from studentreg
where semester_id = $1 and program = $2 and primuss_ancode = $3
order by name
`

type ListStudentRegsForAncodeParams struct {
	SemesterID    string
	Program       string
	PrimussAncode int
}

// Raw Primuss registrations. `program` is the EXAM's program (the former
// collection suffix); `student_program` is the student's own (Primuss column
// Stg) and is what model.StudentReg.Program carries.
func (q *Queries) ListStudentRegsForAncode(ctx context.Context, arg ListStudentRegsForAncodeParams) ([]Studentreg, error) {
	rows, err := q.db.Query(ctx, listStudentRegsForAncode, arg.SemesterID, arg.Program, arg.PrimussAncode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Studentreg{}
	for rows.Next() {
		var i Studentreg
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.Program,
			&i.StudentProgram,
			&i.PrimussAncode,
			&i.Mtknr,
			&i.GroupName,
			&i.Name,
			&i.Presence,
			&i.Aaspf,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentRegsForProgram = `-- name: ListStudentRegsForProgram :many
select id, semester_id, program, student_program, primuss_ancode, mtknr, group_name, name, presence, aaspf, raw from studentreg
where semester_id = $1 and program = $2
order by primuss_ancode, name
`

type ListStudentRegsForProgramParams struct {
	SemesterID string
	Program    string
}

func (q *Queries) ListStudentRegsForProgram(ctx context.Context, arg ListStudentRegsForProgramParams) ([]Studentreg, error) {
	rows, err := q.db.Query(ctx, listStudentRegsForProgram, arg.SemesterID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Studentreg{}
	for rows.Next() {
		var i Studentreg
		if err := rows.Scan(
			&i.ID,
			&i.SemesterID,
			&i.Program,
			&i.StudentProgram,
			&i.PrimussAncode,
			&i.Mtknr,
			&i.GroupName,
			&i.Name,
			&i.Presence,
			&i.Aaspf,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
