// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study_programs.sql

package sqlc

import (
	"context"
)

const deleteStudyProgram = `-- name: DeleteStudyProgram :execrows
delete from study_program where shortname = $1
`

func (q *Queries) DeleteStudyProgram(ctx context.Context, shortname string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudyProgram, shortname)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudyProgram = `-- name: GetStudyProgram :one
select shortname, name, degree, zpa_code, category, active, retired, external_exams_base, joint_faculty from study_program where shortname = $1
`

func (q *Queries) GetStudyProgram(ctx context.Context, shortname string) (StudyProgram, error) {
	row := q.db.QueryRow(ctx, getStudyProgram, shortname)
	var i StudyProgram
	err := row.Scan(
		&i.Shortname,
		&i.Name,
		&i.Degree,
		&i.ZpaCode,
		&i.Category,
		&i.Active,
		&i.Retired,
		&i.ExternalExamsBase,
		&i.JointFaculty,
	)
	return i, err
}

const listStudyPrograms = `-- name: ListStudyPrograms :many
select shortname, name, degree, zpa_code, category, active, retired, external_exams_base, joint_faculty from study_program order by shortname collate "C"
`

// Shortnames are codes (IF-B, DC-M, MUC.DAI), not prose: order by bytes so the
// list does not depend on the cluster's collation. Same reasoning as room names.
func (q *Queries) ListStudyPrograms(ctx context.Context) ([]StudyProgram, error) {
	rows, err := q.db.Query(ctx, listStudyPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudyProgram{}
	for rows.Next() {
		var i StudyProgram
		if err := rows.Scan(
			&i.Shortname,
			&i.Name,
			&i.Degree,
			&i.ZpaCode,
			&i.Category,
			&i.Active,
			&i.Retired,
			&i.ExternalExamsBase,
			&i.JointFaculty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudyProgram = `-- name: UpsertStudyProgram :exec
insert into study_program (
    shortname, name, degree, zpa_code, category, active, retired,
    external_exams_base, joint_faculty
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
on conflict (shortname) do update set
    name                = excluded.name,
    degree              = excluded.degree,
    zpa_code            = excluded.zpa_code,
    category            = excluded.category,
    active              = excluded.active,
    retired             = excluded.retired,
    external_exams_base = excluded.external_exams_base,
    joint_faculty       = excluded.joint_faculty
`

type UpsertStudyProgramParams struct {
	Shortname         string
	Name              string
	Degree            *string
	ZpaCode           string
	Category          string
	Active            bool
	Retired           bool
	ExternalExamsBase *int
	JointFaculty      *string
}

func (q *Queries) UpsertStudyProgram(ctx context.Context, arg UpsertStudyProgramParams) error {
	_, err := q.db.Exec(ctx, upsertStudyProgram,
		arg.Shortname,
		arg.Name,
		arg.Degree,
		arg.ZpaCode,
		arg.Category,
		arg.Active,
		arg.Retired,
		arg.ExternalExamsBase,
		arg.JointFaculty,
	)
	return err
}
