// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package sqlc

import (
	"context"
	"time"
)

const addTodoLink = `-- name: AddTodoLink :exec
insert into todo_link (semester_id, todo_id, kind, key)
values ($1, $2, $3, $4)
on conflict do nothing
`

type AddTodoLinkParams struct {
	SemesterID string
	TodoID     int64
	Kind       string
	Key        string
}

func (q *Queries) AddTodoLink(ctx context.Context, arg AddTodoLinkParams) error {
	_, err := q.db.Exec(ctx, addTodoLink,
		arg.SemesterID,
		arg.TodoID,
		arg.Kind,
		arg.Key,
	)
	return err
}

const countOpenTodosByLink = `-- name: CountOpenTodosByLink :many
select l.key, count(*)::int as count
from todo_link l
join todo t on t.semester_id = l.semester_id and t.id = l.todo_id
where l.semester_id = $1 and l.kind = $2 and t.done_at is null
group by l.key
order by l.key collate "C"
`

type CountOpenTodosByLinkParams struct {
	SemesterID string
	Kind       string
}

type CountOpenTodosByLinkRow struct {
	Key   string
	Count int
}

func (q *Queries) CountOpenTodosByLink(ctx context.Context, arg CountOpenTodosByLinkParams) ([]CountOpenTodosByLinkRow, error) {
	rows, err := q.db.Query(ctx, countOpenTodosByLink, arg.SemesterID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenTodosByLinkRow{}
	for rows.Next() {
		var i CountOpenTodosByLinkRow
		if err := rows.Scan(&i.Key, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTodo = `-- name: DeleteTodo :execrows
delete from todo where semester_id = $1 and id = $2
`

type DeleteTodoParams struct {
	SemesterID string
	ID         int64
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodo, arg.SemesterID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTodoLinks = `-- name: DeleteTodoLinks :exec
delete from todo_link where semester_id = $1 and todo_id = $2
`

type DeleteTodoLinksParams struct {
	SemesterID string
	TodoID     int64
}

func (q *Queries) DeleteTodoLinks(ctx context.Context, arg DeleteTodoLinksParams) error {
	_, err := q.db.Exec(ctx, deleteTodoLinks, arg.SemesterID, arg.TodoID)
	return err
}

const insertTodo = `-- name: InsertTodo :one
insert into todo (semester_id, title, description, priority, due_date, labels, recurring,
                  created_by, carried_from_semester, carried_from_id)
values ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10)
returning id
`

type InsertTodoParams struct {
	SemesterID          string
	Title               string
	Description         string
	Priority            string
	DueDate             *time.Time
	Labels              []string
	Recurring           bool
	CreatedBy           string
	CarriedFromSemester *string
	CarriedFromID       *int64
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTodo,
		arg.SemesterID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.Labels,
		arg.Recurring,
		arg.CreatedBy,
		arg.CarriedFromSemester,
		arg.CarriedFromID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTodoComment = `-- name: InsertTodoComment :one
insert into todo_comment (semester_id, todo_id, body, author)
values ($1, $2, $3, $4)
returning id
`

type InsertTodoCommentParams struct {
	SemesterID string
	TodoID     int64
	Body       string
	Author     string
}

func (q *Queries) InsertTodoComment(ctx context.Context, arg InsertTodoCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTodoComment,
		arg.SemesterID,
		arg.TodoID,
		arg.Body,
		arg.Author,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCarriedTodoIDs = `-- name: ListCarriedTodoIDs :many
select carried_from_id::bigint from todo
where semester_id = $1 and carried_from_semester = $2
`

type ListCarriedTodoIDsParams struct {
	SemesterID   string
	FromSemester *string
}

// The ids (in the source semester) that already have a copy in this semester.
func (q *Queries) ListCarriedTodoIDs(ctx context.Context, arg ListCarriedTodoIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCarriedTodoIDs, arg.SemesterID, arg.FromSemester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var carried_from_id int64
		if err := rows.Scan(&carried_from_id); err != nil {
			return nil, err
		}
		items = append(items, carried_from_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoComments = `-- name: ListTodoComments :many
select c.semester_id, c.todo_id, c.id, c.body, c.author, c.created_at, c.edited_at, u.name as author_name
from todo_comment c
left join app_user u on u.email = c.author
where c.semester_id = $1
  and ($2::bigint is null or c.todo_id = $2::bigint)
  and ($3::bigint is null or c.id = $3::bigint)
order by c.created_at, c.id
`

type ListTodoCommentsParams struct {
	SemesterID string
	TodoID     *int64
	ID         *int64
}

type ListTodoCommentsRow struct {
	SemesterID string
	TodoID     int64
	ID         int64
	Body       string
	Author     string
	CreatedAt  time.Time
	EditedAt   *time.Time
	AuthorName *string
}

func (q *Queries) ListTodoComments(ctx context.Context, arg ListTodoCommentsParams) ([]ListTodoCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTodoComments, arg.SemesterID, arg.TodoID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoCommentsRow{}
	for rows.Next() {
		var i ListTodoCommentsRow
		if err := rows.Scan(
			&i.SemesterID,
			&i.TodoID,
			&i.ID,
			&i.Body,
			&i.Author,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoLabels = `-- name: ListTodoLabels :many
select label from (
    select distinct unnest(labels)::text as label from todo where semester_id = $1
) l
order by label collate "C"
`

// distinct and collate "C" do not mix (see pg-db-layer-conventions), hence the subquery.
func (q *Queries) ListTodoLabels(ctx context.Context, semesterID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTodoLabels, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoLinks = `-- name: ListTodoLinks :many
select l.todo_id, l.kind, l.key,
       coalesce((case l.kind
           when 'EXAM' then (select e.module || ' (' || e.main_examer || ')' from exam e
                             where e.semester_id = l.semester_id and e.ancode::text = l.key)
           when 'TEACHER' then (select t.fullname from teacher t
                                where t.semester_id = l.semester_id and t.id::text = l.key)
           when 'ROOM' then (select r.name from room r where r.name = l.key)
           when 'STUDY_PROGRAM' then (select s.name from study_program s where s.shortname = l.key)
           when 'NTA' then (select n.name from nta n where n.mtknr = l.key)
       end), '')::text as label
from todo_link l
where l.semester_id = $1 and l.todo_id = any($2::bigint[])
order by l.todo_id, l.kind collate "C", l.key collate "C"
`

type ListTodoLinksParams struct {
	SemesterID string
	TodoIds    []int64
}

type ListTodoLinksRow struct {
	TodoID int64
	Kind   string
	Key    string
	Label  string
}

// The label of an entity link is resolved here, one query per list instead of one
// per link. Empty = the target does not exist (any more); phase/condition/day/url/
// jira labels are built in Go. Keep the case in sync with ResolveTodoLinkLabel.
func (q *Queries) ListTodoLinks(ctx context.Context, arg ListTodoLinksParams) ([]ListTodoLinksRow, error) {
	rows, err := q.db.Query(ctx, listTodoLinks, arg.SemesterID, arg.TodoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoLinksRow{}
	for rows.Next() {
		var i ListTodoLinksRow
		if err := rows.Scan(
			&i.TodoID,
			&i.Kind,
			&i.Key,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
select t.semester_id, t.id, t.title, t.description, t.priority, t.due_date, t.labels, t.recurring, t.done_at, t.done_by, t.created_at, t.created_by, t.updated_at, t.carried_from_semester, t.carried_from_id,
       (select count(*) from todo_comment c
        where c.semester_id = t.semester_id and c.todo_id = t.id)::int as comment_count,
       cu.name as created_by_name,
       du.name as done_by_name
from todo t
left join app_user cu on cu.email = t.created_by
left join app_user du on du.email = t.done_by
where t.semester_id = $1
  and ($2::bigint is null or t.id = $2::bigint)
  and ($3::boolean is null or (t.done_at is not null) = $3::boolean)
  and ($4::text is null or $4::text = any(t.labels))
  and ($5::text is null or exists (
        select 1 from todo_link l
        where l.semester_id = t.semester_id and l.todo_id = t.id
          and l.kind = $5::text and l.key = $6::text))
order by t.done_at is not null,
         t.done_at desc,
         (case t.priority when 'HIGH' then 0 when 'NORMAL' then 1 else 2 end)::int,
         t.due_date nulls last,
         t.id desc
`

type ListTodosParams struct {
	SemesterID string
	ID         *int64
	Done       *bool
	Label      *string
	LinkKind   *string
	LinkKey    *string
}

type ListTodosRow struct {
	SemesterID          string
	ID                  int64
	Title               string
	Description         string
	Priority            string
	DueDate             *time.Time
	Labels              []string
	Recurring           bool
	DoneAt              *time.Time
	DoneBy              *string
	CreatedAt           time.Time
	CreatedBy           string
	UpdatedAt           time.Time
	CarriedFromSemester *string
	CarriedFromID       *int64
	CommentCount        int
	CreatedByName       *string
	DoneByName          *string
}

// One query for the list, the detail (id) and the per-link box (link_kind/key);
// all filters are optional. Open before done, then by priority, due date and age.
func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]ListTodosRow, error) {
	rows, err := q.db.Query(ctx, listTodos,
		arg.SemesterID,
		arg.ID,
		arg.Done,
		arg.Label,
		arg.LinkKind,
		arg.LinkKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosRow{}
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.SemesterID,
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Labels,
			&i.Recurring,
			&i.DoneAt,
			&i.DoneBy,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.CarriedFromSemester,
			&i.CarriedFromID,
			&i.CommentCount,
			&i.CreatedByName,
			&i.DoneByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTodoLink = `-- name: RemoveTodoLink :execrows
delete from todo_link
where semester_id = $1 and todo_id = $2 and kind = $3 and key = $4
`

type RemoveTodoLinkParams struct {
	SemesterID string
	TodoID     int64
	Kind       string
	Key        string
}

func (q *Queries) RemoveTodoLink(ctx context.Context, arg RemoveTodoLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTodoLink,
		arg.SemesterID,
		arg.TodoID,
		arg.Kind,
		arg.Key,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveTodoLinkLabel = `-- name: ResolveTodoLinkLabel :one
select coalesce((case $1::text
    when 'EXAM' then (select e.module || ' (' || e.main_examer || ')' from exam e
                      where e.semester_id = $2 and e.ancode::text = $3::text)
    when 'TEACHER' then (select t.fullname from teacher t
                         where t.semester_id = $2 and t.id::text = $3::text)
    when 'ROOM' then (select r.name from room r where r.name = $3::text)
    when 'STUDY_PROGRAM' then (select s.name from study_program s where s.shortname = $3::text)
    when 'NTA' then (select n.name from nta n where n.mtknr = $3::text)
end), '')::text as label
`

type ResolveTodoLinkLabelParams struct {
	Kind       string
	SemesterID string
	Key        string
}

func (q *Queries) ResolveTodoLinkLabel(ctx context.Context, arg ResolveTodoLinkLabelParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveTodoLinkLabel, arg.Kind, arg.SemesterID, arg.Key)
	var label string
	err := row.Scan(&label)
	return label, err
}

const setTodoDone = `-- name: SetTodoDone :execrows
update todo set
    done_at    = case when $1::text is null then null else now() end,
    done_by    = $1::text,
    updated_at = now()
where semester_id = $2 and id = $3
`

type SetTodoDoneParams struct {
	DoneBy     *string
	SemesterID string
	ID         int64
}

// done_by null reopens the todo.
func (q *Queries) SetTodoDone(ctx context.Context, arg SetTodoDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTodoDone, arg.DoneBy, arg.SemesterID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchTodo = `-- name: TouchTodo :exec
update todo set updated_at = now() where semester_id = $1 and id = $2
`

type TouchTodoParams struct {
	SemesterID string
	ID         int64
}

func (q *Queries) TouchTodo(ctx context.Context, arg TouchTodoParams) error {
	_, err := q.db.Exec(ctx, touchTodo, arg.SemesterID, arg.ID)
	return err
}

const updateTodo = `-- name: UpdateTodo :execrows
update todo set
    title       = $1,
    description = $2,
    priority    = $3,
    due_date    = $4,
    labels      = $5,
    recurring   = $6,
    updated_at  = now()
where semester_id = $7 and id = $8
`

type UpdateTodoParams struct {
	Title       string
	Description string
	Priority    string
	DueDate     *time.Time
	Labels      []string
	Recurring   bool
	SemesterID  string
	ID          int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.Labels,
		arg.Recurring,
		arg.SemesterID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTodoComment = `-- name: UpdateTodoComment :execrows
update todo_comment set body = $1, edited_at = now()
where semester_id = $2 and id = $3 and author = $4
`

type UpdateTodoCommentParams struct {
	Body       string
	SemesterID string
	ID         int64
	Author     string
}

// Only the author may edit a comment.
func (q *Queries) UpdateTodoComment(ctx context.Context, arg UpdateTodoCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTodoComment,
		arg.Body,
		arg.SemesterID,
		arg.ID,
		arg.Author,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
