// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
delete from app_user where email = $1
`

// DeleteUser reports nothing: the Mongo version ignored the deleted count too,
// and removing an already-absent user is not an error worth surfacing.
func (q *Queries) DeleteUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUser, email)
	return err
}

const getUser = `-- name: GetUser :one
select email, name, role, shortname from app_user where email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i AppUser
	err := row.Scan(
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Shortname,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select email, name, role, shortname from app_user order by email collate "C"
`

// Email addresses are identifiers: order by bytes, as Mongo did.
func (q *Queries) ListUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Shortname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUser = `-- name: SaveUser :exec
insert into app_user (email, name, role, shortname)
values ($1, $2, $3, $4)
on conflict (email) do update set
    name      = excluded.name,
    role      = excluded.role,
    shortname = excluded.shortname
`

type SaveUserParams struct {
	Email     string
	Name      string
	Role      string
	Shortname string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.Shortname,
	)
	return err
}
