// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_secrets.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUserJiraToken = `-- name: DeleteUserJiraToken :exec
update user_secret set
    jira_key_version = null,
    jira_nonce       = null,
    jira_ciphertext  = null,
    jira_updated_at  = null
where email = $1
`

// Clears only the Jira secret and keeps the row, mirroring the Mongo $unset. A
// user without a stored secret is left alone rather than created empty.
func (q *Queries) DeleteUserJiraToken(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserJiraToken, email)
	return err
}

const getUserSecret = `-- name: GetUserSecret :one
select email, jira_key_version, jira_nonce, jira_ciphertext, jira_updated_at from user_secret where email = $1
`

func (q *Queries) GetUserSecret(ctx context.Context, email string) (UserSecret, error) {
	row := q.db.QueryRow(ctx, getUserSecret, email)
	var i UserSecret
	err := row.Scan(
		&i.Email,
		&i.JiraKeyVersion,
		&i.JiraNonce,
		&i.JiraCiphertext,
		&i.JiraUpdatedAt,
	)
	return i, err
}

const saveUserJiraToken = `-- name: SaveUserJiraToken :exec
insert into user_secret (email, jira_key_version, jira_nonce, jira_ciphertext, jira_updated_at)
values ($1, $2, $3, $4, $5)
on conflict (email) do update set
    jira_key_version = excluded.jira_key_version,
    jira_nonce       = excluded.jira_nonce,
    jira_ciphertext  = excluded.jira_ciphertext,
    jira_updated_at  = excluded.jira_updated_at
`

type SaveUserJiraTokenParams struct {
	Email          string
	JiraKeyVersion *int
	JiraNonce      []byte
	JiraCiphertext []byte
	JiraUpdatedAt  *time.Time
}

// The four Jira columns are written together: the schema check enforces that a
// sealed value is all-or-nothing, because a half-written secret cannot be opened.
func (q *Queries) SaveUserJiraToken(ctx context.Context, arg SaveUserJiraTokenParams) error {
	_, err := q.db.Exec(ctx, saveUserJiraToken,
		arg.Email,
		arg.JiraKeyVersion,
		arg.JiraNonce,
		arg.JiraCiphertext,
		arg.JiraUpdatedAt,
	)
	return err
}
