// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zpa.sql

package sqlc

import (
	"context"
	"time"
)

const deleteInvigilations = `-- name: DeleteInvigilations :exec
delete from invigilation
where semester_id = $1 and is_self_invigilation = $2
`

type DeleteInvigilationsParams struct {
	SemesterID         string
	IsSelfInvigilation bool
}

// The two invigilation targets share one table and are told apart by
// is_self_invigilation, so each replaces only its own half.
func (q *Queries) DeleteInvigilations(ctx context.Context, arg DeleteInvigilationsParams) error {
	_, err := q.db.Exec(ctx, deleteInvigilations, arg.SemesterID, arg.IsSelfInvigilation)
	return err
}

const deleteInvigilatorRequirements = `-- name: DeleteInvigilatorRequirements :exec
delete from invigilator_requirement where semester_id = $1
`

func (q *Queries) DeleteInvigilatorRequirements(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteInvigilatorRequirements, semesterID)
	return err
}

const deleteTeachers = `-- name: DeleteTeachers :exec
delete from teacher where semester_id = $1
`

func (q *Queries) DeleteTeachers(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteTeachers, semesterID)
	return err
}

const deleteZPAStudents = `-- name: DeleteZPAStudents :exec

delete from zpa_student where semester_id = $1
`

// ---------------------------------------------------------------------------
// The four ReplaceAll targets (db/save.go). Each is source data replaced
// wholesale by an import or a generation run, and nothing references any of
// them -- which is why replacing is safe here and would not be for the exams.
// ---------------------------------------------------------------------------
func (q *Queries) DeleteZPAStudents(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteZPAStudents, semesterID)
	return err
}

const getTeacher = `-- name: GetTeacher :one
select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 and id = $2
`

type GetTeacherParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) GetTeacher(ctx context.Context, arg GetTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, arg.SemesterID, arg.ID)
	var i Teacher
	err := row.Scan(
		&i.SemesterID,
		&i.ID,
		&i.Shortname,
		&i.Fullname,
		&i.Email,
		&i.IsProf,
		&i.IsLba,
		&i.IsProfHc,
		&i.IsStaff,
		&i.IsActive,
		&i.LastSemester,
		&i.Fk,
	)
	return i, err
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 and lower(email) = lower($2::text)
`

type GetTeacherByEmailParams struct {
	SemesterID string
	Email      string
}

// Case-insensitive: ZPA stores raw addresses, our user emails are lower-cased.
// The index is on lower(email) for exactly this query.
func (q *Queries) GetTeacherByEmail(ctx context.Context, arg GetTeacherByEmailParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByEmail, arg.SemesterID, arg.Email)
	var i Teacher
	err := row.Scan(
		&i.SemesterID,
		&i.ID,
		&i.Shortname,
		&i.Fullname,
		&i.Email,
		&i.IsProf,
		&i.IsLba,
		&i.IsProfHc,
		&i.IsStaff,
		&i.IsActive,
		&i.LastSemester,
		&i.Fk,
	)
	return i, err
}

const getTeacherIDByName = `-- name: GetTeacherIDByName :one
select id from teacher
where semester_id = $1 and fullname ~ $2::text
order by id
limit 1
`

type GetTeacherIDByNameParams struct {
	SemesterID string
	Name       string
}

// A substring match on the full name, which is what the Mongo $regex without
// anchors did. POSIX rather than PCRE, same language for names.
func (q *Queries) GetTeacherIDByName(ctx context.Context, arg GetTeacherIDByNameParams) (int, error) {
	row := q.db.QueryRow(ctx, getTeacherIDByName, arg.SemesterID, arg.Name)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getZPAStudent = `-- name: GetZPAStudent :one
select semester_id, mtknr, greeting, first_name, last_name, email, gender, group_name from zpa_student where semester_id = $1 and mtknr = $2
`

type GetZPAStudentParams struct {
	SemesterID string
	Mtknr      string
}

func (q *Queries) GetZPAStudent(ctx context.Context, arg GetZPAStudentParams) (ZpaStudent, error) {
	row := q.db.QueryRow(ctx, getZPAStudent, arg.SemesterID, arg.Mtknr)
	var i ZpaStudent
	err := row.Scan(
		&i.SemesterID,
		&i.Mtknr,
		&i.Greeting,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Gender,
		&i.GroupName,
	)
	return i, err
}

const insertInvigilation = `-- name: InsertInvigilation :exec
insert into invigilation (
    semester_id, invigilator_id, starttime, room_name, duration_min,
    is_reserve, is_self_invigilation, pre_planned
) values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertInvigilationParams struct {
	SemesterID         string
	InvigilatorID      int
	Starttime          time.Time
	RoomName           *string
	DurationMin        int
	IsReserve          bool
	IsSelfInvigilation bool
	PrePlanned         bool
}

func (q *Queries) InsertInvigilation(ctx context.Context, arg InsertInvigilationParams) error {
	_, err := q.db.Exec(ctx, insertInvigilation,
		arg.SemesterID,
		arg.InvigilatorID,
		arg.Starttime,
		arg.RoomName,
		arg.DurationMin,
		arg.IsReserve,
		arg.IsSelfInvigilation,
		arg.PrePlanned,
	)
	return err
}

const insertInvigilatorRequirement = `-- name: InsertInvigilatorRequirement :exec
insert into invigilator_requirement (
    semester_id, invigilator_id, invigilator, excluded_dates, part_time,
    oral_exams_contribution, livecoding_contribution, master_contribution,
    free_semester, overtime_last_semester, overtime_this_semester
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
on conflict (semester_id, invigilator_id) do update set
    invigilator             = excluded.invigilator,
    excluded_dates          = excluded.excluded_dates,
    part_time               = excluded.part_time,
    oral_exams_contribution = excluded.oral_exams_contribution,
    livecoding_contribution = excluded.livecoding_contribution,
    master_contribution     = excluded.master_contribution,
    free_semester           = excluded.free_semester,
    overtime_last_semester  = excluded.overtime_last_semester,
    overtime_this_semester  = excluded.overtime_this_semester
`

type InsertInvigilatorRequirementParams struct {
	SemesterID             string
	InvigilatorID          int
	Invigilator            string
	ExcludedDates          []string
	PartTime               float64
	OralExamsContribution  int
	LivecodingContribution int
	MasterContribution     int
	FreeSemester           float64
	OvertimeLastSemester   float64
	OvertimeThisSemester   float64
}

func (q *Queries) InsertInvigilatorRequirement(ctx context.Context, arg InsertInvigilatorRequirementParams) error {
	_, err := q.db.Exec(ctx, insertInvigilatorRequirement,
		arg.SemesterID,
		arg.InvigilatorID,
		arg.Invigilator,
		arg.ExcludedDates,
		arg.PartTime,
		arg.OralExamsContribution,
		arg.LivecodingContribution,
		arg.MasterContribution,
		arg.FreeSemester,
		arg.OvertimeLastSemester,
		arg.OvertimeThisSemester,
	)
	return err
}

const insertTeacher = `-- name: InsertTeacher :exec
insert into teacher (
    semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc,
    is_staff, is_active, last_semester, fk
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
on conflict (semester_id, id) do update set
    shortname     = excluded.shortname,
    fullname      = excluded.fullname,
    email         = excluded.email,
    is_prof       = excluded.is_prof,
    is_lba        = excluded.is_lba,
    is_prof_hc    = excluded.is_prof_hc,
    is_staff      = excluded.is_staff,
    is_active     = excluded.is_active,
    last_semester = excluded.last_semester,
    fk            = excluded.fk
`

type InsertTeacherParams struct {
	SemesterID   string
	ID           int
	Shortname    string
	Fullname     string
	Email        string
	IsProf       bool
	IsLba        bool
	IsProfHc     bool
	IsStaff      bool
	IsActive     bool
	LastSemester string
	Fk           string
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) error {
	_, err := q.db.Exec(ctx, insertTeacher,
		arg.SemesterID,
		arg.ID,
		arg.Shortname,
		arg.Fullname,
		arg.Email,
		arg.IsProf,
		arg.IsLba,
		arg.IsProfHc,
		arg.IsStaff,
		arg.IsActive,
		arg.LastSemester,
		arg.Fk,
	)
	return err
}

const insertZPAStudent = `-- name: InsertZPAStudent :exec
insert into zpa_student (
    semester_id, mtknr, greeting, first_name, last_name, email, gender, group_name
) values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (semester_id, mtknr) do update set
    greeting   = excluded.greeting,
    first_name = excluded.first_name,
    last_name  = excluded.last_name,
    email      = excluded.email,
    gender     = excluded.gender,
    group_name = excluded.group_name
`

type InsertZPAStudentParams struct {
	SemesterID string
	Mtknr      string
	Greeting   string
	FirstName  string
	LastName   string
	Email      string
	Gender     string
	GroupName  string
}

func (q *Queries) InsertZPAStudent(ctx context.Context, arg InsertZPAStudentParams) error {
	_, err := q.db.Exec(ctx, insertZPAStudent,
		arg.SemesterID,
		arg.Mtknr,
		arg.Greeting,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Gender,
		arg.GroupName,
	)
	return err
}

const listTeachers = `-- name: ListTeachers :many

select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 order by fullname
`

// Teachers and students, both mirrored read-only from ZPA.
func (q *Queries) ListTeachers(ctx context.Context, semesterID string) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.SemesterID,
			&i.ID,
			&i.Shortname,
			&i.Fullname,
			&i.Email,
			&i.IsProf,
			&i.IsLba,
			&i.IsProfHc,
			&i.IsStaff,
			&i.IsActive,
			&i.LastSemester,
			&i.Fk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZPAStudents = `-- name: ListZPAStudents :many
select semester_id, mtknr, greeting, first_name, last_name, email, gender, group_name from zpa_student where semester_id = $1 order by last_name, first_name
`

func (q *Queries) ListZPAStudents(ctx context.Context, semesterID string) ([]ZpaStudent, error) {
	rows, err := q.db.Query(ctx, listZPAStudents, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZpaStudent{}
	for rows.Next() {
		var i ZpaStudent
		if err := rows.Scan(
			&i.SemesterID,
			&i.Mtknr,
			&i.Greeting,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Gender,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
