// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zpa.sql

package sqlc

import (
	"context"
)

const deleteTeachers = `-- name: DeleteTeachers :exec
delete from teacher where semester_id = $1
`

func (q *Queries) DeleteTeachers(ctx context.Context, semesterID string) error {
	_, err := q.db.Exec(ctx, deleteTeachers, semesterID)
	return err
}

const getTeacher = `-- name: GetTeacher :one
select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 and id = $2
`

type GetTeacherParams struct {
	SemesterID string
	ID         int
}

func (q *Queries) GetTeacher(ctx context.Context, arg GetTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, arg.SemesterID, arg.ID)
	var i Teacher
	err := row.Scan(
		&i.SemesterID,
		&i.ID,
		&i.Shortname,
		&i.Fullname,
		&i.Email,
		&i.IsProf,
		&i.IsLba,
		&i.IsProfHc,
		&i.IsStaff,
		&i.IsActive,
		&i.LastSemester,
		&i.Fk,
	)
	return i, err
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 and lower(email) = lower($2::text)
`

type GetTeacherByEmailParams struct {
	SemesterID string
	Email      string
}

// Case-insensitive: ZPA stores raw addresses, our user emails are lower-cased.
// The index is on lower(email) for exactly this query.
func (q *Queries) GetTeacherByEmail(ctx context.Context, arg GetTeacherByEmailParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByEmail, arg.SemesterID, arg.Email)
	var i Teacher
	err := row.Scan(
		&i.SemesterID,
		&i.ID,
		&i.Shortname,
		&i.Fullname,
		&i.Email,
		&i.IsProf,
		&i.IsLba,
		&i.IsProfHc,
		&i.IsStaff,
		&i.IsActive,
		&i.LastSemester,
		&i.Fk,
	)
	return i, err
}

const getTeacherIDByName = `-- name: GetTeacherIDByName :one
select id from teacher
where semester_id = $1 and fullname ~ $2::text
order by id
limit 1
`

type GetTeacherIDByNameParams struct {
	SemesterID string
	Name       string
}

// A substring match on the full name, which is what the Mongo $regex without
// anchors did. POSIX rather than PCRE, same language for names.
func (q *Queries) GetTeacherIDByName(ctx context.Context, arg GetTeacherIDByNameParams) (int, error) {
	row := q.db.QueryRow(ctx, getTeacherIDByName, arg.SemesterID, arg.Name)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getZPAStudent = `-- name: GetZPAStudent :one
select semester_id, mtknr, greeting, first_name, last_name, email, gender, group_name from zpa_student where semester_id = $1 and mtknr = $2
`

type GetZPAStudentParams struct {
	SemesterID string
	Mtknr      string
}

func (q *Queries) GetZPAStudent(ctx context.Context, arg GetZPAStudentParams) (ZpaStudent, error) {
	row := q.db.QueryRow(ctx, getZPAStudent, arg.SemesterID, arg.Mtknr)
	var i ZpaStudent
	err := row.Scan(
		&i.SemesterID,
		&i.Mtknr,
		&i.Greeting,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Gender,
		&i.GroupName,
	)
	return i, err
}

const insertTeacher = `-- name: InsertTeacher :exec
insert into teacher (
    semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc,
    is_staff, is_active, last_semester, fk
) values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
on conflict (semester_id, id) do update set
    shortname     = excluded.shortname,
    fullname      = excluded.fullname,
    email         = excluded.email,
    is_prof       = excluded.is_prof,
    is_lba        = excluded.is_lba,
    is_prof_hc    = excluded.is_prof_hc,
    is_staff      = excluded.is_staff,
    is_active     = excluded.is_active,
    last_semester = excluded.last_semester,
    fk            = excluded.fk
`

type InsertTeacherParams struct {
	SemesterID   string
	ID           int
	Shortname    string
	Fullname     string
	Email        string
	IsProf       bool
	IsLba        bool
	IsProfHc     bool
	IsStaff      bool
	IsActive     bool
	LastSemester string
	Fk           string
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) error {
	_, err := q.db.Exec(ctx, insertTeacher,
		arg.SemesterID,
		arg.ID,
		arg.Shortname,
		arg.Fullname,
		arg.Email,
		arg.IsProf,
		arg.IsLba,
		arg.IsProfHc,
		arg.IsStaff,
		arg.IsActive,
		arg.LastSemester,
		arg.Fk,
	)
	return err
}

const listTeachers = `-- name: ListTeachers :many

select semester_id, id, shortname, fullname, email, is_prof, is_lba, is_prof_hc, is_staff, is_active, last_semester, fk from teacher where semester_id = $1 order by fullname
`

// Teachers and students, both mirrored read-only from ZPA.
func (q *Queries) ListTeachers(ctx context.Context, semesterID string) ([]Teacher, error) {
	rows, err := q.db.Query(ctx, listTeachers, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.SemesterID,
			&i.ID,
			&i.Shortname,
			&i.Fullname,
			&i.Email,
			&i.IsProf,
			&i.IsLba,
			&i.IsProfHc,
			&i.IsStaff,
			&i.IsActive,
			&i.LastSemester,
			&i.Fk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZPAStudents = `-- name: ListZPAStudents :many
select semester_id, mtknr, greeting, first_name, last_name, email, gender, group_name from zpa_student where semester_id = $1 order by last_name, first_name
`

func (q *Queries) ListZPAStudents(ctx context.Context, semesterID string) ([]ZpaStudent, error) {
	rows, err := q.db.Query(ctx, listZPAStudents, semesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZpaStudent{}
	for rows.Next() {
		var i ZpaStudent
		if err := rows.Scan(
			&i.SemesterID,
			&i.Mtknr,
			&i.Greeting,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Gender,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
