// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnCode struct {
	AnCode int `json:"anCode"`
}

type ConnectedExam struct {
	ZpaExam      *ZPAExam       `json:"zpaExam"`
	PrimussExams []*PrimussExam `json:"primussExams"`
}

type NTAInput struct {
	Name                 string `json:"name"`
	Mtknr                string `json:"mtknr"`
	Compensation         string `json:"compensation"`
	DeltaDurationPercent int    `json:"deltaDurationPercent"`
	NeedsRoomAlone       bool   `json:"needsRoomAlone"`
	Program              string `json:"program"`
	From                 string `json:"from"`
	Until                string `json:"until"`
}

type PrimussExamByProgram struct {
	Program string         `json:"program"`
	Exams   []*PrimussExam `json:"exams"`
}

type PrimussExamInput struct {
	AnCode  int    `json:"anCode"`
	Program string `json:"program"`
}

type Semester struct {
	ID string `json:"id"`
}

type Step struct {
	Number int    `json:"number"`
	Name   string `json:"name"`
	Done   bool   `json:"done"`
}

type ZPAExamsForType struct {
	Type  string     `json:"type"`
	Exams []*ZPAExam `json:"exams"`
}
